class BankExecutor {
 public static void main(String[] args){

    Bank b1 = new Bank();
    b1.setBankId(1);
    System.out.println("Bank Id:" +b1.getBankId());
    b1.setBankName("SBI");
    System.out.println("Bank Name:" +b1.getBankName());
    b1.setBranch("Bangalore");
    System.out.println("Branch:" +b1.getBranch());
    b1.setIfsc("SBIN0001");
    System.out.println("IFSC:" +b1.getIfsc());
    b1.setBalance(50000);
    System.out.println("Balance:" +b1.getBalance());
    b1.setAccountType("Savings");
    System.out.println("Account Type:" +b1.getAccountType());
    b1.setCustomerName("Harsha");
    System.out.println("Customer:" +b1.getCustomerName());

    System.out.println();
    Bank b2 = new Bank();
    b2.setBankId(2);
    System.out.println("Bank Id:" +b2.getBankId());
    b2.setBankName("HDFC");
    System.out.println("Bank Name:" +b2.getBankName());
    b2.setBranch("BTM Layout");
    System.out.println("Branch:" +b2.getBranch());
    b2.setIfsc("HDFC0002");
    System.out.println("IFSC:" +b2.getIfsc());
    b2.setBalance(75000);
    System.out.println("Balance:" +b2.getBalance());
    b2.setAccountType("Current");
    System.out.println("Account Type:" +b2.getAccountType());
    b2.setCustomerName("Lohith");
    System.out.println("Customer:" +b2.getCustomerName());

    System.out.println();
    Bank b3 = new Bank();
    b3.setBankId(3);
    System.out.println("Bank Id:" +b3.getBankId());
    b3.setBankName("ICICI");
    System.out.println("Bank Name:" +b3.getBankName());
    b3.setBranch("Chennai");
    System.out.println("Branch:" +b3.getBranch());
    b3.setIfsc("ICIC0003");
    System.out.println("IFSC:" +b3.getIfsc());
    b3.setBalance(60000);
    System.out.println("Balance:" +b3.getBalance());
    b3.setAccountType("Savings");
    System.out.println("Account Type:" +b3.getAccountType());
    b3.setCustomerName("Kiran");
    System.out.println("Customer:" +b3.getCustomerName());

    System.out.println();
    Bank b4 = new Bank();
    b4.setBankId(4);
    System.out.println("Bank Id:" +b4.getBankId());
    b4.setBankName("Axis");
    System.out.println("Bank Name:" +b4.getBankName());
    b4.setBranch("Hyderabad");
    System.out.println("Branch:" +b4.getBranch());
    b4.setIfsc("AXIS0004");
    System.out.println("IFSC:" +b4.getIfsc());
    b4.setBalance(82000);
    System.out.println("Balance:" +b4.getBalance());
    b4.setAccountType("Savings");
    System.out.println("Account Type:" +b4.getAccountType());
    b4.setCustomerName("Suresh");
    System.out.println("Customer:" +b4.getCustomerName());

    System.out.println();
    Bank b5 = new Bank();
    b5.setBankId(5);
    System.out.println("Bank Id:" +b5.getBankId());
    b5.setBankName("Canara");
    System.out.println("Bank Name:" +b5.getBankName());
    b5.setBranch("Delhi");
    System.out.println("Branch:" +b5.getBranch());
    b5.setIfsc("CNRB0005");
    System.out.println("IFSC:" +b5.getIfsc());
    b5.setBalance(45000);
    System.out.println("Balance:" +b5.getBalance());
    b5.setAccountType("Current");
    System.out.println("Account Type:" +b5.getAccountType());
    b5.setCustomerName("Ravi");
    System.out.println("Customer:" +b5.getCustomerName());
	
	
	System.out.println();
    Bank b6 = new Bank();
    b6.setBankId(6);
    System.out.println("Bank Id:" +b6.getBankId());
    b6.setBankName("SBI");
    System.out.println("Bank Name:" +b6.getBankName());
    b6.setBranch("Mumbai");
    System.out.println("Branch:" +b6.getBranch());
    b6.setIfsc("SBIN0006");
    System.out.println("IFSC:" +b6.getIfsc());
    b6.setBalance(50000);
    System.out.println("Balance:" +b6.getBalance());
    b6.setAccountType("Savings");
    System.out.println("Account Type:" +b6.getAccountType());
    b6.setCustomerName("Amit");
    System.out.println("Customer:" +b6.getCustomerName());

    System.out.println();
    Bank b7 = new Bank();
    b7.setBankId(7);
    System.out.println("Bank Id:" +b7.getBankId());
    b7.setBankName("HDFC");
    System.out.println("Bank Name:" +b7.getBankName());
    b7.setBranch("Bangalore");
    System.out.println("Branch:" +b7.getBranch());
    b7.setIfsc("HDFC0007");
    System.out.println("IFSC:" +b7.getIfsc());
    b7.setBalance(75000);
    System.out.println("Balance:" +b7.getBalance());
    b7.setAccountType("Current");
    System.out.println("Account Type:" +b7.getAccountType());
    b7.setCustomerName("Sneha");
    System.out.println("Customer:" +b7.getCustomerName());

    System.out.println();
    Bank b8 = new Bank();
    b8.setBankId(8);
    System.out.println("Bank Id:" +b8.getBankId());
    b8.setBankName("ICICI");
    System.out.println("Bank Name:" +b8.getBankName());
    b8.setBranch("Hyderabad");
    System.out.println("Branch:" +b8.getBranch());
    b8.setIfsc("ICIC0008");
    System.out.println("IFSC:" +b8.getIfsc());
    b8.setBalance(62000);
    System.out.println("Balance:" +b8.getBalance());
    b8.setAccountType("Savings");
    System.out.println("Account Type:" +b8.getAccountType());
    b8.setCustomerName("Kiran");
    System.out.println("Customer:" +b8.getCustomerName());

    System.out.println();
    Bank b9 = new Bank();
    b9.setBankId(9);
    System.out.println("Bank Id:" +b9.getBankId());
    b9.setBankName("Axis");
    System.out.println("Bank Name:" +b9.getBankName());
    b9.setBranch("Chennai");
    System.out.println("Branch:" +b9.getBranch());
    b9.setIfsc("UTIB0009");
    System.out.println("IFSC:" +b9.getIfsc());
    b9.setBalance(88000);
    System.out.println("Balance:" +b9.getBalance());
    b9.setAccountType("Current");
    System.out.println("Account Type:" +b9.getAccountType());
    b9.setCustomerName("Divya");
    System.out.println("Customer:" +b9.getCustomerName());

    System.out.println();
    Bank b10 = new Bank();
    b10.setBankId(10);
    System.out.println("Bank Id:" +b10.getBankId());
    b10.setBankName("PNB");
    System.out.println("Bank Name:" +b10.getBankName());
    b10.setBranch("Pune");
    System.out.println("Branch:" +b10.getBranch());
    b10.setIfsc("PUNB0010");
    System.out.println("IFSC:" +b10.getIfsc());
    b10.setBalance(54000);
    System.out.println("Balance:" +b10.getBalance());
    b10.setAccountType("Savings");
    System.out.println("Account Type:" +b10.getAccountType());
    b10.setCustomerName("Arjun");
    System.out.println("Customer:" +b10.getCustomerName());
	
	System.out.println();
    Bank b11 = new Bank();
    b11.setBankId(11);
    System.out.println("Bank Id:" +b11.getBankId());
    b11.setBankName("Union Bank");
    System.out.println("Bank Name:" +b11.getBankName());
    b11.setBranch("Kolkata");
    System.out.println("Branch:" +b11.getBranch());
    b11.setIfsc("UBIN0011");
    System.out.println("IFSC:" +b11.getIfsc());
    b11.setBalance(67000);
    System.out.println("Balance:" +b11.getBalance());
    b11.setAccountType("Savings");
    System.out.println("Account Type:" +b11.getAccountType());
    b11.setCustomerName("Rahul");
    System.out.println("Customer:" +b11.getCustomerName());

    System.out.println();
    Bank b12 = new Bank();
    b12.setBankId(12);
    System.out.println("Bank Id:" +b12.getBankId());
    b12.setBankName("Kotak");
    System.out.println("Bank Name:" +b12.getBankName());
    b12.setBranch("Jaipur");
    System.out.println("Branch:" +b12.getBranch());
    b12.setIfsc("KKBK0012");
    System.out.println("IFSC:" +b12.getIfsc());
    b12.setBalance(72000);
    System.out.println("Balance:" +b12.getBalance());
    b12.setAccountType("Current");
    System.out.println("Account Type:" +b12.getAccountType());
    b12.setCustomerName("Pooja");
    System.out.println("Customer:" +b12.getCustomerName());

    System.out.println();
    Bank b13 = new Bank();
    b13.setBankId(13);
    System.out.println("Bank Id:" +b13.getBankId());
    b13.setBankName("Yes Bank");
    System.out.println("Bank Name:" +b13.getBankName());
    b13.setBranch("Lucknow");
    System.out.println("Branch:" +b13.getBranch());
    b13.setIfsc("YESB0013");
    System.out.println("IFSC:" +b13.getIfsc());
    b13.setBalance(81000);
    System.out.println("Balance:" +b13.getBalance());
    b13.setAccountType("Savings");
    System.out.println("Account Type:" +b13.getAccountType());
    b13.setCustomerName("Suresh");
    System.out.println("Customer:" +b13.getCustomerName());

    System.out.println();
    Bank b14 = new Bank();
    b14.setBankId(14);
    System.out.println("Bank Id:" +b14.getBankId());
    b14.setBankName("IDBI");
    System.out.println("Bank Name:" +b14.getBankName());
    b14.setBranch("Bhopal");
    System.out.println("Branch:" +b14.getBranch());
    b14.setIfsc("IBKL0014");
    System.out.println("IFSC:" +b14.getIfsc());
    b14.setBalance(60000);
    System.out.println("Balance:" +b14.getBalance());
    b14.setAccountType("Current");
    System.out.println("Account Type:" +b14.getAccountType());
    b14.setCustomerName("Anjali");
    System.out.println("Customer:" +b14.getCustomerName());

    System.out.println();
    Bank b15 = new Bank();
    b15.setBankId(15);
    System.out.println("Bank Id:" +b15.getBankId());
    b15.setBankName("Bank of Baroda");
    System.out.println("Bank Name:" +b15.getBankName());
    b15.setBranch("Ahmedabad");
    System.out.println("Branch:" +b15.getBranch());
    b15.setIfsc("BARB0015");
    System.out.println("IFSC:" +b15.getIfsc());
    b15.setBalance(95000);
    System.out.println("Balance:" +b15.getBalance());
    b15.setAccountType("Savings");
    System.out.println("Account Type:" +b15.getAccountType());
    b15.setCustomerName("Vijay");
    System.out.println("Customer:" +b15.getCustomerName());

    System.out.println();
    Bank b16 = new Bank();
    b16.setBankId(16);
    System.out.println("Bank Id:" +b16.getBankId());
    b16.setBankName("Indian Bank");
    System.out.println("Bank Name:" +b16.getBankName());
    b16.setBranch("Nagpur");
    System.out.println("Branch:" +b16.getBranch());
    b16.setIfsc("IDIB0016");
    System.out.println("IFSC:" +b16.getIfsc());
    b16.setBalance(58000);
    System.out.println("Balance:" +b16.getBalance());
    b16.setAccountType("Current");
    System.out.println("Account Type:" +b16.getAccountType());
    b16.setCustomerName("Deepa");
    System.out.println("Customer:" +b16.getCustomerName());

    System.out.println();
    Bank b17 = new Bank();
    b17.setBankId(17);
    System.out.println("Bank Id:" +b17.getBankId());
    b17.setBankName("Central Bank");
    System.out.println("Bank Name:" +b17.getBankName());
    b17.setBranch("Coimbatore");
    System.out.println("Branch:" +b17.getBranch());
    b17.setIfsc("CBIN0017");
    System.out.println("IFSC:" +b17.getIfsc());
    b17.setBalance(67000);
    System.out.println("Balance:" +b17.getBalance());
    b17.setAccountType("Savings");
    System.out.println("Account Type:" +b17.getAccountType());
    b17.setCustomerName("Karthik");
    System.out.println("Customer:" +b17.getCustomerName());

    System.out.println();
    Bank b18 = new Bank();
    b18.setBankId(18);
    System.out.println("Bank Id:" +b18.getBankId());
    b18.setBankName("UCO Bank");
    System.out.println("Bank Name:" +b18.getBankName());
    b18.setBranch("Trivandrum");
    System.out.println("Branch:" +b18.getBranch());
    b18.setIfsc("UCBA0018");
    System.out.println("IFSC:" +b18.getIfsc());
    b18.setBalance(43000);
    System.out.println("Balance:" +b18.getBalance());
    b18.setAccountType("Current");
    System.out.println("Account Type:" +b18.getAccountType());
    b18.setCustomerName("Meena");
    System.out.println("Customer:" +b18.getCustomerName());

    System.out.println();
    Bank b19 = new Bank();
    b19.setBankId(19);
    System.out.println("Bank Id:" +b19.getBankId());
    b19.setBankName("South Indian Bank");
    System.out.println("Bank Name:" +b19.getBankName());
    b19.setBranch("Goa");
    System.out.println("Branch:" +b19.getBranch());
    b19.setIfsc("SIBL0019");
    System.out.println("IFSC:" +b19.getIfsc());
    b19.setBalance(77000);
    System.out.println("Balance:" +b19.getBalance());
    b19.setAccountType("Savings");
    System.out.println("Account Type:" +b19.getAccountType());
    b19.setCustomerName("Arjun");
    System.out.println("Customer:" +b19.getCustomerName());

    System.out.println();
    Bank b20 = new Bank();
    b20.setBankId(20);
    System.out.println("Bank Id:" +b20.getBankId());
    b20.setBankName("Federal Bank");
    System.out.println("Bank Name:" +b20.getBankName());
    b20.setBranch("Bangalore");
    System.out.println("Branch:" +b20.getBranch());
    b20.setIfsc("FDRL0020");
    System.out.println("IFSC:" +b20.getIfsc());
    b20.setBalance(88000);
    System.out.println("Balance:" +b20.getBalance());
    b20.setAccountType("Current");
    System.out.println("Account Type:" +b20.getAccountType());
    b20.setCustomerName("Tarun");
    System.out.println("Customer:" +b20.getCustomerName());
	
	System.out.println();
    Bank b21 = new Bank();
    b21.setBankId(21);
    System.out.println("Bank Id:" +b21.getBankId());
    b21.setBankName("Indian Overseas Bank");
    System.out.println("Bank Name:" +b21.getBankName());
    b21.setBranch("Mysore");
    System.out.println("Branch:" +b21.getBranch());
    b21.setIfsc("IOBA0021");
    System.out.println("IFSC:" +b21.getIfsc());
    b21.setBalance(56000);
    System.out.println("Balance:" +b21.getBalance());
    b21.setAccountType("Savings");
    System.out.println("Account Type:" +b21.getAccountType());
    b21.setCustomerName("Nikhil");
    System.out.println("Customer:" +b21.getCustomerName());

    System.out.println();
    Bank b22 = new Bank();
    b22.setBankId(22);
    System.out.println("Bank Id:" +b22.getBankId());
    b22.setBankName("Karnataka Bank");
    System.out.println("Bank Name:" +b22.getBankName());
    b22.setBranch("Hubli");
    System.out.println("Branch:" +b22.getBranch());
    b22.setIfsc("KARB0022");
    System.out.println("IFSC:" +b22.getIfsc());
    b22.setBalance(73000);
    System.out.println("Balance:" +b22.getBalance());
    b22.setAccountType("Current");
    System.out.println("Account Type:" +b22.getAccountType());
    b22.setCustomerName("Pooja");
    System.out.println("Customer:" +b22.getCustomerName());

    System.out.println();
    Bank b23 = new Bank();
    b23.setBankId(23);
    System.out.println("Bank Id:" +b23.getBankId());
    b23.setBankName("Dena Bank");
    System.out.println("Bank Name:" +b23.getBankName());
    b23.setBranch("Belgaum");
    System.out.println("Branch:" +b23.getBranch());
    b23.setIfsc("BKDN0023");
    System.out.println("IFSC:" +b23.getIfsc());
    b23.setBalance(64000);
    System.out.println("Balance:" +b23.getBalance());
    b23.setAccountType("Savings");
    System.out.println("Account Type:" +b23.getAccountType());
    b23.setCustomerName("Ramesh");
    System.out.println("Customer:" +b23.getCustomerName());

    System.out.println();
    Bank b24 = new Bank();
    b24.setBankId(24);
    System.out.println("Bank Id:" +b24.getBankId());
    b24.setBankName("Syndicate Bank");
    System.out.println("Bank Name:" +b24.getBankName());
    b24.setBranch("Mangalore");
    System.out.println("Branch:" +b24.getBranch());
    b24.setIfsc("SYNB0024");
    System.out.println("IFSC:" +b24.getIfsc());
    b24.setBalance(82000);
    System.out.println("Balance:" +b24.getBalance());
    b24.setAccountType("Current");
    System.out.println("Account Type:" +b24.getAccountType());
    b24.setCustomerName("Sneha");
    System.out.println("Customer:" +b24.getCustomerName());

    System.out.println();
    Bank b25 = new Bank();
    b25.setBankId(25);
    System.out.println("Bank Id:" +b25.getBankId());
    b25.setBankName("Allahabad Bank");
    System.out.println("Bank Name:" +b25.getBankName());
    b25.setBranch("Udupi");
    System.out.println("Branch:" +b25.getBranch());
    b25.setIfsc("ALLA0025");
    System.out.println("IFSC:" +b25.getIfsc());
    b25.setBalance(47000);
    System.out.println("Balance:" +b25.getBalance());
    b25.setAccountType("Savings");
    System.out.println("Account Type:" +b25.getAccountType());
    b25.setCustomerName("Vikram");
    System.out.println("Customer:" +b25.getCustomerName());

    System.out.println();
    Bank b26 = new Bank();
    b26.setBankId(26);
    System.out.println("Bank Id:" +b26.getBankId());
    b26.setBankName("Andhra Bank");
    System.out.println("Bank Name:" +b26.getBankName());
    b26.setBranch("Tumkur");
    System.out.println("Branch:" +b26.getBranch());
    b26.setIfsc("ANDB0026");
    System.out.println("IFSC:" +b26.getIfsc());
    b26.setBalance(69000);
    System.out.println("Balance:" +b26.getBalance());
    b26.setAccountType("Current");
    System.out.println("Account Type:" +b26.getAccountType());
    b26.setCustomerName("Anjali");
    System.out.println("Customer:" +b26.getCustomerName());

    System.out.println();
    Bank b27 = new Bank();
    b27.setBankId(27);
    System.out.println("Bank Id:" +b27.getBankId());
    b27.setBankName("Corporation Bank");
    System.out.println("Bank Name:" +b27.getBankName());
    b27.setBranch("Davangere");
    System.out.println("Branch:" +b27.getBranch());
    b27.setIfsc("CORP0027");
    System.out.println("IFSC:" +b27.getIfsc());
    b27.setBalance(76000);
    System.out.println("Balance:" +b27.getBalance());
    b27.setAccountType("Savings");
    System.out.println("Account Type:" +b27.getAccountType());
    b27.setCustomerName("Kiran");
    System.out.println("Customer:" +b27.getCustomerName());

    System.out.println();
    Bank b28 = new Bank();
    b28.setBankId(28);
    System.out.println("Bank Id:" +b28.getBankId());
    b28.setBankName("Oriental Bank");
    System.out.println("Bank Name:" +b28.getBankName());
    b28.setBranch("Shimoga");
    System.out.println("Branch:" +b28.getBranch());
    b28.setIfsc("ORBC0028");
    System.out.println("IFSC:" +b28.getIfsc());
    b28.setBalance(52000);
    System.out.println("Balance:" +b28.getBalance());
    b28.setAccountType("Current");
    System.out.println("Account Type:" +b28.getAccountType());
    b28.setCustomerName("Deepa");
    System.out.println("Customer:" +b28.getCustomerName());

    System.out.println();
    Bank b29 = new Bank();
    b29.setBankId(29);
    System.out.println("Bank Id:" +b29.getBankId());
    b29.setBankName("Vijaya Bank");
    System.out.println("Bank Name:" +b29.getBankName());
    b29.setBranch("Bellary");
    System.out.println("Branch:" +b29.getBranch());
    b29.setIfsc("VIJB0029");
    System.out.println("IFSC:" +b29.getIfsc());
    b29.setBalance(61000);
    System.out.println("Balance:" +b29.getBalance());
    b29.setAccountType("Savings");
    System.out.println("Account Type:" +b29.getAccountType());
    b29.setCustomerName("Arun");
    System.out.println("Customer:" +b29.getCustomerName());
 }
}