class CaseEvidenceExecutor {
 public static void main(String[] args){
    CaseEvidence c1 = new CaseEvidence();
    c1.setEvidenceId(1);
    System.out.println("Evidence Id:" +c1.getEvidenceId());
    c1.setCaseName("Robbery Case");
    System.out.println("Case:" +c1.getCaseName());
    c1.setEvidenceType("Fingerprint");
    System.out.println("Type:" +c1.getEvidenceType());
    c1.setDescription("Fingerprint on door");
    System.out.println("Description:" +c1.getDescription());
    c1.setCollectedBy("Officer Ravi");
    System.out.println("Collected By:" +c1.getCollectedBy());
    c1.setDate("01-03-2026");
    System.out.println("Date:" +c1.getDate());
    c1.setStatus("Verified");
    System.out.println("Status:" +c1.getStatus());

    System.out.println();
    CaseEvidence c2 = new CaseEvidence();
    c2.setEvidenceId(2);
    System.out.println("Evidence Id:" +c2.getEvidenceId());
    c2.setCaseName("Murder Case");
    System.out.println("Case:" +c2.getCaseName());
    c2.setEvidenceType("Weapon");
    System.out.println("Type:" +c2.getEvidenceType());
    c2.setDescription("Knife found at scene");
    System.out.println("Description:" +c2.getDescription());
    c2.setCollectedBy("Officer Meena");
    System.out.println("Collected By:" +c2.getCollectedBy());
    c2.setDate("02-03-2026");
    System.out.println("Date:" +c2.getDate());
    c2.setStatus("Under Investigation");
    System.out.println("Status:" +c2.getStatus());
	
	System.out.println();
    CaseEvidence c3 = new CaseEvidence();
    c3.setEvidenceId(3);
    System.out.println("Evidence Id:" +c3.getEvidenceId());
    c3.setCaseName("Cyber Crime");
    System.out.println("Case:" +c3.getCaseName());
    c3.setEvidenceType("Email Logs");
    System.out.println("Type:" +c3.getEvidenceType());
    c3.setDescription("Suspicious email records");
    System.out.println("Description:" +c3.getDescription());
    c3.setCollectedBy("Officer Kiran");
    System.out.println("Collected By:" +c3.getCollectedBy());
    c3.setDate("03-03-2026");
    System.out.println("Date:" +c3.getDate());
    c3.setStatus("Verified");
    System.out.println("Status:" +c3.getStatus());

    System.out.println();
    CaseEvidence c4 = new CaseEvidence();
    c4.setEvidenceId(4);
    System.out.println("Evidence Id:" +c4.getEvidenceId());
    c4.setCaseName("Fraud Case");
    System.out.println("Case:" +c4.getCaseName());
    c4.setEvidenceType("Documents");
    System.out.println("Type:" +c4.getEvidenceType());
    c4.setDescription("Fake financial records");
    System.out.println("Description:" +c4.getDescription());
    c4.setCollectedBy("Officer Anil");
    System.out.println("Collected By:" +c4.getCollectedBy());
    c4.setDate("04-03-2026");
    System.out.println("Date:" +c4.getDate());
    c4.setStatus("Under Investigation");
    System.out.println("Status:" +c4.getStatus());

    System.out.println();
    CaseEvidence c5 = new CaseEvidence();
    c5.setEvidenceId(5);
    System.out.println("Evidence Id:" +c5.getEvidenceId());
    c5.setCaseName("Accident Case");
    System.out.println("Case:" +c5.getCaseName());
    c5.setEvidenceType("CCTV Footage");
    System.out.println("Type:" +c5.getEvidenceType());
    c5.setDescription("Video recording from street");
    System.out.println("Description:" +c5.getDescription());
    c5.setCollectedBy("Officer Ravi");
    System.out.println("Collected By:" +c5.getCollectedBy());
    c5.setDate("05-03-2026");
    System.out.println("Date:" +c5.getDate());
    c5.setStatus("Verified");
    System.out.println("Status:" +c5.getStatus());

    System.out.println();
    CaseEvidence c6 = new CaseEvidence();
    c6.setEvidenceId(6);
    System.out.println("Evidence Id:" +c6.getEvidenceId());
    c6.setCaseName("Theft Case");
    System.out.println("Case:" +c6.getCaseName());
    c6.setEvidenceType("Witness Statement");
    System.out.println("Type:" +c6.getEvidenceType());
    c6.setDescription("Statement from nearby person");
    System.out.println("Description:" +c6.getDescription());
    c6.setCollectedBy("Officer Meena");
    System.out.println("Collected By:" +c6.getCollectedBy());
    c6.setDate("06-03-2026");
    System.out.println("Date:" +c6.getDate());
    c6.setStatus("Pending");
    System.out.println("Status:" +c6.getStatus());

    System.out.println();
    CaseEvidence c7 = new CaseEvidence();
    c7.setEvidenceId(7);
    System.out.println("Evidence Id:" +c7.getEvidenceId());
    c7.setCaseName("Kidnap Case");
    System.out.println("Case:" +c7.getCaseName());
    c7.setEvidenceType("Call Records");
    System.out.println("Type:" +c7.getEvidenceType());
    c7.setDescription("Phone call details");
    System.out.println("Description:" +c7.getDescription());
    c7.setCollectedBy("Officer Suresh");
    System.out.println("Collected By:" +c7.getCollectedBy());
    c7.setDate("07-03-2026");
    System.out.println("Date:" +c7.getDate());
    c7.setStatus("Under Investigation");
    System.out.println("Status:" +c7.getStatus());

    System.out.println();
    CaseEvidence c8 = new CaseEvidence();
    c8.setEvidenceId(8);
    System.out.println("Evidence Id:" +c8.getEvidenceId());
    c8.setCaseName("Drug Case");
    System.out.println("Case:" +c8.getCaseName());
    c8.setEvidenceType("Substance Sample");
    System.out.println("Type:" +c8.getEvidenceType());
    c8.setDescription("Illegal drug sample");
    System.out.println("Description:" +c8.getDescription());
    c8.setCollectedBy("Officer Deepa");
    System.out.println("Collected By:" +c8.getCollectedBy());
    c8.setDate("08-03-2026");
    System.out.println("Date:" +c8.getDate());
    c8.setStatus("Verified");
    System.out.println("Status:" +c8.getStatus());

    System.out.println();
    CaseEvidence c9 = new CaseEvidence();
    c9.setEvidenceId(9);
    System.out.println("Evidence Id:" +c9.getEvidenceId());
    c9.setCaseName("Arson Case");
    System.out.println("Case:" +c9.getCaseName());
    c9.setEvidenceType("Burn Materials");
    System.out.println("Type:" +c9.getEvidenceType());
    c9.setDescription("Remains of burned items");
    System.out.println("Description:" +c9.getDescription());
    c9.setCollectedBy("Officer Kumar");
    System.out.println("Collected By:" +c9.getCollectedBy());
    c9.setDate("09-03-2026");
    System.out.println("Date:" +c9.getDate());
    c9.setStatus("Pending");
    System.out.println("Status:" +c9.getStatus());

    System.out.println();
    CaseEvidence c10 = new CaseEvidence();
    c10.setEvidenceId(10);
    System.out.println("Evidence Id:" +c10.getEvidenceId());
    c10.setCaseName("Assault Case");
    System.out.println("Case:" +c10.getCaseName());
    c10.setEvidenceType("Medical Report");
    System.out.println("Type:" +c10.getEvidenceType());
    c10.setDescription("Injury details report");
    System.out.println("Description:" +c10.getDescription());
    c10.setCollectedBy("Officer Anjali");
    System.out.println("Collected By:" +c10.getCollectedBy());
    c10.setDate("10-03-2026");
    System.out.println("Date:" +c10.getDate());
    c10.setStatus("Verified");
    System.out.println("Status:" +c10.getStatus());

 }
}