class ClothExecutor {
 public static void main(String[] args){

    System.out.println();
    Cloth c1 = new Cloth();
    c1.setClothId(1);
    System.out.println("Cloth Id:" +c1.getClothId());
    c1.setName("T-Shirt");
    System.out.println("Name:" +c1.getName());
    c1.setType("Casual");
    System.out.println("Type:" +c1.getType());
    c1.setBrand("Nike");
    System.out.println("Brand:" +c1.getBrand());
    c1.setPrice(799);
    System.out.println("Price:" +c1.getPrice());
    c1.setSize("M");
    System.out.println("Size:" +c1.getSize());
    c1.setColor("Black");
    System.out.println("Color:" +c1.getColor());

    System.out.println();
    Cloth c2 = new Cloth();
    c2.setClothId(2);
    System.out.println("Cloth Id:" +c2.getClothId());
    c2.setName("Shirt");
    System.out.println("Name:" +c2.getName());
    c2.setType("Formal");
    System.out.println("Type:" +c2.getType());
    c2.setBrand("Peter England");
    System.out.println("Brand:" +c2.getBrand());
    c2.setPrice(1299);
    System.out.println("Price:" +c2.getPrice());
    c2.setSize("L");
    System.out.println("Size:" +c2.getSize());
    c2.setColor("White");
    System.out.println("Color:" +c2.getColor());
	
	System.out.println();
    Cloth c3 = new Cloth();
    c3.setClothId(3);
    System.out.println("Cloth Id:" +c3.getClothId());
    c3.setName("Jeans");
    System.out.println("Name:" +c3.getName());
    c3.setType("Casual");
    System.out.println("Type:" +c3.getType());
    c3.setBrand("Levis");
    System.out.println("Brand:" +c3.getBrand());
    c3.setPrice(1999);
    System.out.println("Price:" +c3.getPrice());
    c3.setSize("32");
    System.out.println("Size:" +c3.getSize());
    c3.setColor("Blue");
    System.out.println("Color:" +c3.getColor());

    System.out.println();
    Cloth c4 = new Cloth();
    c4.setClothId(4);
    System.out.println("Cloth Id:" +c4.getClothId());
    c4.setName("Kurta");
    System.out.println("Name:" +c4.getName());
    c4.setType("Traditional");
    System.out.println("Type:" +c4.getType());
    c4.setBrand("FabIndia");
    System.out.println("Brand:" +c4.getBrand());
    c4.setPrice(1499);
    System.out.println("Price:" +c4.getPrice());
    c4.setSize("L");
    System.out.println("Size:" +c4.getSize());
    c4.setColor("Green");
    System.out.println("Color:" +c4.getColor());

    System.out.println();
    Cloth c5 = new Cloth();
    c5.setClothId(5);
    System.out.println("Cloth Id:" +c5.getClothId());
    c5.setName("Jacket");
    System.out.println("Name:" +c5.getName());
    c5.setType("Winter");
    System.out.println("Type:" +c5.getType());
    c5.setBrand("Puma");
    System.out.println("Brand:" +c5.getBrand());
    c5.setPrice(2999);
    System.out.println("Price:" +c5.getPrice());
    c5.setSize("XL");
    System.out.println("Size:" +c5.getSize());
    c5.setColor("Black");
    System.out.println("Color:" +c5.getColor());

    System.out.println();
    Cloth c6 = new Cloth();
    c6.setClothId(6);
    System.out.println("Cloth Id:" +c6.getClothId());
    c6.setName("Saree");
    System.out.println("Name:" +c6.getName());
    c6.setType("Traditional");
    System.out.println("Type:" +c6.getType());
    c6.setBrand("Kanchipuram");
    System.out.println("Brand:" +c6.getBrand());
    c6.setPrice(5000);
    System.out.println("Price:" +c6.getPrice());
    c6.setSize("Free");
    System.out.println("Size:" +c6.getSize());
    c6.setColor("Red");
    System.out.println("Color:" +c6.getColor());

    System.out.println();
    Cloth c7 = new Cloth();
    c7.setClothId(7);
    System.out.println("Cloth Id:" +c7.getClothId());
    c7.setName("Shorts");
    System.out.println("Name:" +c7.getName());
    c7.setType("Casual");
    System.out.println("Type:" +c7.getType());
    c7.setBrand("Adidas");
    System.out.println("Brand:" +c7.getBrand());
    c7.setPrice(899);
    System.out.println("Price:" +c7.getPrice());
    c7.setSize("M");
    System.out.println("Size:" +c7.getSize());
    c7.setColor("Grey");
    System.out.println("Color:" +c7.getColor());

    System.out.println();
    Cloth c8 = new Cloth();
    c8.setClothId(8);
    System.out.println("Cloth Id:" +c8.getClothId());
    c8.setName("Blazer");
    System.out.println("Name:" +c8.getName());
    c8.setType("Formal");
    System.out.println("Type:" +c8.getType());
    c8.setBrand("Raymond");
    System.out.println("Brand:" +c8.getBrand());
    c8.setPrice(4500);
    System.out.println("Price:" +c8.getPrice());
    c8.setSize("L");
    System.out.println("Size:" +c8.getSize());
    c8.setColor("Navy Blue");
    System.out.println("Color:" +c8.getColor());

    System.out.println();
    Cloth c9 = new Cloth();
    c9.setClothId(9);
    System.out.println("Cloth Id:" +c9.getClothId());
    c9.setName("Hoodie");
    System.out.println("Name:" +c9.getName());
    c9.setType("Winter");
    System.out.println("Type:" +c9.getType());
    c9.setBrand("Zara");
    System.out.println("Brand:" +c9.getBrand());
    c9.setPrice(2500);
    System.out.println("Price:" +c9.getPrice());
    c9.setSize("M");
    System.out.println("Size:" +c9.getSize());
    c9.setColor("Brown");
    System.out.println("Color:" +c9.getColor());

    System.out.println();
    Cloth c10 = new Cloth();
    c10.setClothId(10);
    System.out.println("Cloth Id:" +c10.getClothId());
    c10.setName("Track Pants");
    System.out.println("Name:" +c10.getName());
    c10.setType("Sports");
    System.out.println("Type:" +c10.getType());
    c10.setBrand("Reebok");
    System.out.println("Brand:" +c10.getBrand());
    c10.setPrice(1200);
    System.out.println("Price:" +c10.getPrice());
    c10.setSize("L");
    System.out.println("Size:" +c10.getSize());
    c10.setColor("Black");
    System.out.println("Color:" +c10.getColor());

 }
}