class Esp32Executor {
 public static void main(String[] args){
    System.out.println();
    Esp32 e1 = new Esp32();
    e1.setDeviceId(1);
    System.out.println("Device Id:" +e1.getDeviceId());
    e1.setBoardName("ESP32 DevKit V1");
    System.out.println("Board:" +e1.getBoardName());
    e1.setFlashSize(4);
    System.out.println("Flash (MB):" +e1.getFlashSize());
    e1.setRamSize(520);
    System.out.println("RAM (KB):" +e1.getRamSize());
    e1.setWifi(true);
    System.out.println("WiFi:" +e1.getWifi());
    e1.setBluetooth(true);
    System.out.println("Bluetooth:" +e1.getBluetooth());
    e1.setClockSpeed(240);
    System.out.println("Clock (MHz):" +e1.getClockSpeed());

    System.out.println();
    Esp32 e2 = new Esp32();
    e2.setDeviceId(2);
    System.out.println("Device Id:" +e2.getDeviceId());
    e2.setBoardName("ESP32 WROOM");
    System.out.println("Board:" +e2.getBoardName());
    e2.setFlashSize(8);
    System.out.println("Flash (MB):" +e2.getFlashSize());
    e2.setRamSize(520);
    System.out.println("RAM (KB):" +e2.getRamSize());
    e2.setWifi(true);
    System.out.println("WiFi:" +e2.getWifi());
    e2.setBluetooth(true);
    System.out.println("Bluetooth:" +e2.getBluetooth());
    e2.setClockSpeed(160);
    System.out.println("Clock (MHz):" +e2.getClockSpeed());
	
	System.out.println();
    Esp32 e3 = new Esp32();
    e3.setDeviceId(3);
    System.out.println("Device Id:" +e3.getDeviceId());
    e3.setBoardName("ESP32 Pico");
    System.out.println("Board:" +e3.getBoardName());
    e3.setFlashSize(4);
    System.out.println("Flash (MB):" +e3.getFlashSize());
    e3.setRamSize(448);
    System.out.println("RAM (KB):" +e3.getRamSize());
    e3.setWifi(true);
    System.out.println("WiFi:" +e3.getWifi());
    e3.setBluetooth(true);
    System.out.println("Bluetooth:" +e3.getBluetooth());
    e3.setClockSpeed(240);
    System.out.println("Clock (MHz):" +e3.getClockSpeed());

    System.out.println();
    Esp32 e4 = new Esp32();
    e4.setDeviceId(4);
    System.out.println("Device Id:" +e4.getDeviceId());
    e4.setBoardName("ESP32 S2");
    System.out.println("Board:" +e4.getBoardName());
    e4.setFlashSize(8);
    System.out.println("Flash (MB):" +e4.getFlashSize());
    e4.setRamSize(320);
    System.out.println("RAM (KB):" +e4.getRamSize());
    e4.setWifi(true);
    System.out.println("WiFi:" +e4.getWifi());
    e4.setBluetooth(false);
    System.out.println("Bluetooth:" +e4.getBluetooth());
    e4.setClockSpeed(240);
    System.out.println("Clock (MHz):" +e4.getClockSpeed());

    System.out.println();
    Esp32 e5 = new Esp32();
    e5.setDeviceId(5);
    System.out.println("Device Id:" +e5.getDeviceId());
    e5.setBoardName("ESP32 S3");
    System.out.println("Board:" +e5.getBoardName());
    e5.setFlashSize(16);
    System.out.println("Flash (MB):" +e5.getFlashSize());
    e5.setRamSize(512);
    System.out.println("RAM (KB):" +e5.getRamSize());
    e5.setWifi(true);
    System.out.println("WiFi:" +e5.getWifi());
    e5.setBluetooth(true);
    System.out.println("Bluetooth:" +e5.getBluetooth());
    e5.setClockSpeed(240);
    System.out.println("Clock (MHz):" +e5.getClockSpeed());

    System.out.println();
    Esp32 e6 = new Esp32();
    e6.setDeviceId(6);
    System.out.println("Device Id:" +e6.getDeviceId());
    e6.setBoardName("ESP32 C3");
    System.out.println("Board:" +e6.getBoardName());
    e6.setFlashSize(4);
    System.out.println("Flash (MB):" +e6.getFlashSize());
    e6.setRamSize(400);
    System.out.println("RAM (KB):" +e6.getRamSize());
    e6.setWifi(true);
    System.out.println("WiFi:" +e6.getWifi());
    e6.setBluetooth(true);
    System.out.println("Bluetooth:" +e6.getBluetooth());
    e6.setClockSpeed(160);
    System.out.println("Clock (MHz):" +e6.getClockSpeed());

    System.out.println();
    Esp32 e7 = new Esp32();
    e7.setDeviceId(7);
    System.out.println("Device Id:" +e7.getDeviceId());
    e7.setBoardName("ESP32 WROVER");
    System.out.println("Board:" +e7.getBoardName());
    e7.setFlashSize(8);
    System.out.println("Flash (MB):" +e7.getFlashSize());
    e7.setRamSize(520);
    System.out.println("RAM (KB):" +e7.getRamSize());
    e7.setWifi(true);
    System.out.println("WiFi:" +e7.getWifi());
    e7.setBluetooth(true);
    System.out.println("Bluetooth:" +e7.getBluetooth());
    e7.setClockSpeed(240);
    System.out.println("Clock (MHz):" +e7.getClockSpeed());

    System.out.println();
    Esp32 e8 = new Esp32();
    e8.setDeviceId(8);
    System.out.println("Device Id:" +e8.getDeviceId());
    e8.setBoardName("ESP32 Lite");
    System.out.println("Board:" +e8.getBoardName());
    e8.setFlashSize(2);
    System.out.println("Flash (MB):" +e8.getFlashSize());
    e8.setRamSize(256);
    System.out.println("RAM (KB):" +e8.getRamSize());
    e8.setWifi(true);
    System.out.println("WiFi:" +e8.getWifi());
    e8.setBluetooth(false);
    System.out.println("Bluetooth:" +e8.getBluetooth());
    e8.setClockSpeed(120);
    System.out.println("Clock (MHz):" +e8.getClockSpeed());

    System.out.println();
    Esp32 e9 = new Esp32();
    e9.setDeviceId(9);
    System.out.println("Device Id:" +e9.getDeviceId());
    e9.setBoardName("ESP32 Mini");
    System.out.println("Board:" +e9.getBoardName());
    e9.setFlashSize(4);
    System.out.println("Flash (MB):" +e9.getFlashSize());
    e9.setRamSize(320);
    System.out.println("RAM (KB):" +e9.getRamSize());
    e9.setWifi(true);
    System.out.println("WiFi:" +e9.getWifi());
    e9.setBluetooth(true);
    System.out.println("Bluetooth:" +e9.getBluetooth());
    e9.setClockSpeed(160);
    System.out.println("Clock (MHz):" +e9.getClockSpeed());

    System.out.println();
    Esp32 e10 = new Esp32();
    e10.setDeviceId(10);
    System.out.println("Device Id:" +e10.getDeviceId());
    e10.setBoardName("ESP32 Pro");
    System.out.println("Board:" +e10.getBoardName());
    e10.setFlashSize(32);
    System.out.println("Flash (MB):" +e10.getFlashSize());
    e10.setRamSize(520);
    System.out.println("RAM (KB):" +e10.getRamSize());
    e10.setWifi(true);
    System.out.println("WiFi:" +e10.getWifi());
    e10.setBluetooth(true);
    System.out.println("Bluetooth:" +e10.getBluetooth());
    e10.setClockSpeed(240);
    System.out.println("Clock (MHz):" +e10.getClockSpeed());

 }
}