class FertilizerExecutor {
 public static void main(String[] args){
    System.out.println();
    Fertilizer f1 = new Fertilizer();
    f1.setFertilizerId(1);
    System.out.println("Fertilizer Id:" +f1.getFertilizerId());
    f1.setName("Urea");
    System.out.println("Name:" +f1.getName());
    f1.setType("Nitrogen");
    System.out.println("Type:" +f1.getType());
    f1.setPrice(300);
    System.out.println("Price:" +f1.getPrice());
    f1.setBrand("IFFCO");
    System.out.println("Brand:" +f1.getBrand());
    f1.setQuantity(50);
    System.out.println("Quantity(kg):" +f1.getQuantity());
    f1.setUsage("Crop Growth");
    System.out.println("Usage:" +f1.getUsage());

    System.out.println();
    Fertilizer f2 = new Fertilizer();
    f2.setFertilizerId(2);
    System.out.println("Fertilizer Id:" +f2.getFertilizerId());
    f2.setName("DAP");
    System.out.println("Name:" +f2.getName());
    f2.setType("Phosphate");
    System.out.println("Type:" +f2.getType());
    f2.setPrice(1200);
    System.out.println("Price:" +f2.getPrice());
    f2.setBrand("NFL");
    System.out.println("Brand:" +f2.getBrand());
    f2.setQuantity(50);
    System.out.println("Quantity(kg):" +f2.getQuantity());
    f2.setUsage("Root Development");
    System.out.println("Usage:" +f2.getUsage());
	
	System.out.println();
    Fertilizer f3 = new Fertilizer();
    f3.setFertilizerId(3);
    System.out.println("Fertilizer Id:" +f3.getFertilizerId());
    f3.setName("NPK");
    System.out.println("Name:" +f3.getName());
    f3.setType("Mixed");
    System.out.println("Type:" +f3.getType());
    f3.setPrice(900);
    System.out.println("Price:" +f3.getPrice());
    f3.setBrand("Coromandel");
    System.out.println("Brand:" +f3.getBrand());
    f3.setQuantity(50);
    System.out.println("Quantity(kg):" +f3.getQuantity());
    f3.setUsage("Balanced Nutrition");
    System.out.println("Usage:" +f3.getUsage());

    System.out.println();
    Fertilizer f4 = new Fertilizer();
    f4.setFertilizerId(4);
    System.out.println("Fertilizer Id:" +f4.getFertilizerId());
    f4.setName("Potash");
    System.out.println("Name:" +f4.getName());
    f4.setType("Potassium");
    System.out.println("Type:" +f4.getType());
    f4.setPrice(800);
    System.out.println("Price:" +f4.getPrice());
    f4.setBrand("IFFCO");
    System.out.println("Brand:" +f4.getBrand());
    f4.setQuantity(50);
    System.out.println("Quantity(kg):" +f4.getQuantity());
    f4.setUsage("Fruit Quality");
    System.out.println("Usage:" +f4.getUsage());

    System.out.println();
    Fertilizer f5 = new Fertilizer();
    f5.setFertilizerId(5);
    System.out.println("Fertilizer Id:" +f5.getFertilizerId());
    f5.setName("Ammonium Sulphate");
    System.out.println("Name:" +f5.getName());
    f5.setType("Nitrogen");
    System.out.println("Type:" +f5.getType());
    f5.setPrice(700);
    System.out.println("Price:" +f5.getPrice());
    f5.setBrand("NFL");
    System.out.println("Brand:" +f5.getBrand());
    f5.setQuantity(45);
    System.out.println("Quantity(kg):" +f5.getQuantity());
    f5.setUsage("Soil Fertility");
    System.out.println("Usage:" +f5.getUsage());

    System.out.println();
    Fertilizer f6 = new Fertilizer();
    f6.setFertilizerId(6);
    System.out.println("Fertilizer Id:" +f6.getFertilizerId());
    f6.setName("Zinc Sulphate");
    System.out.println("Name:" +f6.getName());
    f6.setType("Micronutrient");
    System.out.println("Type:" +f6.getType());
    f6.setPrice(500);
    System.out.println("Price:" +f6.getPrice());
    f6.setBrand("Tata Chemicals");
    System.out.println("Brand:" +f6.getBrand());
    f6.setQuantity(25);
    System.out.println("Quantity(kg):" +f6.getQuantity());
    f6.setUsage("Plant Growth");
    System.out.println("Usage:" +f6.getUsage());

    System.out.println();
    Fertilizer f7 = new Fertilizer();
    f7.setFertilizerId(7);
    System.out.println("Fertilizer Id:" +f7.getFertilizerId());
    f7.setName("Super Phosphate");
    System.out.println("Name:" +f7.getName());
    f7.setType("Phosphate");
    System.out.println("Type:" +f7.getType());
    f7.setPrice(850);
    System.out.println("Price:" +f7.getPrice());
    f7.setBrand("Coromandel");
    System.out.println("Brand:" +f7.getBrand());
    f7.setQuantity(50);
    System.out.println("Quantity(kg):" +f7.getQuantity());
    f7.setUsage("Root Strength");
    System.out.println("Usage:" +f7.getUsage());

    System.out.println();
    Fertilizer f8 = new Fertilizer();
    f8.setFertilizerId(8);
    System.out.println("Fertilizer Id:" +f8.getFertilizerId());
    f8.setName("Bio Fertilizer");
    System.out.println("Name:" +f8.getName());
    f8.setType("Organic");
    System.out.println("Type:" +f8.getType());
    f8.setPrice(600);
    System.out.println("Price:" +f8.getPrice());
    f8.setBrand("IFFCO");
    System.out.println("Brand:" +f8.getBrand());
    f8.setQuantity(20);
    System.out.println("Quantity(kg):" +f8.getQuantity());
    f8.setUsage("Eco Friendly Growth");
    System.out.println("Usage:" +f8.getUsage());

    System.out.println();
    Fertilizer f9 = new Fertilizer();
    f9.setFertilizerId(9);
    System.out.println("Fertilizer Id:" +f9.getFertilizerId());
    f9.setName("Calcium Nitrate");
    System.out.println("Name:" +f9.getName());
    f9.setType("Nitrogen");
    System.out.println("Type:" +f9.getType());
    f9.setPrice(950);
    System.out.println("Price:" +f9.getPrice());
    f9.setBrand("Tata Chemicals");
    System.out.println("Brand:" +f9.getBrand());
    f9.setQuantity(50);
    System.out.println("Quantity(kg):" +f9.getQuantity());
    f9.setUsage("Leaf Growth");
    System.out.println("Usage:" +f9.getUsage());

    System.out.println();
    Fertilizer f10 = new Fertilizer();
    f10.setFertilizerId(10);
    System.out.println("Fertilizer Id:" +f10.getFertilizerId());
    f10.setName("DAP Plus");
    System.out.println("Name:" +f10.getName());
    f10.setType("Phosphate");
    System.out.println("Type:" +f10.getType());
    f10.setPrice(1300);
    System.out.println("Price:" +f10.getPrice());
    f10.setBrand("NFL");
    System.out.println("Brand:" +f10.getBrand());
    f10.setQuantity(50);
    System.out.println("Quantity(kg):" +f10.getQuantity());
    f10.setUsage("Crop Yield");
    System.out.println("Usage:" +f10.getUsage());

 }
}