class IndianArmyExecutor {
 public static void main(String[] args){
    System.out.println();
    IndianArmy s1 = new IndianArmy();
    s1.setSoldierId(1);
    System.out.println("Soldier Id:" +s1.getSoldierId());
    s1.setName("Ravi");
    System.out.println("Name:" +s1.getName());
    s1.setRank("Captain");
    System.out.println("Rank:" +s1.getRank());
    s1.setRegiment("Infantry");
    System.out.println("Regiment:" +s1.getRegiment());
    s1.setAge(35);
    System.out.println("Age:" +s1.getAge());
    s1.setLocation("Kashmir");
    System.out.println("Location:" +s1.getLocation());
    s1.setOnDuty(true);
    System.out.println("On Duty:" +s1.getOnDuty());

    System.out.println();
    IndianArmy s2 = new IndianArmy();
    s2.setSoldierId(2);
    System.out.println("Soldier Id:" +s2.getSoldierId());
    s2.setName("Arjun");
    System.out.println("Name:" +s2.getName());
    s2.setRank("Lieutenant");
    System.out.println("Rank:" +s2.getRank());
    s2.setRegiment("Artillery");
    System.out.println("Regiment:" +s2.getRegiment());
    s2.setAge(28);
    System.out.println("Age:" +s2.getAge());
    s2.setLocation("Rajasthan");
    System.out.println("Location:" +s2.getLocation());
    s2.setOnDuty(true);
    System.out.println("On Duty:" +s2.getOnDuty());
	
	System.out.println();
    IndianArmy s3 = new IndianArmy();
    s3.setSoldierId(3);
    System.out.println("Soldier Id:" +s3.getSoldierId());
    s3.setName("Kiran");
    System.out.println("Name:" +s3.getName());
    s3.setRank("Major");
    System.out.println("Rank:" +s3.getRank());
    s3.setRegiment("Infantry");
    System.out.println("Regiment:" +s3.getRegiment());
    s3.setAge(40);
    System.out.println("Age:" +s3.getAge());
    s3.setLocation("Punjab");
    System.out.println("Location:" +s3.getLocation());
    s3.setOnDuty(true);
    System.out.println("On Duty:" +s3.getOnDuty());

    System.out.println();
    IndianArmy s4 = new IndianArmy();
    s4.setSoldierId(4);
    System.out.println("Soldier Id:" +s4.getSoldierId());
    s4.setName("Vijay");
    System.out.println("Name:" +s4.getName());
    s4.setRank("Colonel");
    System.out.println("Rank:" +s4.getRank());
    s4.setRegiment("Armoured");
    System.out.println("Regiment:" +s4.getRegiment());
    s4.setAge(45);
    System.out.println("Age:" +s4.getAge());
    s4.setLocation("Delhi");
    System.out.println("Location:" +s4.getLocation());
    s4.setOnDuty(false);
    System.out.println("On Duty:" +s4.getOnDuty());

    System.out.println();
    IndianArmy s5 = new IndianArmy();
    s5.setSoldierId(5);
    System.out.println("Soldier Id:" +s5.getSoldierId());
    s5.setName("Rahul");
    System.out.println("Name:" +s5.getName());
    s5.setRank("Lieutenant");
    System.out.println("Rank:" +s5.getRank());
    s5.setRegiment("Artillery");
    System.out.println("Regiment:" +s5.getRegiment());
    s5.setAge(27);
    System.out.println("Age:" +s5.getAge());
    s5.setLocation("Assam");
    System.out.println("Location:" +s5.getLocation());
    s5.setOnDuty(true);
    System.out.println("On Duty:" +s5.getOnDuty());

    System.out.println();
    IndianArmy s6 = new IndianArmy();
    s6.setSoldierId(6);
    System.out.println("Soldier Id:" +s6.getSoldierId());
    s6.setName("Manoj");
    System.out.println("Name:" +s6.getName());
    s6.setRank("Captain");
    System.out.println("Rank:" +s6.getRank());
    s6.setRegiment("Signals");
    System.out.println("Regiment:" +s6.getRegiment());
    s6.setAge(33);
    System.out.println("Age:" +s6.getAge());
    s6.setLocation("Jammu");
    System.out.println("Location:" +s6.getLocation());
    s6.setOnDuty(true);
    System.out.println("On Duty:" +s6.getOnDuty());

    System.out.println();
    IndianArmy s7 = new IndianArmy();
    s7.setSoldierId(7);
    System.out.println("Soldier Id:" +s7.getSoldierId());
    s7.setName("Ajay");
    System.out.println("Name:" +s7.getName());
    s7.setRank("Sepoy");
    System.out.println("Rank:" +s7.getRank());
    s7.setRegiment("Infantry");
    System.out.println("Regiment:" +s7.getRegiment());
    s7.setAge(24);
    System.out.println("Age:" +s7.getAge());
    s7.setLocation("Siachen");
    System.out.println("Location:" +s7.getLocation());
    s7.setOnDuty(true);
    System.out.println("On Duty:" +s7.getOnDuty());

    System.out.println();
    IndianArmy s8 = new IndianArmy();
    s8.setSoldierId(8);
    System.out.println("Soldier Id:" +s8.getSoldierId());
    s8.setName("Ramesh");
    System.out.println("Name:" +s8.getName());
    s8.setRank("General");
    System.out.println("Rank:" +s8.getRank());
    s8.setRegiment("Headquarters");
    System.out.println("Regiment:" +s8.getRegiment());
    s8.setAge(55);
    System.out.println("Age:" +s8.getAge());
    s8.setLocation("Delhi");
    System.out.println("Location:" +s8.getLocation());
    s8.setOnDuty(false);
    System.out.println("On Duty:" +s8.getOnDuty());

    System.out.println();
    IndianArmy s9 = new IndianArmy();
    s9.setSoldierId(9);
    System.out.println("Soldier Id:" +s9.getSoldierId());
    s9.setName("Deepak");
    System.out.println("Name:" +s9.getName());
    s9.setRank("Major");
    System.out.println("Rank:" +s9.getRank());
    s9.setRegiment("Engineers");
    System.out.println("Regiment:" +s9.getRegiment());
    s9.setAge(38);
    System.out.println("Age:" +s9.getAge());
    s9.setLocation("Ladakh");
    System.out.println("Location:" +s9.getLocation());
    s9.setOnDuty(true);
    System.out.println("On Duty:" +s9.getOnDuty());

    System.out.println();
    IndianArmy s10 = new IndianArmy();
    s10.setSoldierId(10);
    System.out.println("Soldier Id:" +s10.getSoldierId());
    s10.setName("Sandeep");
    System.out.println("Name:" +s10.getName());
    s10.setRank("Captain");
    System.out.println("Rank:" +s10.getRank());
    s10.setRegiment("Artillery");
    System.out.println("Regiment:" +s10.getRegiment());
    s10.setAge(32);
    System.out.println("Age:" +s10.getAge());
    s10.setLocation("Kargil");
    System.out.println("Location:" +s10.getLocation());
    s10.setOnDuty(true);
    System.out.println("On Duty:" +s10.getOnDuty());

 }
}