class MarvelExecutor {
 public static void main(String[] args){
    System.out.println();
    Marvel m1 = new Marvel();
    m1.setHeroId(1);
    System.out.println("Hero Id:" +m1.getHeroId());
    m1.setName("Iron Man");
    System.out.println("Name:" +m1.getName());
    m1.setSuperPower("Genius Intelligence");
    System.out.println("Power:" +m1.getSuperPower());
    m1.setTeam("Avengers");
    System.out.println("Team:" +m1.getTeam());
    m1.setWeapon("Suit");
    System.out.println("Weapon:" +m1.getWeapon());
    m1.setPlanet("Earth");
    System.out.println("Planet:" +m1.getPlanet());
    m1.setIsAvenger(true);
    System.out.println("Avenger:" +m1.getIsAvenger());

    System.out.println();
    Marvel m2 = new Marvel();
    m2.setHeroId(2);
    System.out.println("Hero Id:" +m2.getHeroId());
    m2.setName("Thor");
    System.out.println("Name:" +m2.getName());
    m2.setSuperPower("God of Thunder");
    System.out.println("Power:" +m2.getSuperPower());
    m2.setTeam("Avengers");
    System.out.println("Team:" +m2.getTeam());
    m2.setWeapon("Mjolnir");
    System.out.println("Weapon:" +m2.getWeapon());
    m2.setPlanet("Asgard");
    System.out.println("Planet:" +m2.getPlanet());
    m2.setIsAvenger(true);
    System.out.println("Avenger:" +m2.getIsAvenger());
	
	System.out.println();
    Marvel m3 = new Marvel();
    m3.setHeroId(3);
    System.out.println("Hero Id:" +m3.getHeroId());
    m3.setName("Captain America");
    System.out.println("Name:" +m3.getName());
    m3.setSuperPower("Super Soldier");
    System.out.println("Power:" +m3.getSuperPower());
    m3.setTeam("Avengers");
    System.out.println("Team:" +m3.getTeam());
    m3.setWeapon("Shield");
    System.out.println("Weapon:" +m3.getWeapon());
    m3.setPlanet("Earth");
    System.out.println("Planet:" +m3.getPlanet());
    m3.setIsAvenger(true);
    System.out.println("Avenger:" +m3.getIsAvenger());

    System.out.println();
    Marvel m4 = new Marvel();
    m4.setHeroId(4);
    System.out.println("Hero Id:" +m4.getHeroId());
    m4.setName("Hulk");
    System.out.println("Name:" +m4.getName());
    m4.setSuperPower("Super Strength");
    System.out.println("Power:" +m4.getSuperPower());
    m4.setTeam("Avengers");
    System.out.println("Team:" +m4.getTeam());
    m4.setWeapon("Fists");
    System.out.println("Weapon:" +m4.getWeapon());
    m4.setPlanet("Earth");
    System.out.println("Planet:" +m4.getPlanet());
    m4.setIsAvenger(true);
    System.out.println("Avenger:" +m4.getIsAvenger());

    System.out.println();
    Marvel m5 = new Marvel();
    m5.setHeroId(5);
    System.out.println("Hero Id:" +m5.getHeroId());
    m5.setName("Black Widow");
    System.out.println("Name:" +m5.getName());
    m5.setSuperPower("Espionage");
    System.out.println("Power:" +m5.getSuperPower());
    m5.setTeam("Avengers");
    System.out.println("Team:" +m5.getTeam());
    m5.setWeapon("Guns");
    System.out.println("Weapon:" +m5.getWeapon());
    m5.setPlanet("Earth");
    System.out.println("Planet:" +m5.getPlanet());
    m5.setIsAvenger(true);
    System.out.println("Avenger:" +m5.getIsAvenger());

    System.out.println();
    Marvel m6 = new Marvel();
    m6.setHeroId(6);
    System.out.println("Hero Id:" +m6.getHeroId());
    m6.setName("Hawkeye");
    System.out.println("Name:" +m6.getName());
    m6.setSuperPower("Sharp Shooter");
    System.out.println("Power:" +m6.getSuperPower());
    m6.setTeam("Avengers");
    System.out.println("Team:" +m6.getTeam());
    m6.setWeapon("Bow and Arrow");
    System.out.println("Weapon:" +m6.getWeapon());
    m6.setPlanet("Earth");
    System.out.println("Planet:" +m6.getPlanet());
    m6.setIsAvenger(true);
    System.out.println("Avenger:" +m6.getIsAvenger());

    System.out.println();
    Marvel m7 = new Marvel();
    m7.setHeroId(7);
    System.out.println("Hero Id:" +m7.getHeroId());
    m7.setName("Spider-Man");
    System.out.println("Name:" +m7.getName());
    m7.setSuperPower("Spider Sense");
    System.out.println("Power:" +m7.getSuperPower());
    m7.setTeam("Avengers");
    System.out.println("Team:" +m7.getTeam());
    m7.setWeapon("Web Shooter");
    System.out.println("Weapon:" +m7.getWeapon());
    m7.setPlanet("Earth");
    System.out.println("Planet:" +m7.getPlanet());
    m7.setIsAvenger(true);
    System.out.println("Avenger:" +m7.getIsAvenger());

    System.out.println();
    Marvel m8 = new Marvel();
    m8.setHeroId(8);
    System.out.println("Hero Id:" +m8.getHeroId());
    m8.setName("Doctor Strange");
    System.out.println("Name:" +m8.getName());
    m8.setSuperPower("Magic");
    System.out.println("Power:" +m8.getSuperPower());
    m8.setTeam("Avengers");
    System.out.println("Team:" +m8.getTeam());
    m8.setWeapon("Time Stone");
    System.out.println("Weapon:" +m8.getWeapon());
    m8.setPlanet("Earth");
    System.out.println("Planet:" +m8.getPlanet());
    m8.setIsAvenger(true);
    System.out.println("Avenger:" +m8.getIsAvenger());

    System.out.println();
    Marvel m9 = new Marvel();
    m9.setHeroId(9);
    System.out.println("Hero Id:" +m9.getHeroId());
    m9.setName("Black Panther");
    System.out.println("Name:" +m9.getName());
    m9.setSuperPower("Enhanced Strength");
    System.out.println("Power:" +m9.getSuperPower());
    m9.setTeam("Avengers");
    System.out.println("Team:" +m9.getTeam());
    m9.setWeapon("Vibranium Suit");
    System.out.println("Weapon:" +m9.getWeapon());
    m9.setPlanet("Wakanda");
    System.out.println("Planet:" +m9.getPlanet());
    m9.setIsAvenger(true);
    System.out.println("Avenger:" +m9.getIsAvenger());

    System.out.println();
    Marvel m10 = new Marvel();
    m10.setHeroId(10);
    System.out.println("Hero Id:" +m10.getHeroId());
    m10.setName("Captain Marvel");
    System.out.println("Name:" +m10.getName());
    m10.setSuperPower("Energy Power");
    System.out.println("Power:" +m10.getSuperPower());
    m10.setTeam("Avengers");
    System.out.println("Team:" +m10.getTeam());
    m10.setWeapon("Energy Blast");
    System.out.println("Weapon:" +m10.getWeapon());
    m10.setPlanet("Earth");
    System.out.println("Planet:" +m10.getPlanet());
    m10.setIsAvenger(true);
    System.out.println("Avenger:" +m10.getIsAvenger());

 }
}