class MedicineExecutor {
 public static void main(String[] args){
    System.out.println();
    Medicine m1 = new Medicine();
    m1.setMedicineId(1);
    System.out.println("Medicine Id:" +m1.getMedicineId());
    m1.setName("Paracetamol");
    System.out.println("Name:" +m1.getName());
    m1.setType("Tablet");
    System.out.println("Type:" +m1.getType());
    m1.setPrice(50);
    System.out.println("Price:" +m1.getPrice());
    m1.setManufacturer("Cipla");
    System.out.println("Manufacturer:" +m1.getManufacturer());
    m1.setExpiryDate("12-2026");
    System.out.println("Expiry:" +m1.getExpiryDate());
    m1.setUsage("Fever");
    System.out.println("Usage:" +m1.getUsage());

    System.out.println();
    Medicine m2 = new Medicine();
    m2.setMedicineId(2);
    System.out.println("Medicine Id:" +m2.getMedicineId());
    m2.setName("Amoxicillin");
    System.out.println("Name:" +m2.getName());
    m2.setType("Capsule");
    System.out.println("Type:" +m2.getType());
    m2.setPrice(120);
    System.out.println("Price:" +m2.getPrice());
    m2.setManufacturer("Sun Pharma");
    System.out.println("Manufacturer:" +m2.getManufacturer());
    m2.setExpiryDate("10-2026");
    System.out.println("Expiry:" +m2.getExpiryDate());
    m2.setUsage("Infection");
    System.out.println("Usage:" +m2.getUsage());
	
	System.out.println();
    Medicine m3 = new Medicine();
    m3.setMedicineId(3);
    System.out.println("Medicine Id:" +m3.getMedicineId());
    m3.setName("Ibuprofen");
    System.out.println("Name:" +m3.getName());
    m3.setType("Tablet");
    System.out.println("Type:" +m3.getType());
    m3.setPrice(80);
    System.out.println("Price:" +m3.getPrice());
    m3.setManufacturer("Dr. Reddy");
    System.out.println("Manufacturer:" +m3.getManufacturer());
    m3.setExpiryDate("11-2026");
    System.out.println("Expiry:" +m3.getExpiryDate());
    m3.setUsage("Pain Relief");
    System.out.println("Usage:" +m3.getUsage());

    System.out.println();
    Medicine m4 = new Medicine();
    m4.setMedicineId(4);
    System.out.println("Medicine Id:" +m4.getMedicineId());
    m4.setName("Cetirizine");
    System.out.println("Name:" +m4.getName());
    m4.setType("Tablet");
    System.out.println("Type:" +m4.getType());
    m4.setPrice(60);
    System.out.println("Price:" +m4.getPrice());
    m4.setManufacturer("Cipla");
    System.out.println("Manufacturer:" +m4.getManufacturer());
    m4.setExpiryDate("09-2026");
    System.out.println("Expiry:" +m4.getExpiryDate());
    m4.setUsage("Allergy");
    System.out.println("Usage:" +m4.getUsage());

    System.out.println();
    Medicine m5 = new Medicine();
    m5.setMedicineId(5);
    System.out.println("Medicine Id:" +m5.getMedicineId());
    m5.setName("Azithromycin");
    System.out.println("Name:" +m5.getName());
    m5.setType("Tablet");
    System.out.println("Type:" +m5.getType());
    m5.setPrice(150);
    System.out.println("Price:" +m5.getPrice());
    m5.setManufacturer("Sun Pharma");
    System.out.println("Manufacturer:" +m5.getManufacturer());
    m5.setExpiryDate("08-2026");
    System.out.println("Expiry:" +m5.getExpiryDate());
    m5.setUsage("Infection");
    System.out.println("Usage:" +m5.getUsage());

    System.out.println();
    Medicine m6 = new Medicine();
    m6.setMedicineId(6);
    System.out.println("Medicine Id:" +m6.getMedicineId());
    m6.setName("Metformin");
    System.out.println("Name:" +m6.getName());
    m6.setType("Tablet");
    System.out.println("Type:" +m6.getType());
    m6.setPrice(90);
    System.out.println("Price:" +m6.getPrice());
    m6.setManufacturer("Glenmark");
    System.out.println("Manufacturer:" +m6.getManufacturer());
    m6.setExpiryDate("07-2026");
    System.out.println("Expiry:" +m6.getExpiryDate());
    m6.setUsage("Diabetes");
    System.out.println("Usage:" +m6.getUsage());

    System.out.println();
    Medicine m7 = new Medicine();
    m7.setMedicineId(7);
    System.out.println("Medicine Id:" +m7.getMedicineId());
    m7.setName("Aspirin");
    System.out.println("Name:" +m7.getName());
    m7.setType("Tablet");
    System.out.println("Type:" +m7.getType());
    m7.setPrice(40);
    System.out.println("Price:" +m7.getPrice());
    m7.setManufacturer("Bayer");
    System.out.println("Manufacturer:" +m7.getManufacturer());
    m7.setExpiryDate("06-2026");
    System.out.println("Expiry:" +m7.getExpiryDate());
    m7.setUsage("Pain Relief");
    System.out.println("Usage:" +m7.getUsage());

    System.out.println();
    Medicine m8 = new Medicine();
    m8.setMedicineId(8);
    System.out.println("Medicine Id:" +m8.getMedicineId());
    m8.setName("Dolo 650");
    System.out.println("Name:" +m8.getName());
    m8.setType("Tablet");
    System.out.println("Type:" +m8.getType());
    m8.setPrice(30);
    System.out.println("Price:" +m8.getPrice());
    m8.setManufacturer("Micro Labs");
    System.out.println("Manufacturer:" +m8.getManufacturer());
    m8.setExpiryDate("05-2026");
    System.out.println("Expiry:" +m8.getExpiryDate());
    m8.setUsage("Fever");
    System.out.println("Usage:" +m8.getUsage());

    System.out.println();
    Medicine m9 = new Medicine();
    m9.setMedicineId(9);
    System.out.println("Medicine Id:" +m9.getMedicineId());
    m9.setName("ORS");
    System.out.println("Name:" +m9.getName());
    m9.setType("Powder");
    System.out.println("Type:" +m9.getType());
    m9.setPrice(20);
    System.out.println("Price:" +m9.getPrice());
    m9.setManufacturer("WHO");
    System.out.println("Manufacturer:" +m9.getManufacturer());
    m9.setExpiryDate("12-2026");
    System.out.println("Expiry:" +m9.getExpiryDate());
    m9.setUsage("Dehydration");
    System.out.println("Usage:" +m9.getUsage());

    System.out.println();
    Medicine m10 = new Medicine();
    m10.setMedicineId(10);
    System.out.println("Medicine Id:" +m10.getMedicineId());
    m10.setName("Insulin");
    System.out.println("Name:" +m10.getName());
    m10.setType("Injection");
    System.out.println("Type:" +m10.getType());
    m10.setPrice(500);
    System.out.println("Price:" +m10.getPrice());
    m10.setManufacturer("Novo Nordisk");
    System.out.println("Manufacturer:" +m10.getManufacturer());
    m10.setExpiryDate("04-2026");
    System.out.println("Expiry:" +m10.getExpiryDate());
    m10.setUsage("Diabetes");
    System.out.println("Usage:" +m10.getUsage());

 }
}