class NasaExecutor {
 public static void main(String[] args){
    System.out.println();
    Nasa n1 = new Nasa();
    n1.setMissionId(1);
    System.out.println("Mission Id:" +n1.getMissionId());
    n1.setMissionName("Apollo 11");
    System.out.println("Mission:" +n1.getMissionName());
    n1.setSpacecraft("Saturn V");
    System.out.println("Spacecraft:" +n1.getSpacecraft());
    n1.setLaunchDate("16-07-1969");
    System.out.println("Launch Date:" +n1.getLaunchDate());
    n1.setDestination("Moon");
    System.out.println("Destination:" +n1.getDestination());
    n1.setCrewCount(3);
    System.out.println("Crew:" +n1.getCrewCount());
    n1.setStatus("Completed");
    System.out.println("Status:" +n1.getStatus());

    System.out.println();
    Nasa n2 = new Nasa();
    n2.setMissionId(2);
    System.out.println("Mission Id:" +n2.getMissionId());
    n2.setMissionName("Mars Rover");
    System.out.println("Mission:" +n2.getMissionName());
    n2.setSpacecraft("Perseverance");
    System.out.println("Spacecraft:" +n2.getSpacecraft());
    n2.setLaunchDate("30-07-2020");
    System.out.println("Launch Date:" +n2.getLaunchDate());
    n2.setDestination("Mars");
    System.out.println("Destination:" +n2.getDestination());
    n2.setCrewCount(0);
    System.out.println("Crew:" +n2.getCrewCount());
    n2.setStatus("Active");
    System.out.println("Status:" +n2.getStatus());
	
	System.out.println();
    Nasa n3 = new Nasa();
    n3.setMissionId(3);
    System.out.println("Mission Id:" +n3.getMissionId());
    n3.setMissionName("Voyager 1");
    System.out.println("Mission:" +n3.getMissionName());
    n3.setSpacecraft("Voyager");
    System.out.println("Spacecraft:" +n3.getSpacecraft());
    n3.setLaunchDate("05-09-1977");
    System.out.println("Launch Date:" +n3.getLaunchDate());
    n3.setDestination("Interstellar Space");
    System.out.println("Destination:" +n3.getDestination());
    n3.setCrewCount(0);
    System.out.println("Crew:" +n3.getCrewCount());
    n3.setStatus("Active");
    System.out.println("Status:" +n3.getStatus());

    System.out.println();
    Nasa n4 = new Nasa();
    n4.setMissionId(4);
    System.out.println("Mission Id:" +n4.getMissionId());
    n4.setMissionName("Chandrayaan-1");
    System.out.println("Mission:" +n4.getMissionName());
    n4.setSpacecraft("PSLV");
    System.out.println("Spacecraft:" +n4.getSpacecraft());
    n4.setLaunchDate("22-10-2008");
    System.out.println("Launch Date:" +n4.getLaunchDate());
    n4.setDestination("Moon");
    System.out.println("Destination:" +n4.getDestination());
    n4.setCrewCount(0);
    System.out.println("Crew:" +n4.getCrewCount());
    n4.setStatus("Completed");
    System.out.println("Status:" +n4.getStatus());

    System.out.println();
    Nasa n5 = new Nasa();
    n5.setMissionId(5);
    System.out.println("Mission Id:" +n5.getMissionId());
    n5.setMissionName("James Webb");
    System.out.println("Mission:" +n5.getMissionName());
    n5.setSpacecraft("JWST");
    System.out.println("Spacecraft:" +n5.getSpacecraft());
    n5.setLaunchDate("25-12-2021");
    System.out.println("Launch Date:" +n5.getLaunchDate());
    n5.setDestination("Space Telescope Orbit");
    System.out.println("Destination:" +n5.getDestination());
    n5.setCrewCount(0);
    System.out.println("Crew:" +n5.getCrewCount());
    n5.setStatus("Active");
    System.out.println("Status:" +n5.getStatus());

    System.out.println();
    Nasa n6 = new Nasa();
    n6.setMissionId(6);
    System.out.println("Mission Id:" +n6.getMissionId());
    n6.setMissionName("Artemis I");
    System.out.println("Mission:" +n6.getMissionName());
    n6.setSpacecraft("Orion");
    System.out.println("Spacecraft:" +n6.getSpacecraft());
    n6.setLaunchDate("16-11-2022");
    System.out.println("Launch Date:" +n6.getLaunchDate());
    n6.setDestination("Moon Orbit");
    System.out.println("Destination:" +n6.getDestination());
    n6.setCrewCount(0);
    System.out.println("Crew:" +n6.getCrewCount());
    n6.setStatus("Completed");
    System.out.println("Status:" +n6.getStatus());

    System.out.println();
    Nasa n7 = new Nasa();
    n7.setMissionId(7);
    System.out.println("Mission Id:" +n7.getMissionId());
    n7.setMissionName("Hubble Telescope");
    System.out.println("Mission:" +n7.getMissionName());
    n7.setSpacecraft("HST");
    System.out.println("Spacecraft:" +n7.getSpacecraft());
    n7.setLaunchDate("24-04-1990");
    System.out.println("Launch Date:" +n7.getLaunchDate());
    n7.setDestination("Low Earth Orbit");
    System.out.println("Destination:" +n7.getDestination());
    n7.setCrewCount(0);
    System.out.println("Crew:" +n7.getCrewCount());
    n7.setStatus("Active");
    System.out.println("Status:" +n7.getStatus());

    System.out.println();
    Nasa n8 = new Nasa();
    n8.setMissionId(8);
    System.out.println("Mission Id:" +n8.getMissionId());
    n8.setMissionName("Sputnik");
    System.out.println("Mission:" +n8.getMissionName());
    n8.setSpacecraft("Sputnik-1");
    System.out.println("Spacecraft:" +n8.getSpacecraft());
    n8.setLaunchDate("04-10-1957");
    System.out.println("Launch Date:" +n8.getLaunchDate());
    n8.setDestination("Earth Orbit");
    System.out.println("Destination:" +n8.getDestination());
    n8.setCrewCount(0);
    System.out.println("Crew:" +n8.getCrewCount());
    n8.setStatus("Completed");
    System.out.println("Status:" +n8.getStatus());

    System.out.println();
    Nasa n9 = new Nasa();
    n9.setMissionId(9);
    System.out.println("Mission Id:" +n9.getMissionId());
    n9.setMissionName("Mars Pathfinder");
    System.out.println("Mission:" +n9.getMissionName());
    n9.setSpacecraft("Sojourner");
    System.out.println("Spacecraft:" +n9.getSpacecraft());
    n9.setLaunchDate("04-12-1996");
    System.out.println("Launch Date:" +n9.getLaunchDate());
    n9.setDestination("Mars");
    System.out.println("Destination:" +n9.getDestination());
    n9.setCrewCount(0);
    System.out.println("Crew:" +n9.getCrewCount());
    n9.setStatus("Completed");
    System.out.println("Status:" +n9.getStatus());

    System.out.println();
    Nasa n10 = new Nasa();
    n10.setMissionId(10);
    System.out.println("Mission Id:" +n10.getMissionId());
    n10.setMissionName("Apollo 13");
    System.out.println("Mission:" +n10.getMissionName());
    n10.setSpacecraft("Saturn V");
    System.out.println("Spacecraft:" +n10.getSpacecraft());
    n10.setLaunchDate("11-04-1970");
    System.out.println("Launch Date:" +n10.getLaunchDate());
    n10.setDestination("Moon");
    System.out.println("Destination:" +n10.getDestination());
    n10.setCrewCount(3);
    System.out.println("Crew:" +n10.getCrewCount());
    n10.setStatus("Failed");
    System.out.println("Status:" +n10.getStatus());

 }
}