class NutritionTableExecutor {
 public static void main(String[] args){
    NutritionTable n1 = new NutritionTable();
    n1.setItemId(1);
    System.out.println("Item Id:" +n1.getItemId());
    n1.setFoodName("Rice");
    System.out.println("Food:" +n1.getFoodName());
    n1.setCalories(130);
    System.out.println("Calories:" +n1.getCalories());
    n1.setProtein(2.5);
    System.out.println("Protein:" +n1.getProtein());
    n1.setFat(0.3);
    System.out.println("Fat:" +n1.getFat());
    n1.setCarbs(28);
    System.out.println("Carbs:" +n1.getCarbs());
    n1.setCategory("Grain");
    System.out.println("Category:" +n1.getCategory());

    System.out.println();
    NutritionTable n2 = new NutritionTable();
    n2.setItemId(2);
    System.out.println("Item Id:" +n2.getItemId());
    n2.setFoodName("Egg");
    System.out.println("Food:" +n2.getFoodName());
    n2.setCalories(155);
    System.out.println("Calories:" +n2.getCalories());
    n2.setProtein(13);
    System.out.println("Protein:" +n2.getProtein());
    n2.setFat(11);
    System.out.println("Fat:" +n2.getFat());
    n2.setCarbs(1.1);
    System.out.println("Carbs:" +n2.getCarbs());
    n2.setCategory("Protein");
    System.out.println("Category:" +n2.getCategory());
	
	System.out.println();
    NutritionTable n3 = new NutritionTable();
    n3.setItemId(3);
    System.out.println("Item Id:" +n3.getItemId());
    n3.setFoodName("Milk");
    System.out.println("Food:" +n3.getFoodName());
    n3.setCalories(42);
    System.out.println("Calories:" +n3.getCalories());
    n3.setProtein(3.4);
    System.out.println("Protein:" +n3.getProtein());
    n3.setFat(1.0);
    System.out.println("Fat:" +n3.getFat());
    n3.setCarbs(5.0);
    System.out.println("Carbs:" +n3.getCarbs());
    n3.setCategory("Dairy");
    System.out.println("Category:" +n3.getCategory());

    System.out.println();
    NutritionTable n4 = new NutritionTable();
    n4.setItemId(4);
    System.out.println("Item Id:" +n4.getItemId());
    n4.setFoodName("Chicken");
    System.out.println("Food:" +n4.getFoodName());
    n4.setCalories(239);
    System.out.println("Calories:" +n4.getCalories());
    n4.setProtein(27);
    System.out.println("Protein:" +n4.getProtein());
    n4.setFat(14);
    System.out.println("Fat:" +n4.getFat());
    n4.setCarbs(0);
    System.out.println("Carbs:" +n4.getCarbs());
    n4.setCategory("Meat");
    System.out.println("Category:" +n4.getCategory());

    System.out.println();
    NutritionTable n5 = new NutritionTable();
    n5.setItemId(5);
    System.out.println("Item Id:" +n5.getItemId());
    n5.setFoodName("Apple");
    System.out.println("Food:" +n5.getFoodName());
    n5.setCalories(52);
    System.out.println("Calories:" +n5.getCalories());
    n5.setProtein(0.3);
    System.out.println("Protein:" +n5.getProtein());
    n5.setFat(0.2);
    System.out.println("Fat:" +n5.getFat());
    n5.setCarbs(14);
    System.out.println("Carbs:" +n5.getCarbs());
    n5.setCategory("Fruit");
    System.out.println("Category:" +n5.getCategory());

    System.out.println();
    NutritionTable n6 = new NutritionTable();
    n6.setItemId(6);
    System.out.println("Item Id:" +n6.getItemId());
    n6.setFoodName("Banana");
    System.out.println("Food:" +n6.getFoodName());
    n6.setCalories(89);
    System.out.println("Calories:" +n6.getCalories());
    n6.setProtein(1.1);
    System.out.println("Protein:" +n6.getProtein());
    n6.setFat(0.3);
    System.out.println("Fat:" +n6.getFat());
    n6.setCarbs(23);
    System.out.println("Carbs:" +n6.getCarbs());
    n6.setCategory("Fruit");
    System.out.println("Category:" +n6.getCategory());

    System.out.println();
    NutritionTable n7 = new NutritionTable();
    n7.setItemId(7);
    System.out.println("Item Id:" +n7.getItemId());
    n7.setFoodName("Bread");
    System.out.println("Food:" +n7.getFoodName());
    n7.setCalories(265);
    System.out.println("Calories:" +n7.getCalories());
    n7.setProtein(9);
    System.out.println("Protein:" +n7.getProtein());
    n7.setFat(3.2);
    System.out.println("Fat:" +n7.getFat());
    n7.setCarbs(49);
    System.out.println("Carbs:" +n7.getCarbs());
    n7.setCategory("Grain");
    System.out.println("Category:" +n7.getCategory());

    System.out.println();
    NutritionTable n8 = new NutritionTable();
    n8.setItemId(8);
    System.out.println("Item Id:" +n8.getItemId());
    n8.setFoodName("Fish");
    System.out.println("Food:" +n8.getFoodName());
    n8.setCalories(206);
    System.out.println("Calories:" +n8.getCalories());
    n8.setProtein(22);
    System.out.println("Protein:" +n8.getProtein());
    n8.setFat(12);
    System.out.println("Fat:" +n8.getFat());
    n8.setCarbs(0);
    System.out.println("Carbs:" +n8.getCarbs());
    n8.setCategory("Meat");
    System.out.println("Category:" +n8.getCategory());

    System.out.println();
    NutritionTable n9 = new NutritionTable();
    n9.setItemId(9);
    System.out.println("Item Id:" +n9.getItemId());
    n9.setFoodName("Almonds");
    System.out.println("Food:" +n9.getFoodName());
    n9.setCalories(576);
    System.out.println("Calories:" +n9.getCalories());
    n9.setProtein(21);
    System.out.println("Protein:" +n9.getProtein());
    n9.setFat(49);
    System.out.println("Fat:" +n9.getFat());
    n9.setCarbs(22);
    System.out.println("Carbs:" +n9.getCarbs());
    n9.setCategory("Nuts");
    System.out.println("Category:" +n9.getCategory());

    System.out.println();
    NutritionTable n10 = new NutritionTable();
    n10.setItemId(10);
    System.out.println("Item Id:" +n10.getItemId());
    n10.setFoodName("Paneer");
    System.out.println("Food:" +n10.getFoodName());
    n10.setCalories(265);
    System.out.println("Calories:" +n10.getCalories());
    n10.setProtein(18);
    System.out.println("Protein:" +n10.getProtein());
    n10.setFat(20);
    System.out.println("Fat:" +n10.getFat());
    n10.setCarbs(1.2);
    System.out.println("Carbs:" +n10.getCarbs());
    n10.setCategory("Dairy");
    System.out.println("Category:" +n10.getCategory());
	
	    System.out.println();
    NutritionTable n11 = new NutritionTable();
    n11.setItemId(11);
    System.out.println("Item Id:" +n11.getItemId());
    n11.setFoodName("Dal");
    System.out.println("Food:" +n11.getFoodName());
    n11.setCalories(116);
    System.out.println("Calories:" +n11.getCalories());
    n11.setProtein(9);
    System.out.println("Protein:" +n11.getProtein());
    n11.setFat(0.4);
    System.out.println("Fat:" +n11.getFat());
    n11.setCarbs(20);
    System.out.println("Carbs:" +n11.getCarbs());
    n11.setCategory("Protein");
    System.out.println("Category:" +n11.getCategory());

    System.out.println();
    NutritionTable n12 = new NutritionTable();
    n12.setItemId(12);
    System.out.println("Item Id:" +n12.getItemId());
    n12.setFoodName("Chapati");
    System.out.println("Food:" +n12.getFoodName());
    n12.setCalories(120);
    System.out.println("Calories:" +n12.getCalories());
    n12.setProtein(3);
    System.out.println("Protein:" +n12.getProtein());
    n12.setFat(1);
    System.out.println("Fat:" +n12.getFat());
    n12.setCarbs(20);
    System.out.println("Carbs:" +n12.getCarbs());
    n12.setCategory("Grain");
    System.out.println("Category:" +n12.getCategory());

    System.out.println();
    NutritionTable n13 = new NutritionTable();
    n13.setItemId(13);
    System.out.println("Item Id:" +n13.getItemId());
    n13.setFoodName("Curd");
    System.out.println("Food:" +n13.getFoodName());
    n13.setCalories(98);
    System.out.println("Calories:" +n13.getCalories());
    n13.setProtein(11);
    System.out.println("Protein:" +n13.getProtein());
    n13.setFat(4);
    System.out.println("Fat:" +n13.getFat());
    n13.setCarbs(3.4);
    System.out.println("Carbs:" +n13.getCarbs());
    n13.setCategory("Dairy");
    System.out.println("Category:" +n13.getCategory());

    System.out.println();
    NutritionTable n14 = new NutritionTable();
    n14.setItemId(14);
    System.out.println("Item Id:" +n14.getItemId());
    n14.setFoodName("Mango");
    System.out.println("Food:" +n14.getFoodName());
    n14.setCalories(60);
    System.out.println("Calories:" +n14.getCalories());
    n14.setProtein(0.8);
    System.out.println("Protein:" +n14.getProtein());
    n14.setFat(0.4);
    System.out.println("Fat:" +n14.getFat());
    n14.setCarbs(15);
    System.out.println("Carbs:" +n14.getCarbs());
    n14.setCategory("Fruit");
    System.out.println("Category:" +n14.getCategory());

    System.out.println();
    NutritionTable n15 = new NutritionTable();
    n15.setItemId(15);
    System.out.println("Item Id:" +n15.getItemId());
    n15.setFoodName("Grapes");
    System.out.println("Food:" +n15.getFoodName());
    n15.setCalories(69);
    System.out.println("Calories:" +n15.getCalories());
    n15.setProtein(0.6);
    System.out.println("Protein:" +n15.getProtein());
    n15.setFat(0.2);
    System.out.println("Fat:" +n15.getFat());
    n15.setCarbs(18);
    System.out.println("Carbs:" +n15.getCarbs());
    n15.setCategory("Fruit");
    System.out.println("Category:" +n15.getCategory());

    System.out.println();
    NutritionTable n16 = new NutritionTable();
    n16.setItemId(16);
    System.out.println("Item Id:" +n16.getItemId());
    n16.setFoodName("Broccoli");
    System.out.println("Food:" +n16.getFoodName());
    n16.setCalories(55);
    System.out.println("Calories:" +n16.getCalories());
    n16.setProtein(3.7);
    System.out.println("Protein:" +n16.getProtein());
    n16.setFat(0.6);
    System.out.println("Fat:" +n16.getFat());
    n16.setCarbs(11);
    System.out.println("Carbs:" +n16.getCarbs());
    n16.setCategory("Vegetable");
    System.out.println("Category:" +n16.getCategory());

    System.out.println();
    NutritionTable n17 = new NutritionTable();
    n17.setItemId(17);
    System.out.println("Item Id:" +n17.getItemId());
    n17.setFoodName("Cabbage");
    System.out.println("Food:" +n17.getFoodName());
    n17.setCalories(25);
    System.out.println("Calories:" +n17.getCalories());
    n17.setProtein(1.3);
    System.out.println("Protein:" +n17.getProtein());
    n17.setFat(0.1);
    System.out.println("Fat:" +n17.getFat());
    n17.setCarbs(6);
    System.out.println("Carbs:" +n17.getCarbs());
    n17.setCategory("Vegetable");
    System.out.println("Category:" +n17.getCategory());

    System.out.println();
    NutritionTable n18 = new NutritionTable();
    n18.setItemId(18);
    System.out.println("Item Id:" +n18.getItemId());
    n18.setFoodName("Soybean");
    System.out.println("Food:" +n18.getFoodName());
    n18.setCalories(446);
    System.out.println("Calories:" +n18.getCalories());
    n18.setProtein(36);
    System.out.println("Protein:" +n18.getProtein());
    n18.setFat(20);
    System.out.println("Fat:" +n18.getFat());
    n18.setCarbs(30);
    System.out.println("Carbs:" +n18.getCarbs());
    n18.setCategory("Protein");
    System.out.println("Category:" +n18.getCategory());

    System.out.println();
    NutritionTable n19 = new NutritionTable();
    n19.setItemId(19);
    System.out.println("Item Id:" +n19.getItemId());
    n19.setFoodName("Corn");
    System.out.println("Food:" +n19.getFoodName());
    n19.setCalories(86);
    System.out.println("Calories:" +n19.getCalories());
    n19.setProtein(3.2);
    System.out.println("Protein:" +n19.getProtein());
    n19.setFat(1.2);
    System.out.println("Fat:" +n19.getFat());
    n19.setCarbs(19);
    System.out.println("Carbs:" +n19.getCarbs());
    n19.setCategory("Grain");
    System.out.println("Category:" +n19.getCategory());

    System.out.println();
    NutritionTable n20 = new NutritionTable();
    n20.setItemId(20);
    System.out.println("Item Id:" +n20.getItemId());
    n20.setFoodName("Honey");
    System.out.println("Food:" +n20.getFoodName());
    n20.setCalories(304);
    System.out.println("Calories:" +n20.getCalories());
    n20.setProtein(0.3);
    System.out.println("Protein:" +n20.getProtein());
    n20.setFat(0);
    System.out.println("Fat:" +n20.getFat());
    n20.setCarbs(82);
    System.out.println("Carbs:" +n20.getCarbs());
    n20.setCategory("Sweet");
    System.out.println("Category:" +n20.getCategory());
	
	System.out.println();
    NutritionTable n21 = new NutritionTable();
    n21.setItemId(21);
    System.out.println("Item Id:" +n21.getItemId());
    n21.setFoodName("Oats");
    System.out.println("Food:" +n21.getFoodName());
    n21.setCalories(389);
    System.out.println("Calories:" +n21.getCalories());
    n21.setProtein(17);
    System.out.println("Protein:" +n21.getProtein());
    n21.setFat(7);
    System.out.println("Fat:" +n21.getFat());
    n21.setCarbs(66);
    System.out.println("Carbs:" +n21.getCarbs());
    n21.setCategory("Grain");
    System.out.println("Category:" +n21.getCategory());

    System.out.println();
    NutritionTable n22 = new NutritionTable();
    n22.setItemId(22);
    System.out.println("Item Id:" +n22.getItemId());
    n22.setFoodName("Orange");
    System.out.println("Food:" +n22.getFoodName());
    n22.setCalories(47);
    System.out.println("Calories:" +n22.getCalories());
    n22.setProtein(0.9);
    System.out.println("Protein:" +n22.getProtein());
    n22.setFat(0.1);
    System.out.println("Fat:" +n22.getFat());
    n22.setCarbs(12);
    System.out.println("Carbs:" +n22.getCarbs());
    n22.setCategory("Fruit");
    System.out.println("Category:" +n22.getCategory());

    System.out.println();
    NutritionTable n23 = new NutritionTable();
    n23.setItemId(23);
    System.out.println("Item Id:" +n23.getItemId());
    n23.setFoodName("Carrot");
    System.out.println("Food:" +n23.getFoodName());
    n23.setCalories(41);
    System.out.println("Calories:" +n23.getCalories());
    n23.setProtein(0.9);
    System.out.println("Protein:" +n23.getProtein());
    n23.setFat(0.2);
    System.out.println("Fat:" +n23.getFat());
    n23.setCarbs(10);
    System.out.println("Carbs:" +n23.getCarbs());
    n23.setCategory("Vegetable");
    System.out.println("Category:" +n23.getCategory());

    System.out.println();
    NutritionTable n24 = new NutritionTable();
    n24.setItemId(24);
    System.out.println("Item Id:" +n24.getItemId());
    n24.setFoodName("Potato");
    System.out.println("Food:" +n24.getFoodName());
    n24.setCalories(77);
    System.out.println("Calories:" +n24.getCalories());
    n24.setProtein(2);
    System.out.println("Protein:" +n24.getProtein());
    n24.setFat(0.1);
    System.out.println("Fat:" +n24.getFat());
    n24.setCarbs(17);
    System.out.println("Carbs:" +n24.getCarbs());
    n24.setCategory("Vegetable");
    System.out.println("Category:" +n24.getCategory());

    System.out.println();
    NutritionTable n25 = new NutritionTable();
    n25.setItemId(25);
    System.out.println("Item Id:" +n25.getItemId());
    n25.setFoodName("Tomato");
    System.out.println("Food:" +n25.getFoodName());
    n25.setCalories(18);
    System.out.println("Calories:" +n25.getCalories());
    n25.setProtein(0.9);
    System.out.println("Protein:" +n25.getProtein());
    n25.setFat(0.2);
    System.out.println("Fat:" +n25.getFat());
    n25.setCarbs(3.9);
    System.out.println("Carbs:" +n25.getCarbs());
    n25.setCategory("Vegetable");
    System.out.println("Category:" +n25.getCategory());

    System.out.println();
    NutritionTable n26 = new NutritionTable();
    n26.setItemId(26);
    System.out.println("Item Id:" +n26.getItemId());
    n26.setFoodName("Cheese");
    System.out.println("Food:" +n26.getFoodName());
    n26.setCalories(402);
    System.out.println("Calories:" +n26.getCalories());
    n26.setProtein(25);
    System.out.println("Protein:" +n26.getProtein());
    n26.setFat(33);
    System.out.println("Fat:" +n26.getFat());
    n26.setCarbs(1.3);
    System.out.println("Carbs:" +n26.getCarbs());
    n26.setCategory("Dairy");
    System.out.println("Category:" +n26.getCategory());

    System.out.println();
    NutritionTable n27 = new NutritionTable();
    n27.setItemId(27);
    System.out.println("Item Id:" +n27.getItemId());
    n27.setFoodName("Butter");
    System.out.println("Food:" +n27.getFoodName());
    n27.setCalories(717);
    System.out.println("Calories:" +n27.getCalories());
    n27.setProtein(0.9);
    System.out.println("Protein:" +n27.getProtein());
    n27.setFat(81);
    System.out.println("Fat:" +n27.getFat());
    n27.setCarbs(0.1);
    System.out.println("Carbs:" +n27.getCarbs());
    n27.setCategory("Dairy");
    System.out.println("Category:" +n27.getCategory());

    System.out.println();
    NutritionTable n28 = new NutritionTable();
    n28.setItemId(28);
    System.out.println("Item Id:" +n28.getItemId());
    n28.setFoodName("Spinach");
    System.out.println("Food:" +n28.getFoodName());
    n28.setCalories(23);
    System.out.println("Calories:" +n28.getCalories());
    n28.setProtein(2.9);
    System.out.println("Protein:" +n28.getProtein());
    n28.setFat(0.4);
    System.out.println("Fat:" +n28.getFat());
    n28.setCarbs(3.6);
    System.out.println("Carbs:" +n28.getCarbs());
    n28.setCategory("Vegetable");
    System.out.println("Category:" +n28.getCategory());

    System.out.println();
    NutritionTable n29 = new NutritionTable();
    n29.setItemId(29);
    System.out.println("Item Id:" +n29.getItemId());
    n29.setFoodName("Peanuts");
    System.out.println("Food:" +n29.getFoodName());
    n29.setCalories(567);
    System.out.println("Calories:" +n29.getCalories());
    n29.setProtein(26);
    System.out.println("Protein:" +n29.getProtein());
    n29.setFat(49);
    System.out.println("Fat:" +n29.getFat());
    n29.setCarbs(16);
    System.out.println("Carbs:" +n29.getCarbs());
    n29.setCategory("Nuts");
    System.out.println("Category:" +n29.getCategory());

 }
}