class OrderDetailsExecutor {
 public static void main(String[] args){
    OrderDetails order1 = new OrderDetails();
    order1.setOrderId(1);
    System.out.println("Order Id:" +order1.getOrderId());
    order1.setProductName("Laptop");
    System.out.println("Product:" +order1.getProductName());
    order1.setQuantity(1);
    System.out.println("Quantity:" +order1.getQuantity());
    order1.setPrice(55000);
    System.out.println("Price:" +order1.getPrice());
    order1.setOrderDate("01-01-2026");
    System.out.println("Date:" +order1.getOrderDate());
    order1.setStatus("Delivered");
    System.out.println("Status:" +order1.getStatus());
    order1.setCustomerName("Harsha");
    System.out.println("Customer:" +order1.getCustomerName());

    System.out.println();
    OrderDetails order2 = new OrderDetails();
    order2.setOrderId(2);
    System.out.println("Order Id:" +order2.getOrderId());
    order2.setProductName("Mobile");
    System.out.println("Product:" +order2.getProductName());
    order2.setQuantity(2);
    System.out.println("Quantity:" +order2.getQuantity());
    order2.setPrice(20000);
    System.out.println("Price:" +order2.getPrice());
    order2.setOrderDate("02-01-2026");
    System.out.println("Date:" +order2.getOrderDate());
    order2.setStatus("Shipped");
    System.out.println("Status:" +order2.getStatus());
    order2.setCustomerName("Lohith");
    System.out.println("Customer:" +order2.getCustomerName());

    System.out.println();
    OrderDetails order3 = new OrderDetails();
    order3.setOrderId(3);
    System.out.println("Order Id:" +order3.getOrderId());
    order3.setProductName("Headphones");
    System.out.println("Product:" +order3.getProductName());
    order3.setQuantity(1);
    System.out.println("Quantity:" +order3.getQuantity());
    order3.setPrice(1500);
    System.out.println("Price:" +order3.getPrice());
    order3.setOrderDate("03-01-2026");
    System.out.println("Date:" +order3.getOrderDate());
    order3.setStatus("Pending");
    System.out.println("Status:" +order3.getStatus());
    order3.setCustomerName("Kiran");
    System.out.println("Customer:" +order3.getCustomerName());

    System.out.println();
    OrderDetails order4 = new OrderDetails();
    order4.setOrderId(4);
    System.out.println("Order Id:" +order4.getOrderId());
    order4.setProductName("Keyboard");
    System.out.println("Product:" +order4.getProductName());
    order4.setQuantity(1);
    System.out.println("Quantity:" +order4.getQuantity());
    order4.setPrice(800);
    System.out.println("Price:" +order4.getPrice());
    order4.setOrderDate("04-01-2026");
    System.out.println("Date:" +order4.getOrderDate());
    order4.setStatus("Delivered");
    System.out.println("Status:" +order4.getStatus());
    order4.setCustomerName("Suresh");
    System.out.println("Customer:" +order4.getCustomerName());

    System.out.println();
    OrderDetails order5 = new OrderDetails();
    order5.setOrderId(5);
    System.out.println("Order Id:" +order5.getOrderId());
    order5.setProductName("Mouse");
    System.out.println("Product:" +order5.getProductName());
    order5.setQuantity(2);
    System.out.println("Quantity:" +order5.getQuantity());
    order5.setPrice(500);
    System.out.println("Price:" +order5.getPrice());
    order5.setOrderDate("05-01-2026");
    System.out.println("Date:" +order5.getOrderDate());
    order5.setStatus("Cancelled");
    System.out.println("Status:" +order5.getStatus());
    order5.setCustomerName("Ravi");
    System.out.println("Customer:" +order5.getCustomerName());
	
	System.out.println();
    OrderDetails order6 = new OrderDetails();
    order6.setOrderId(6);
    System.out.println("Order Id:" +order6.getOrderId());
    order6.setProductName("Keyboard");
    System.out.println("Product:" +order6.getProductName());
    order6.setQuantity(1);
    System.out.println("Quantity:" +order6.getQuantity());
    order6.setPrice(1200);
    System.out.println("Price:" +order6.getPrice());
    order6.setOrderDate("06-01-2026");
    System.out.println("Date:" +order6.getOrderDate());
    order6.setStatus("Delivered");
    System.out.println("Status:" +order6.getStatus());
    order6.setCustomerName("Amit");
    System.out.println("Customer:" +order6.getCustomerName());

    System.out.println();
    OrderDetails order7 = new OrderDetails();
    order7.setOrderId(7);
    System.out.println("Order Id:" +order7.getOrderId());
    order7.setProductName("Monitor");
    System.out.println("Product:" +order7.getProductName());
    order7.setQuantity(1);
    System.out.println("Quantity:" +order7.getQuantity());
    order7.setPrice(8000);
    System.out.println("Price:" +order7.getPrice());
    order7.setOrderDate("07-01-2026");
    System.out.println("Date:" +order7.getOrderDate());
    order7.setStatus("Shipped");
    System.out.println("Status:" +order7.getStatus());
    order7.setCustomerName("Sneha");
    System.out.println("Customer:" +order7.getCustomerName());

    System.out.println();
    OrderDetails order8 = new OrderDetails();
    order8.setOrderId(8);
    System.out.println("Order Id:" +order8.getOrderId());
    order8.setProductName("Laptop");
    System.out.println("Product:" +order8.getProductName());
    order8.setQuantity(1);
    System.out.println("Quantity:" +order8.getQuantity());
    order8.setPrice(55000);
    System.out.println("Price:" +order8.getPrice());
    order8.setOrderDate("08-01-2026");
    System.out.println("Date:" +order8.getOrderDate());
    order8.setStatus("Delivered");
    System.out.println("Status:" +order8.getStatus());
    order8.setCustomerName("Kiran");
    System.out.println("Customer:" +order8.getCustomerName());

    System.out.println();
    OrderDetails order9 = new OrderDetails();
    order9.setOrderId(9);
    System.out.println("Order Id:" +order9.getOrderId());
    order9.setProductName("Headphones");
    System.out.println("Product:" +order9.getProductName());
    order9.setQuantity(2);
    System.out.println("Quantity:" +order9.getQuantity());
    order9.setPrice(2000);
    System.out.println("Price:" +order9.getPrice());
    order9.setOrderDate("09-01-2026");
    System.out.println("Date:" +order9.getOrderDate());
    order9.setStatus("Pending");
    System.out.println("Status:" +order9.getStatus());
    order9.setCustomerName("Rahul");
    System.out.println("Customer:" +order9.getCustomerName());

    System.out.println();
    OrderDetails order10 = new OrderDetails();
    order10.setOrderId(10);
    System.out.println("Order Id:" +order10.getOrderId());
    order10.setProductName("Speaker");
    System.out.println("Product:" +order10.getProductName());
    order10.setQuantity(1);
    System.out.println("Quantity:" +order10.getQuantity());
    order10.setPrice(3000);
    System.out.println("Price:" +order10.getPrice());
    order10.setOrderDate("10-01-2026");
    System.out.println("Date:" +order10.getOrderDate());
    order10.setStatus("Delivered");
    System.out.println("Status:" +order10.getStatus());
    order10.setCustomerName("Divya");
    System.out.println("Customer:" +order10.getCustomerName());
	
	System.out.println();
    OrderDetails order11 = new OrderDetails();
    order11.setOrderId(11);
    System.out.println("Order Id:" +order11.getOrderId());
    order11.setProductName("Tablet");
    System.out.println("Product:" +order11.getProductName());
    order11.setQuantity(1);
    System.out.println("Quantity:" +order11.getQuantity());
    order11.setPrice(15000);
    System.out.println("Price:" +order11.getPrice());
    order11.setOrderDate("11-01-2026");
    System.out.println("Date:" +order11.getOrderDate());
    order11.setStatus("Delivered");
    System.out.println("Status:" +order11.getStatus());
    order11.setCustomerName("Anjali");
    System.out.println("Customer:" +order11.getCustomerName());

    System.out.println();
    OrderDetails order12 = new OrderDetails();
    order12.setOrderId(12);
    System.out.println("Order Id:" +order12.getOrderId());
    order12.setProductName("Webcam");
    System.out.println("Product:" +order12.getProductName());
    order12.setQuantity(1);
    System.out.println("Quantity:" +order12.getQuantity());
    order12.setPrice(2500);
    System.out.println("Price:" +order12.getPrice());
    order12.setOrderDate("12-01-2026");
    System.out.println("Date:" +order12.getOrderDate());
    order12.setStatus("Pending");
    System.out.println("Status:" +order12.getStatus());
    order12.setCustomerName("Karthik");
    System.out.println("Customer:" +order12.getCustomerName());

    System.out.println();
    OrderDetails order13 = new OrderDetails();
    order13.setOrderId(13);
    System.out.println("Order Id:" +order13.getOrderId());
    order13.setProductName("Charger");
    System.out.println("Product:" +order13.getProductName());
    order13.setQuantity(2);
    System.out.println("Quantity:" +order13.getQuantity());
    order13.setPrice(1000);
    System.out.println("Price:" +order13.getPrice());
    order13.setOrderDate("13-01-2026");
    System.out.println("Date:" +order13.getOrderDate());
    order13.setStatus("Shipped");
    System.out.println("Status:" +order13.getStatus());
    order13.setCustomerName("Pooja");
    System.out.println("Customer:" +order13.getCustomerName());

    System.out.println();
    OrderDetails order14 = new OrderDetails();
    order14.setOrderId(14);
    System.out.println("Order Id:" +order14.getOrderId());
    order14.setProductName("USB Cable");
    System.out.println("Product:" +order14.getProductName());
    order14.setQuantity(3);
    System.out.println("Quantity:" +order14.getQuantity());
    order14.setPrice(600);
    System.out.println("Price:" +order14.getPrice());
    order14.setOrderDate("14-01-2026");
    System.out.println("Date:" +order14.getOrderDate());
    order14.setStatus("Delivered");
    System.out.println("Status:" +order14.getStatus());
    order14.setCustomerName("Ramesh");
    System.out.println("Customer:" +order14.getCustomerName());

    System.out.println();
    OrderDetails order15 = new OrderDetails();
    order15.setOrderId(15);
    System.out.println("Order Id:" +order15.getOrderId());
    order15.setProductName("Power Bank");
    System.out.println("Product:" +order15.getProductName());
    order15.setQuantity(1);
    System.out.println("Quantity:" +order15.getQuantity());
    order15.setPrice(2000);
    System.out.println("Price:" +order15.getPrice());
    order15.setOrderDate("15-01-2026");
    System.out.println("Date:" +order15.getOrderDate());
    order15.setStatus("Cancelled");
    System.out.println("Status:" +order15.getStatus());
    order15.setCustomerName("Suresh");
    System.out.println("Customer:" +order15.getCustomerName());

    System.out.println();
    OrderDetails order16 = new OrderDetails();
    order16.setOrderId(16);
    System.out.println("Order Id:" +order16.getOrderId());
    order16.setProductName("Smart Watch");
    System.out.println("Product:" +order16.getProductName());
    order16.setQuantity(1);
    System.out.println("Quantity:" +order16.getQuantity());
    order16.setPrice(5000);
    System.out.println("Price:" +order16.getPrice());
    order16.setOrderDate("16-01-2026");
    System.out.println("Date:" +order16.getOrderDate());
    order16.setStatus("Delivered");
    System.out.println("Status:" +order16.getStatus());
    order16.setCustomerName("Meena");
    System.out.println("Customer:" +order16.getCustomerName());

    System.out.println();
    OrderDetails order17 = new OrderDetails();
    order17.setOrderId(17);
    System.out.println("Order Id:" +order17.getOrderId());
    order17.setProductName("Router");
    System.out.println("Product:" +order17.getProductName());
    order17.setQuantity(1);
    System.out.println("Quantity:" +order17.getQuantity());
    order17.setPrice(3500);
    System.out.println("Price:" +order17.getPrice());
    order17.setOrderDate("17-01-2026");
    System.out.println("Date:" +order17.getOrderDate());
    order17.setStatus("Shipped");
    System.out.println("Status:" +order17.getStatus());
    order17.setCustomerName("Arjun");
    System.out.println("Customer:" +order17.getCustomerName());

    System.out.println();
    OrderDetails order18 = new OrderDetails();
    order18.setOrderId(18);
    System.out.println("Order Id:" +order18.getOrderId());
    order18.setProductName("SSD");
    System.out.println("Product:" +order18.getProductName());
    order18.setQuantity(1);
    System.out.println("Quantity:" +order18.getQuantity());
    order18.setPrice(7000);
    System.out.println("Price:" +order18.getPrice());
    order18.setOrderDate("18-01-2026");
    System.out.println("Date:" +order18.getOrderDate());
    order18.setStatus("Delivered");
    System.out.println("Status:" +order18.getStatus());
    order18.setCustomerName("Divya");
    System.out.println("Customer:" +order18.getCustomerName());

    System.out.println();
    OrderDetails order19 = new OrderDetails();
    order19.setOrderId(19);
    System.out.println("Order Id:" +order19.getOrderId());
    order19.setProductName("Hard Disk");
    System.out.println("Product:" +order19.getProductName());
    order19.setQuantity(1);
    System.out.println("Quantity:" +order19.getQuantity());
    order19.setPrice(6000);
    System.out.println("Price:" +order19.getPrice());
    order19.setOrderDate("19-01-2026");
    System.out.println("Date:" +order19.getOrderDate());
    order19.setStatus("Pending");
    System.out.println("Status:" +order19.getStatus());
    order19.setCustomerName("Rahul");
    System.out.println("Customer:" +order19.getCustomerName());

    System.out.println();
    OrderDetails order20 = new OrderDetails();
    order20.setOrderId(20);
    System.out.println("Order Id:" +order20.getOrderId());
    order20.setProductName("Printer");
    System.out.println("Product:" +order20.getProductName());
    order20.setQuantity(1);
    System.out.println("Quantity:" +order20.getQuantity());
    order20.setPrice(9000);
    System.out.println("Price:" +order20.getPrice());
    order20.setOrderDate("20-01-2026");
    System.out.println("Date:" +order20.getOrderDate());
    order20.setStatus("Delivered");
    System.out.println("Status:" +order20.getStatus());
    order20.setCustomerName("Nikhil");
    System.out.println("Customer:" +order20.getCustomerName());
	
	    System.out.println();
    OrderDetails order21 = new OrderDetails();
    order21.setOrderId(21);
    System.out.println("Order Id:" +order21.getOrderId());
    order21.setProductName("Graphics Card");
    System.out.println("Product:" +order21.getProductName());
    order21.setQuantity(1);
    System.out.println("Quantity:" +order21.getQuantity());
    order21.setPrice(25000);
    System.out.println("Price:" +order21.getPrice());
    order21.setOrderDate("21-01-2026");
    System.out.println("Date:" +order21.getOrderDate());
    order21.setStatus("Delivered");
    System.out.println("Status:" +order21.getStatus());
    order21.setCustomerName("Tarun");
    System.out.println("Customer:" +order21.getCustomerName());

    System.out.println();
    OrderDetails order22 = new OrderDetails();
    order22.setOrderId(22);
    System.out.println("Order Id:" +order22.getOrderId());
    order22.setProductName("RAM");
    System.out.println("Product:" +order22.getProductName());
    order22.setQuantity(2);
    System.out.println("Quantity:" +order22.getQuantity());
    order22.setPrice(8000);
    System.out.println("Price:" +order22.getPrice());
    order22.setOrderDate("22-01-2026");
    System.out.println("Date:" +order22.getOrderDate());
    order22.setStatus("Shipped");
    System.out.println("Status:" +order22.getStatus());
    order22.setCustomerName("Ravi");
    System.out.println("Customer:" +order22.getCustomerName());

    System.out.println();
    OrderDetails order23 = new OrderDetails();
    order23.setOrderId(23);
    System.out.println("Order Id:" +order23.getOrderId());
    order23.setProductName("Motherboard");
    System.out.println("Product:" +order23.getProductName());
    order23.setQuantity(1);
    System.out.println("Quantity:" +order23.getQuantity());
    order23.setPrice(12000);
    System.out.println("Price:" +order23.getPrice());
    order23.setOrderDate("23-01-2026");
    System.out.println("Date:" +order23.getOrderDate());
    order23.setStatus("Delivered");
    System.out.println("Status:" +order23.getStatus());
    order23.setCustomerName("Kiran");
    System.out.println("Customer:" +order23.getCustomerName());

    System.out.println();
    OrderDetails order24 = new OrderDetails();
    order24.setOrderId(24);
    System.out.println("Order Id:" +order24.getOrderId());
    order24.setProductName("Cooling Fan");
    System.out.println("Product:" +order24.getProductName());
    order24.setQuantity(3);
    System.out.println("Quantity:" +order24.getQuantity());
    order24.setPrice(1500);
    System.out.println("Price:" +order24.getPrice());
    order24.setOrderDate("24-01-2026");
    System.out.println("Date:" +order24.getOrderDate());
    order24.setStatus("Pending");
    System.out.println("Status:" +order24.getStatus());
    order24.setCustomerName("Sneha");
    System.out.println("Customer:" +order24.getCustomerName());

    System.out.println();
    OrderDetails order25 = new OrderDetails();
    order25.setOrderId(25);
    System.out.println("Order Id:" +order25.getOrderId());
    order25.setProductName("Cabinet");
    System.out.println("Product:" +order25.getProductName());
    order25.setQuantity(1);
    System.out.println("Quantity:" +order25.getQuantity());
    order25.setPrice(4000);
    System.out.println("Price:" +order25.getPrice());
    order25.setOrderDate("25-01-2026");
    System.out.println("Date:" +order25.getOrderDate());
    order25.setStatus("Delivered");
    System.out.println("Status:" +order25.getStatus());
    order25.setCustomerName("Arjun");
    System.out.println("Customer:" +order25.getCustomerName());

    System.out.println();
    OrderDetails order26 = new OrderDetails();
    order26.setOrderId(26);
    System.out.println("Order Id:" +order26.getOrderId());
    order26.setProductName("Projector");
    System.out.println("Product:" +order26.getProductName());
    order26.setQuantity(1);
    System.out.println("Quantity:" +order26.getQuantity());
    order26.setPrice(20000);
    System.out.println("Price:" +order26.getPrice());
    order26.setOrderDate("26-01-2026");
    System.out.println("Date:" +order26.getOrderDate());
    order26.setStatus("Shipped");
    System.out.println("Status:" +order26.getStatus());
    order26.setCustomerName("Divya");
    System.out.println("Customer:" +order26.getCustomerName());

    System.out.println();
    OrderDetails order27 = new OrderDetails();
    order27.setOrderId(27);
    System.out.println("Order Id:" +order27.getOrderId());
    order27.setProductName("Scanner");
    System.out.println("Product:" +order27.getProductName());
    order27.setQuantity(1);
    System.out.println("Quantity:" +order27.getQuantity());
    order27.setPrice(7000);
    System.out.println("Price:" +order27.getPrice());
    order27.setOrderDate("27-01-2026");
    System.out.println("Date:" +order27.getOrderDate());
    order27.setStatus("Delivered");
    System.out.println("Status:" +order27.getStatus());
    order27.setCustomerName("Rahul");
    System.out.println("Customer:" +order27.getCustomerName());

    System.out.println();
    OrderDetails order28 = new OrderDetails();
    order28.setOrderId(28);
    System.out.println("Order Id:" +order28.getOrderId());
    order28.setProductName("Pen Drive");
    System.out.println("Product:" +order28.getProductName());
    order28.setQuantity(4);
    System.out.println("Quantity:" +order28.getQuantity());
    order28.setPrice(2000);
    System.out.println("Price:" +order28.getPrice());
    order28.setOrderDate("28-01-2026");
    System.out.println("Date:" +order28.getOrderDate());
    order28.setStatus("Pending");
    System.out.println("Status:" +order28.getStatus());
    order28.setCustomerName("Pooja");
    System.out.println("Customer:" +order28.getCustomerName());

    System.out.println();
    OrderDetails order29 = new OrderDetails();
    order29.setOrderId(29);
    System.out.println("Order Id:" +order29.getOrderId());
    order29.setProductName("External HDD");
    System.out.println("Product:" +order29.getProductName());
    order29.setQuantity(1);
    System.out.println("Quantity:" +order29.getQuantity());
    order29.setPrice(6500);
    System.out.println("Price:" +order29.getPrice());
    order29.setOrderDate("29-01-2026");
    System.out.println("Date:" +order29.getOrderDate());
    order29.setStatus("Delivered");
    System.out.println("Status:" +order29.getStatus());
    order29.setCustomerName("Nikhil");
    System.out.println("Customer:" +order29.getCustomerName());
	
 }
}