class PatientExecutor {
 public static void main(String[] args){

    System.out.println();
    Patient p1 = new Patient();
    p1.setPatientId(1);
    System.out.println("Patient Id:" +p1.getPatientId());
    p1.setName("Ravi");
    System.out.println("Name:" +p1.getName());
    p1.setAge(30);
    System.out.println("Age:" +p1.getAge());
    p1.setGender("Male");
    System.out.println("Gender:" +p1.getGender());
    p1.setDisease("Fever");
    System.out.println("Disease:" +p1.getDisease());
    p1.setDoctorName("Dr. Kumar");
    System.out.println("Doctor:" +p1.getDoctorName());
    p1.setHospitalName("Apollo");
    System.out.println("Hospital:" +p1.getHospitalName());

    System.out.println();
    Patient p2 = new Patient();
    p2.setPatientId(2);
    System.out.println("Patient Id:" +p2.getPatientId());
    p2.setName("Sneha");
    System.out.println("Name:" +p2.getName());
    p2.setAge(25);
    System.out.println("Age:" +p2.getAge());
    p2.setGender("Female");
    System.out.println("Gender:" +p2.getGender());
    p2.setDisease("Cold");
    System.out.println("Disease:" +p2.getDisease());
    p2.setDoctorName("Dr. Meena");
    System.out.println("Doctor:" +p2.getDoctorName());
    p2.setHospitalName("Fortis");
    System.out.println("Hospital:" +p2.getHospitalName());
	
	System.out.println();
    Patient p3 = new Patient();
    p3.setPatientId(3);
    System.out.println("Patient Id:" +p3.getPatientId());
    p3.setName("Arjun");
    System.out.println("Name:" +p3.getName());
    p3.setAge(40);
    System.out.println("Age:" +p3.getAge());
    p3.setGender("Male");
    System.out.println("Gender:" +p3.getGender());
    p3.setDisease("Diabetes");
    System.out.println("Disease:" +p3.getDisease());
    p3.setDoctorName("Dr. Ramesh");
    System.out.println("Doctor:" +p3.getDoctorName());
    p3.setHospitalName("Manipal");
    System.out.println("Hospital:" +p3.getHospitalName());

    System.out.println();
    Patient p4 = new Patient();
    p4.setPatientId(4);
    System.out.println("Patient Id:" +p4.getPatientId());
    p4.setName("Pooja");
    System.out.println("Name:" +p4.getName());
    p4.setAge(28);
    System.out.println("Age:" +p4.getAge());
    p4.setGender("Female");
    System.out.println("Gender:" +p4.getGender());
    p4.setDisease("Asthma");
    System.out.println("Disease:" +p4.getDisease());
    p4.setDoctorName("Dr. Anita");
    System.out.println("Doctor:" +p4.getDoctorName());
    p4.setHospitalName("Columbia Asia");
    System.out.println("Hospital:" +p4.getHospitalName());

    System.out.println();
    Patient p5 = new Patient();
    p5.setPatientId(5);
    System.out.println("Patient Id:" +p5.getPatientId());
    p5.setName("Kiran");
    System.out.println("Name:" +p5.getName());
    p5.setAge(35);
    System.out.println("Age:" +p5.getAge());
    p5.setGender("Male");
    System.out.println("Gender:" +p5.getGender());
    p5.setDisease("Migraine");
    System.out.println("Disease:" +p5.getDisease());
    p5.setDoctorName("Dr. Suresh");
    System.out.println("Doctor:" +p5.getDoctorName());
    p5.setHospitalName("Narayana");
    System.out.println("Hospital:" +p5.getHospitalName());

    System.out.println();
    Patient p6 = new Patient();
    p6.setPatientId(6);
    System.out.println("Patient Id:" +p6.getPatientId());
    p6.setName("Meena");
    System.out.println("Name:" +p6.getName());
    p6.setAge(50);
    System.out.println("Age:" +p6.getAge());
    p6.setGender("Female");
    System.out.println("Gender:" +p6.getGender());
    p6.setDisease("Hypertension");
    System.out.println("Disease:" +p6.getDisease());
    p6.setDoctorName("Dr. Ravi");
    System.out.println("Doctor:" +p6.getDoctorName());
    p6.setHospitalName("Apollo");
    System.out.println("Hospital:" +p6.getHospitalName());

    System.out.println();
    Patient p7 = new Patient();
    p7.setPatientId(7);
    System.out.println("Patient Id:" +p7.getPatientId());
    p7.setName("Vijay");
    System.out.println("Name:" +p7.getName());
    p7.setAge(45);
    System.out.println("Age:" +p7.getAge());
    p7.setGender("Male");
    System.out.println("Gender:" +p7.getGender());
    p7.setDisease("Heart Disease");
    System.out.println("Disease:" +p7.getDisease());
    p7.setDoctorName("Dr. Reddy");
    System.out.println("Doctor:" +p7.getDoctorName());
    p7.setHospitalName("Fortis");
    System.out.println("Hospital:" +p7.getHospitalName());

    System.out.println();
    Patient p8 = new Patient();
    p8.setPatientId(8);
    System.out.println("Patient Id:" +p8.getPatientId());
    p8.setName("Anjali");
    System.out.println("Name:" +p8.getName());
    p8.setAge(22);
    System.out.println("Age:" +p8.getAge());
    p8.setGender("Female");
    System.out.println("Gender:" +p8.getGender());
    p8.setDisease("Allergy");
    System.out.println("Disease:" +p8.getDisease());
    p8.setDoctorName("Dr. Neha");
    System.out.println("Doctor:" +p8.getDoctorName());
    p8.setHospitalName("Cloudnine");
    System.out.println("Hospital:" +p8.getHospitalName());

    System.out.println();
    Patient p9 = new Patient();
    p9.setPatientId(9);
    System.out.println("Patient Id:" +p9.getPatientId());
    p9.setName("Rahul");
    System.out.println("Name:" +p9.getName());
    p9.setAge(33);
    System.out.println("Age:" +p9.getAge());
    p9.setGender("Male");
    System.out.println("Gender:" +p9.getGender());
    p9.setDisease("Back Pain");
    System.out.println("Disease:" +p9.getDisease());
    p9.setDoctorName("Dr. Arjun");
    System.out.println("Doctor:" +p9.getDoctorName());
    p9.setHospitalName("Manipal");
    System.out.println("Hospital:" +p9.getHospitalName());

    System.out.println();
    Patient p10 = new Patient();
    p10.setPatientId(10);
    System.out.println("Patient Id:" +p10.getPatientId());
    p10.setName("Lakshmi");
    System.out.println("Name:" +p10.getName());
    p10.setAge(60);
    System.out.println("Age:" +p10.getAge());
    p10.setGender("Female");
    System.out.println("Gender:" +p10.getGender());
    p10.setDisease("Arthritis");
    System.out.println("Disease:" +p10.getDisease());
    p10.setDoctorName("Dr. Shankar");
    System.out.println("Doctor:" +p10.getDoctorName());
    p10.setHospitalName("Narayana");
    System.out.println("Hospital:" +p10.getHospitalName());
	
	System.out.println();
    Patient p11 = new Patient();
    p11.setPatientId(11);
    System.out.println("Patient Id:" +p11.getPatientId());
    p11.setName("Suresh");
    System.out.println("Name:" +p11.getName());
    p11.setAge(48);
    System.out.println("Age:" +p11.getAge());
    p11.setGender("Male");
    System.out.println("Gender:" +p11.getGender());
    p11.setDisease("Thyroid");
    System.out.println("Disease:" +p11.getDisease());
    p11.setDoctorName("Dr. Kavitha");
    System.out.println("Doctor:" +p11.getDoctorName());
    p11.setHospitalName("Apollo");
    System.out.println("Hospital:" +p11.getHospitalName());

    System.out.println();
    Patient p12 = new Patient();
    p12.setPatientId(12);
    System.out.println("Patient Id:" +p12.getPatientId());
    p12.setName("Priya");
    System.out.println("Name:" +p12.getName());
    p12.setAge(29);
    System.out.println("Age:" +p12.getAge());
    p12.setGender("Female");
    System.out.println("Gender:" +p12.getGender());
    p12.setDisease("Fever");
    System.out.println("Disease:" +p12.getDisease());
    p12.setDoctorName("Dr. Manoj");
    System.out.println("Doctor:" +p12.getDoctorName());
    p12.setHospitalName("Fortis");
    System.out.println("Hospital:" +p12.getHospitalName());

    System.out.println();
    Patient p13 = new Patient();
    p13.setPatientId(13);
    System.out.println("Patient Id:" +p13.getPatientId());
    p13.setName("Ramesh");
    System.out.println("Name:" +p13.getName());
    p13.setAge(55);
    System.out.println("Age:" +p13.getAge());
    p13.setGender("Male");
    System.out.println("Gender:" +p13.getGender());
    p13.setDisease("Kidney Stone");
    System.out.println("Disease:" +p13.getDisease());
    p13.setDoctorName("Dr. Reddy");
    System.out.println("Doctor:" +p13.getDoctorName());
    p13.setHospitalName("Manipal");
    System.out.println("Hospital:" +p13.getHospitalName());

    System.out.println();
    Patient p14 = new Patient();
    p14.setPatientId(14);
    System.out.println("Patient Id:" +p14.getPatientId());
    p14.setName("Anita");
    System.out.println("Name:" +p14.getName());
    p14.setAge(34);
    System.out.println("Age:" +p14.getAge());
    p14.setGender("Female");
    System.out.println("Gender:" +p14.getGender());
    p14.setDisease("Skin Allergy");
    System.out.println("Disease:" +p14.getDisease());
    p14.setDoctorName("Dr. Neha");
    System.out.println("Doctor:" +p14.getDoctorName());
    p14.setHospitalName("Columbia Asia");
    System.out.println("Hospital:" +p14.getHospitalName());

    System.out.println();
    Patient p15 = new Patient();
    p15.setPatientId(15);
    System.out.println("Patient Id:" +p15.getPatientId());
    p15.setName("Karthik");
    System.out.println("Name:" +p15.getName());
    p15.setAge(38);
    System.out.println("Age:" +p15.getAge());
    p15.setGender("Male");
    System.out.println("Gender:" +p15.getGender());
    p15.setDisease("Diabetes");
    System.out.println("Disease:" +p15.getDisease());
    p15.setDoctorName("Dr. Suresh");
    System.out.println("Doctor:" +p15.getDoctorName());
    p15.setHospitalName("Narayana");
    System.out.println("Hospital:" +p15.getHospitalName());

    System.out.println();
    Patient p16 = new Patient();
    p16.setPatientId(16);
    System.out.println("Patient Id:" +p16.getPatientId());
    p16.setName("Divya");
    System.out.println("Name:" +p16.getName());
    p16.setAge(26);
    System.out.println("Age:" +p16.getAge());
    p16.setGender("Female");
    System.out.println("Gender:" +p16.getGender());
    p16.setDisease("Cold");
    System.out.println("Disease:" +p16.getDisease());
    p16.setDoctorName("Dr. Anil");
    System.out.println("Doctor:" +p16.getDoctorName());
    p16.setHospitalName("Apollo");
    System.out.println("Hospital:" +p16.getHospitalName());

    System.out.println();
    Patient p17 = new Patient();
    p17.setPatientId(17);
    System.out.println("Patient Id:" +p17.getPatientId());
    p17.setName("Manoj");
    System.out.println("Name:" +p17.getName());
    p17.setAge(42);
    System.out.println("Age:" +p17.getAge());
    p17.setGender("Male");
    System.out.println("Gender:" +p17.getGender());
    p17.setDisease("BP");
    System.out.println("Disease:" +p17.getDisease());
    p17.setDoctorName("Dr. Kumar");
    System.out.println("Doctor:" +p17.getDoctorName());
    p17.setHospitalName("Fortis");
    System.out.println("Hospital:" +p17.getHospitalName());

    System.out.println();
    Patient p18 = new Patient();
    p18.setPatientId(18);
    System.out.println("Patient Id:" +p18.getPatientId());
    p18.setName("Shreya");
    System.out.println("Name:" +p18.getName());
    p18.setAge(31);
    System.out.println("Age:" +p18.getAge());
    p18.setGender("Female");
    System.out.println("Gender:" +p18.getGender());
    p18.setDisease("Migraine");
    System.out.println("Disease:" +p18.getDisease());
    p18.setDoctorName("Dr. Ravi");
    System.out.println("Doctor:" +p18.getDoctorName());
    p18.setHospitalName("Manipal");
    System.out.println("Hospital:" +p18.getHospitalName());

    System.out.println();
    Patient p19 = new Patient();
    p19.setPatientId(19);
    System.out.println("Patient Id:" +p19.getPatientId());
    p19.setName("Ajay");
    System.out.println("Name:" +p19.getName());
    p19.setAge(50);
    System.out.println("Age:" +p19.getAge());
    p19.setGender("Male");
    System.out.println("Gender:" +p19.getGender());
    p19.setDisease("Heart Issue");
    System.out.println("Disease:" +p19.getDisease());
    p19.setDoctorName("Dr. Reddy");
    System.out.println("Doctor:" +p19.getDoctorName());
    p19.setHospitalName("Narayana");
    System.out.println("Hospital:" +p19.getHospitalName());

    System.out.println();
    Patient p20 = new Patient();
    p20.setPatientId(20);
    System.out.println("Patient Id:" +p20.getPatientId());
    p20.setName("Geetha");
    System.out.println("Name:" +p20.getName());
    p20.setAge(45);
    System.out.println("Age:" +p20.getAge());
    p20.setGender("Female");
    System.out.println("Gender:" +p20.getGender());
    p20.setDisease("Arthritis");
    System.out.println("Disease:" +p20.getDisease());
    p20.setDoctorName("Dr. Shankar");
    System.out.println("Doctor:" +p20.getDoctorName());
    p20.setHospitalName("Columbia Asia");
    System.out.println("Hospital:" +p20.getHospitalName());
	
	System.out.println();
    Patient p21 = new Patient();
    p21.setPatientId(21);
    System.out.println("Patient Id:" +p21.getPatientId());
    p21.setName("Naveen");
    System.out.println("Name:" +p21.getName());
    p21.setAge(36);
    System.out.println("Age:" +p21.getAge());
    p21.setGender("Male");
    System.out.println("Gender:" +p21.getGender());
    p21.setDisease("Fever");
    System.out.println("Disease:" +p21.getDisease());
    p21.setDoctorName("Dr. Anil");
    System.out.println("Doctor:" +p21.getDoctorName());
    p21.setHospitalName("Apollo");
    System.out.println("Hospital:" +p21.getHospitalName());

    System.out.println();
    Patient p22 = new Patient();
    p22.setPatientId(22);
    System.out.println("Patient Id:" +p22.getPatientId());
    p22.setName("Kavya");
    System.out.println("Name:" +p22.getName());
    p22.setAge(27);
    System.out.println("Age:" +p22.getAge());
    p22.setGender("Female");
    System.out.println("Gender:" +p22.getGender());
    p22.setDisease("Cold");
    System.out.println("Disease:" +p22.getDisease());
    p22.setDoctorName("Dr. Meena");
    System.out.println("Doctor:" +p22.getDoctorName());
    p22.setHospitalName("Fortis");
    System.out.println("Hospital:" +p22.getHospitalName());

    System.out.println();
    Patient p23 = new Patient();
    p23.setPatientId(23);
    System.out.println("Patient Id:" +p23.getPatientId());
    p23.setName("Harish");
    System.out.println("Name:" +p23.getName());
    p23.setAge(52);
    System.out.println("Age:" +p23.getAge());
    p23.setGender("Male");
    System.out.println("Gender:" +p23.getGender());
    p23.setDisease("Diabetes");
    System.out.println("Disease:" +p23.getDisease());
    p23.setDoctorName("Dr. Ramesh");
    System.out.println("Doctor:" +p23.getDoctorName());
    p23.setHospitalName("Narayana");
    System.out.println("Hospital:" +p23.getHospitalName());

    System.out.println();
    Patient p24 = new Patient();
    p24.setPatientId(24);
    System.out.println("Patient Id:" +p24.getPatientId());
    p24.setName("Swathi");
    System.out.println("Name:" +p24.getName());
    p24.setAge(33);
    System.out.println("Age:" +p24.getAge());
    p24.setGender("Female");
    System.out.println("Gender:" +p24.getGender());
    p24.setDisease("Asthma");
    System.out.println("Disease:" +p24.getDisease());
    p24.setDoctorName("Dr. Anita");
    System.out.println("Doctor:" +p24.getDoctorName());
    p24.setHospitalName("Columbia Asia");
    System.out.println("Hospital:" +p24.getHospitalName());

    System.out.println();
    Patient p25 = new Patient();
    p25.setPatientId(25);
    System.out.println("Patient Id:" +p25.getPatientId());
    p25.setName("Prakash");
    System.out.println("Name:" +p25.getName());
    p25.setAge(47);
    System.out.println("Age:" +p25.getAge());
    p25.setGender("Male");
    System.out.println("Gender:" +p25.getGender());
    p25.setDisease("BP");
    System.out.println("Disease:" +p25.getDisease());
    p25.setDoctorName("Dr. Kumar");
    System.out.println("Doctor:" +p25.getDoctorName());
    p25.setHospitalName("Apollo");
    System.out.println("Hospital:" +p25.getHospitalName());

    System.out.println();
    Patient p26 = new Patient();
    p26.setPatientId(26);
    System.out.println("Patient Id:" +p26.getPatientId());
    p26.setName("Deepa");
    System.out.println("Name:" +p26.getName());
    p26.setAge(29);
    System.out.println("Age:" +p26.getAge());
    p26.setGender("Female");
    System.out.println("Gender:" +p26.getGender());
    p26.setDisease("Allergy");
    System.out.println("Disease:" +p26.getDisease());
    p26.setDoctorName("Dr. Neha");
    System.out.println("Doctor:" +p26.getDoctorName());
    p26.setHospitalName("Fortis");
    System.out.println("Hospital:" +p26.getHospitalName());

    System.out.println();
    Patient p27 = new Patient();
    p27.setPatientId(27);
    System.out.println("Patient Id:" +p27.getPatientId());
    p27.setName("Gopal");
    System.out.println("Name:" +p27.getName());
    p27.setAge(60);
    System.out.println("Age:" +p27.getAge());
    p27.setGender("Male");
    System.out.println("Gender:" +p27.getGender());
    p27.setDisease("Arthritis");
    System.out.println("Disease:" +p27.getDisease());
    p27.setDoctorName("Dr. Shankar");
    System.out.println("Doctor:" +p27.getDoctorName());
    p27.setHospitalName("Manipal");
    System.out.println("Hospital:" +p27.getHospitalName());

    System.out.println();
    Patient p28 = new Patient();
    p28.setPatientId(28);
    System.out.println("Patient Id:" +p28.getPatientId());
    p28.setName("Asha");
    System.out.println("Name:" +p28.getName());
    p28.setAge(41);
    System.out.println("Age:" +p28.getAge());
    p28.setGender("Female");
    System.out.println("Gender:" +p28.getGender());
    p28.setDisease("Thyroid");
    System.out.println("Disease:" +p28.getDisease());
    p28.setDoctorName("Dr. Kavitha");
    System.out.println("Doctor:" +p28.getDoctorName());
    p28.setHospitalName("Narayana");
    System.out.println("Hospital:" +p28.getHospitalName());

    System.out.println();
    Patient p29 = new Patient();
    p29.setPatientId(29);
    System.out.println("Patient Id:" +p29.getPatientId());
    p29.setName("Rohini");
    System.out.println("Name:" +p29.getName());
    p29.setAge(37);
    System.out.println("Age:" +p29.getAge());
    p29.setGender("Female");
    System.out.println("Gender:" +p29.getGender());
    p29.setDisease("Migraine");
    System.out.println("Disease:" +p29.getDisease());
    p29.setDoctorName("Dr. Ravi");
    System.out.println("Doctor:" +p29.getDoctorName());
    p29.setHospitalName("Apollo");
    System.out.println("Hospital:" +p29.getHospitalName());

 }
}