class PhoneSettingsExecutor {
 public static void main(String[] args){
    System.out.println();
    PhoneSettings p1 = new PhoneSettings();
    p1.setSettingId(1);
    System.out.println("Setting Id:" +p1.getSettingId());
    p1.setWifiName("Home_WiFi");
    System.out.println("WiFi:" +p1.getWifiName());
    p1.setBluetooth(true);
    System.out.println("Bluetooth:" +p1.getBluetooth());
    p1.setBrightness(70);
    System.out.println("Brightness:" +p1.getBrightness());
    p1.setMode("Normal");
    System.out.println("Mode:" +p1.getMode());
    p1.setVolume(80);
    System.out.println("Volume:" +p1.getVolume());
    p1.setAirplaneMode(false);
    System.out.println("Airplane:" +p1.getAirplaneMode());

    System.out.println();
    PhoneSettings p2 = new PhoneSettings();
    p2.setSettingId(2);
    System.out.println("Setting Id:" +p2.getSettingId());
    p2.setWifiName("Office_WiFi");
    System.out.println("WiFi:" +p2.getWifiName());
    p2.setBluetooth(false);
    System.out.println("Bluetooth:" +p2.getBluetooth());
    p2.setBrightness(50);
    System.out.println("Brightness:" +p2.getBrightness());
    p2.setMode("Silent");
    System.out.println("Mode:" +p2.getMode());
    p2.setVolume(20);
    System.out.println("Volume:" +p2.getVolume());
    p2.setAirplaneMode(false);
    System.out.println("Airplane:" +p2.getAirplaneMode());
	
	System.out.println();
    PhoneSettings p3 = new PhoneSettings();
    p3.setSettingId(3);
    System.out.println("Setting Id:" +p3.getSettingId());
    p3.setWifiName("Cafe_WiFi");
    System.out.println("WiFi:" +p3.getWifiName());
    p3.setBluetooth(true);
    System.out.println("Bluetooth:" +p3.getBluetooth());
    p3.setBrightness(60);
    System.out.println("Brightness:" +p3.getBrightness());
    p3.setMode("Normal");
    System.out.println("Mode:" +p3.getMode());
    p3.setVolume(70);
    System.out.println("Volume:" +p3.getVolume());
    p3.setAirplaneMode(false);
    System.out.println("Airplane:" +p3.getAirplaneMode());

    System.out.println();
    PhoneSettings p4 = new PhoneSettings();
    p4.setSettingId(4);
    System.out.println("Setting Id:" +p4.getSettingId());
    p4.setWifiName("College_WiFi");
    System.out.println("WiFi:" +p4.getWifiName());
    p4.setBluetooth(false);
    System.out.println("Bluetooth:" +p4.getBluetooth());
    p4.setBrightness(80);
    System.out.println("Brightness:" +p4.getBrightness());
    p4.setMode("Vibrate");
    System.out.println("Mode:" +p4.getMode());
    p4.setVolume(40);
    System.out.println("Volume:" +p4.getVolume());
    p4.setAirplaneMode(false);
    System.out.println("Airplane:" +p4.getAirplaneMode());

    System.out.println();
    PhoneSettings p5 = new PhoneSettings();
    p5.setSettingId(5);
    System.out.println("Setting Id:" +p5.getSettingId());
    p5.setWifiName("Airport_WiFi");
    System.out.println("WiFi:" +p5.getWifiName());
    p5.setBluetooth(true);
    System.out.println("Bluetooth:" +p5.getBluetooth());
    p5.setBrightness(90);
    System.out.println("Brightness:" +p5.getBrightness());
    p5.setMode("Normal");
    System.out.println("Mode:" +p5.getMode());
    p5.setVolume(85);
    System.out.println("Volume:" +p5.getVolume());
    p5.setAirplaneMode(true);
    System.out.println("Airplane:" +p5.getAirplaneMode());

    System.out.println();
    PhoneSettings p6 = new PhoneSettings();
    p6.setSettingId(6);
    System.out.println("Setting Id:" +p6.getSettingId());
    p6.setWifiName("Train_WiFi");
    System.out.println("WiFi:" +p6.getWifiName());
    p6.setBluetooth(false);
    System.out.println("Bluetooth:" +p6.getBluetooth());
    p6.setBrightness(40);
    System.out.println("Brightness:" +p6.getBrightness());
    p6.setMode("Silent");
    System.out.println("Mode:" +p6.getMode());
    p6.setVolume(10);
    System.out.println("Volume:" +p6.getVolume());
    p6.setAirplaneMode(true);
    System.out.println("Airplane:" +p6.getAirplaneMode());

    System.out.println();
    PhoneSettings p7 = new PhoneSettings();
    p7.setSettingId(7);
    System.out.println("Setting Id:" +p7.getSettingId());
    p7.setWifiName("Hostel_WiFi");
    System.out.println("WiFi:" +p7.getWifiName());
    p7.setBluetooth(true);
    System.out.println("Bluetooth:" +p7.getBluetooth());
    p7.setBrightness(75);
    System.out.println("Brightness:" +p7.getBrightness());
    p7.setMode("Normal");
    System.out.println("Mode:" +p7.getMode());
    p7.setVolume(65);
    System.out.println("Volume:" +p7.getVolume());
    p7.setAirplaneMode(false);
    System.out.println("Airplane:" +p7.getAirplaneMode());

    System.out.println();
    PhoneSettings p8 = new PhoneSettings();
    p8.setSettingId(8);
    System.out.println("Setting Id:" +p8.getSettingId());
    p8.setWifiName("Library_WiFi");
    System.out.println("WiFi:" +p8.getWifiName());
    p8.setBluetooth(false);
    System.out.println("Bluetooth:" +p8.getBluetooth());
    p8.setBrightness(30);
    System.out.println("Brightness:" +p8.getBrightness());
    p8.setMode("Silent");
    System.out.println("Mode:" +p8.getMode());
    p8.setVolume(5);
    System.out.println("Volume:" +p8.getVolume());
    p8.setAirplaneMode(false);
    System.out.println("Airplane:" +p8.getAirplaneMode());

    System.out.println();
    PhoneSettings p9 = new PhoneSettings();
    p9.setSettingId(9);
    System.out.println("Setting Id:" +p9.getSettingId());
    p9.setWifiName("Mall_WiFi");
    System.out.println("WiFi:" +p9.getWifiName());
    p9.setBluetooth(true);
    System.out.println("Bluetooth:" +p9.getBluetooth());
    p9.setBrightness(85);
    System.out.println("Brightness:" +p9.getBrightness());
    p9.setMode("Normal");
    System.out.println("Mode:" +p9.getMode());
    p9.setVolume(90);
    System.out.println("Volume:" +p9.getVolume());
    p9.setAirplaneMode(false);
    System.out.println("Airplane:" +p9.getAirplaneMode());

    System.out.println();
    PhoneSettings p10 = new PhoneSettings();
    p10.setSettingId(10);
    System.out.println("Setting Id:" +p10.getSettingId());
    p10.setWifiName("Hotel_WiFi");
    System.out.println("WiFi:" +p10.getWifiName());
    p10.setBluetooth(true);
    System.out.println("Bluetooth:" +p10.getBluetooth());
    p10.setBrightness(65);
    System.out.println("Brightness:" +p10.getBrightness());
    p10.setMode("Vibrate");
    System.out.println("Mode:" +p10.getMode());
    p10.setVolume(50);
    System.out.println("Volume:" +p10.getVolume());
    p10.setAirplaneMode(false);
    System.out.println("Airplane:" +p10.getAirplaneMode());

 }
}