class PlayGroundExecutor {
 public static void main(String[] args){
    System.out.println();
    PlayGround p1 = new PlayGround();
    p1.setGroundId(1);
    System.out.println("Ground Id:" +p1.getGroundId());
    p1.setName("National Stadium");
    System.out.println("Name:" +p1.getName());
    p1.setLocation("Delhi");
    System.out.println("Location:" +p1.getLocation());
    p1.setType("Cricket");
    System.out.println("Type:" +p1.getType());
    p1.setCapacity(50000);
    System.out.println("Capacity:" +p1.getCapacity());
    p1.setIsOpen(true);
    System.out.println("Open:" +p1.getIsOpen());
    p1.setSurface("Grass");
    System.out.println("Surface:" +p1.getSurface());

    System.out.println();
    PlayGround p2 = new PlayGround();
    p2.setGroundId(2);
    System.out.println("Ground Id:" +p2.getGroundId());
    p2.setName("City Sports Arena");
    System.out.println("Name:" +p2.getName());
    p2.setLocation("Mumbai");
    System.out.println("Location:" +p2.getLocation());
    p2.setType("Football");
    System.out.println("Type:" +p2.getType());
    p2.setCapacity(30000);
    System.out.println("Capacity:" +p2.getCapacity());
    p2.setIsOpen(false);
    System.out.println("Open:" +p2.getIsOpen());
    p2.setSurface("Turf");
    System.out.println("Surface:" +p2.getSurface());
	
	System.out.println();
    PlayGround p3 = new PlayGround();
    p3.setGroundId(3);
    System.out.println("Ground Id:" +p3.getGroundId());
    p3.setName("Green Field");
    System.out.println("Name:" +p3.getName());
    p3.setLocation("Bangalore");
    System.out.println("Location:" +p3.getLocation());
    p3.setType("Cricket");
    System.out.println("Type:" +p3.getType());
    p3.setCapacity(25000);
    System.out.println("Capacity:" +p3.getCapacity());
    p3.setIsOpen(true);
    System.out.println("Open:" +p3.getIsOpen());
    p3.setSurface("Grass");
    System.out.println("Surface:" +p3.getSurface());

    System.out.println();
    PlayGround p4 = new PlayGround();
    p4.setGroundId(4);
    System.out.println("Ground Id:" +p4.getGroundId());
    p4.setName("Sunrise Stadium");
    System.out.println("Name:" +p4.getName());
    p4.setLocation("Hyderabad");
    System.out.println("Location:" +p4.getLocation());
    p4.setType("Football");
    System.out.println("Type:" +p4.getType());
    p4.setCapacity(40000);
    System.out.println("Capacity:" +p4.getCapacity());
    p4.setIsOpen(false);
    System.out.println("Open:" +p4.getIsOpen());
    p4.setSurface("Turf");
    System.out.println("Surface:" +p4.getSurface());

    System.out.println();
    PlayGround p5 = new PlayGround();
    p5.setGroundId(5);
    System.out.println("Ground Id:" +p5.getGroundId());
    p5.setName("Victory Arena");
    System.out.println("Name:" +p5.getName());
    p5.setLocation("Chennai");
    System.out.println("Location:" +p5.getLocation());
    p5.setType("Hockey");
    System.out.println("Type:" +p5.getType());
    p5.setCapacity(20000);
    System.out.println("Capacity:" +p5.getCapacity());
    p5.setIsOpen(true);
    System.out.println("Open:" +p5.getIsOpen());
    p5.setSurface("Turf");
    System.out.println("Surface:" +p5.getSurface());

    System.out.println();
    PlayGround p6 = new PlayGround();
    p6.setGroundId(6);
    System.out.println("Ground Id:" +p6.getGroundId());
    p6.setName("Royal Grounds");
    System.out.println("Name:" +p6.getName());
    p6.setLocation("Jaipur");
    System.out.println("Location:" +p6.getLocation());
    p6.setType("Cricket");
    System.out.println("Type:" +p6.getType());
    p6.setCapacity(35000);
    System.out.println("Capacity:" +p6.getCapacity());
    p6.setIsOpen(true);
    System.out.println("Open:" +p6.getIsOpen());
    p6.setSurface("Grass");
    System.out.println("Surface:" +p6.getSurface());

    System.out.println();
    PlayGround p7 = new PlayGround();
    p7.setGroundId(7);
    System.out.println("Ground Id:" +p7.getGroundId());
    p7.setName("Metro Stadium");
    System.out.println("Name:" +p7.getName());
    p7.setLocation("Kolkata");
    System.out.println("Location:" +p7.getLocation());
    p7.setType("Football");
    System.out.println("Type:" +p7.getType());
    p7.setCapacity(60000);
    System.out.println("Capacity:" +p7.getCapacity());
    p7.setIsOpen(false);
    System.out.println("Open:" +p7.getIsOpen());
    p7.setSurface("Grass");
    System.out.println("Surface:" +p7.getSurface());

    System.out.println();
    PlayGround p8 = new PlayGround();
    p8.setGroundId(8);
    System.out.println("Ground Id:" +p8.getGroundId());
    p8.setName("City Ground");
    System.out.println("Name:" +p8.getName());
    p8.setLocation("Pune");
    System.out.println("Location:" +p8.getLocation());
    p8.setType("Basketball");
    System.out.println("Type:" +p8.getType());
    p8.setCapacity(10000);
    System.out.println("Capacity:" +p8.getCapacity());
    p8.setIsOpen(true);
    System.out.println("Open:" +p8.getIsOpen());
    p8.setSurface("Concrete");
    System.out.println("Surface:" +p8.getSurface());

    System.out.println();
    PlayGround p9 = new PlayGround();
    p9.setGroundId(9);
    System.out.println("Ground Id:" +p9.getGroundId());
    p9.setName("Elite Arena");
    System.out.println("Name:" +p9.getName());
    p9.setLocation("Ahmedabad");
    System.out.println("Location:" +p9.getLocation());
    p9.setType("Cricket");
    System.out.println("Type:" +p9.getType());
    p9.setCapacity(70000);
    System.out.println("Capacity:" +p9.getCapacity());
    p9.setIsOpen(true);
    System.out.println("Open:" +p9.getIsOpen());
    p9.setSurface("Grass");
    System.out.println("Surface:" +p9.getSurface());

    System.out.println();
    PlayGround p10 = new PlayGround();
    p10.setGroundId(10);
    System.out.println("Ground Id:" +p10.getGroundId());
    p10.setName("Victory Ground");
    System.out.println("Name:" +p10.getName());
    p10.setLocation("Lucknow");
    System.out.println("Location:" +p10.getLocation());
    p10.setType("Kabaddi");
    System.out.println("Type:" +p10.getType());
    p10.setCapacity(15000);
    System.out.println("Capacity:" +p10.getCapacity());
    p10.setIsOpen(true);
    System.out.println("Open:" +p10.getIsOpen());
    p10.setSurface("Mud");
    System.out.println("Surface:" +p10.getSurface());

 }
}