class PlayerExecutor {
 public static void main(String[] args){

    System.out.println();
    Player p1 = new Player();
    p1.setPlayerId(1);
    System.out.println("Player Id:" +p1.getPlayerId());
    p1.setName("Rohit");
    System.out.println("Name:" +p1.getName());
    p1.setSport("Cricket");
    System.out.println("Sport:" +p1.getSport());
    p1.setAge(35);
    System.out.println("Age:" +p1.getAge());
    p1.setTeam("India");
    System.out.println("Team:" +p1.getTeam());
    p1.setMatchesPlayed(250);
    System.out.println("Matches:" +p1.getMatchesPlayed());
    p1.setScore(10000);
    System.out.println("Score:" +p1.getScore());

    System.out.println();
    Player p2 = new Player();
    p2.setPlayerId(2);
    System.out.println("Player Id:" +p2.getPlayerId());
    p2.setName("Messi");
    System.out.println("Name:" +p2.getName());
    p2.setSport("Football");
    System.out.println("Sport:" +p2.getSport());
    p2.setAge(36);
    System.out.println("Age:" +p2.getAge());
    p2.setTeam("Argentina");
    System.out.println("Team:" +p2.getTeam());
    p2.setMatchesPlayed(800);
    System.out.println("Matches:" +p2.getMatchesPlayed());
    p2.setScore(700);
    System.out.println("Score:" +p2.getScore());
	
	System.out.println();
    Player p3 = new Player();
    p3.setPlayerId(3);
    System.out.println("Player Id:" +p3.getPlayerId());
    p3.setName("Virat");
    System.out.println("Name:" +p3.getName());
    p3.setSport("Cricket");
    System.out.println("Sport:" +p3.getSport());
    p3.setAge(34);
    System.out.println("Age:" +p3.getAge());
    p3.setTeam("India");
    System.out.println("Team:" +p3.getTeam());
    p3.setMatchesPlayed(300);
    System.out.println("Matches:" +p3.getMatchesPlayed());
    p3.setScore(12000);
    System.out.println("Score:" +p3.getScore());

    System.out.println();
    Player p4 = new Player();
    p4.setPlayerId(4);
    System.out.println("Player Id:" +p4.getPlayerId());
    p4.setName("Ronaldo");
    System.out.println("Name:" +p4.getName());
    p4.setSport("Football");
    System.out.println("Sport:" +p4.getSport());
    p4.setAge(38);
    System.out.println("Age:" +p4.getAge());
    p4.setTeam("Portugal");
    System.out.println("Team:" +p4.getTeam());
    p4.setMatchesPlayed(850);
    System.out.println("Matches:" +p4.getMatchesPlayed());
    p4.setScore(750);
    System.out.println("Score:" +p4.getScore());

    System.out.println();
    Player p5 = new Player();
    p5.setPlayerId(5);
    System.out.println("Player Id:" +p5.getPlayerId());
    p5.setName("Dhoni");
    System.out.println("Name:" +p5.getName());
    p5.setSport("Cricket");
    System.out.println("Sport:" +p5.getSport());
    p5.setAge(41);
    System.out.println("Age:" +p5.getAge());
    p5.setTeam("India");
    System.out.println("Team:" +p5.getTeam());
    p5.setMatchesPlayed(350);
    System.out.println("Matches:" +p5.getMatchesPlayed());
    p5.setScore(10000);
    System.out.println("Score:" +p5.getScore());

    System.out.println();
    Player p6 = new Player();
    p6.setPlayerId(6);
    System.out.println("Player Id:" +p6.getPlayerId());
    p6.setName("Neymar");
    System.out.println("Name:" +p6.getName());
    p6.setSport("Football");
    System.out.println("Sport:" +p6.getSport());
    p6.setAge(31);
    System.out.println("Age:" +p6.getAge());
    p6.setTeam("Brazil");
    System.out.println("Team:" +p6.getTeam());
    p6.setMatchesPlayed(600);
    System.out.println("Matches:" +p6.getMatchesPlayed());
    p6.setScore(400);
    System.out.println("Score:" +p6.getScore());

    System.out.println();
    Player p7 = new Player();
    p7.setPlayerId(7);
    System.out.println("Player Id:" +p7.getPlayerId());
    p7.setName("Hardik");
    System.out.println("Name:" +p7.getName());
    p7.setSport("Cricket");
    System.out.println("Sport:" +p7.getSport());
    p7.setAge(30);
    System.out.println("Age:" +p7.getAge());
    p7.setTeam("India");
    System.out.println("Team:" +p7.getTeam());
    p7.setMatchesPlayed(150);
    System.out.println("Matches:" +p7.getMatchesPlayed());
    p7.setScore(3000);
    System.out.println("Score:" +p7.getScore());

    System.out.println();
    Player p8 = new Player();
    p8.setPlayerId(8);
    System.out.println("Player Id:" +p8.getPlayerId());
    p8.setName("Mbappe");
    System.out.println("Name:" +p8.getName());
    p8.setSport("Football");
    System.out.println("Sport:" +p8.getSport());
    p8.setAge(25);
    System.out.println("Age:" +p8.getAge());
    p8.setTeam("France");
    System.out.println("Team:" +p8.getTeam());
    p8.setMatchesPlayed(300);
    System.out.println("Matches:" +p8.getMatchesPlayed());
    p8.setScore(250);
    System.out.println("Score:" +p8.getScore());

    System.out.println();
    Player p9 = new Player();
    p9.setPlayerId(9);
    System.out.println("Player Id:" +p9.getPlayerId());
    p9.setName("Bumrah");
    System.out.println("Name:" +p9.getName());
    p9.setSport("Cricket");
    System.out.println("Sport:" +p9.getSport());
    p9.setAge(29);
    System.out.println("Age:" +p9.getAge());
    p9.setTeam("India");
    System.out.println("Team:" +p9.getTeam());
    p9.setMatchesPlayed(120);
    System.out.println("Matches:" +p9.getMatchesPlayed());
    p9.setScore(500);
    System.out.println("Score:" +p9.getScore());

    System.out.println();
    Player p10 = new Player();
    p10.setPlayerId(10);
    System.out.println("Player Id:" +p10.getPlayerId());
    p10.setName("Federer");
    System.out.println("Name:" +p10.getName());
    p10.setSport("Tennis");
    System.out.println("Sport:" +p10.getSport());
    p10.setAge(41);
    System.out.println("Age:" +p10.getAge());
    p10.setTeam("Switzerland");
    System.out.println("Team:" +p10.getTeam());
    p10.setMatchesPlayed(1500);
    System.out.println("Matches:" +p10.getMatchesPlayed());
    p10.setScore(1200);
    System.out.println("Score:" +p10.getScore());
	
	    System.out.println();
    Player p11 = new Player();
    p11.setPlayerId(11);
    System.out.println("Player Id:" +p11.getPlayerId());
    p11.setName("Kane");
    System.out.println("Name:" +p11.getName());
    p11.setSport("Cricket");
    System.out.println("Sport:" +p11.getSport());
    p11.setAge(33);
    System.out.println("Age:" +p11.getAge());
    p11.setTeam("New Zealand");
    System.out.println("Team:" +p11.getTeam());
    p11.setMatchesPlayed(280);
    System.out.println("Matches:" +p11.getMatchesPlayed());
    p11.setScore(9000);
    System.out.println("Score:" +p11.getScore());

    System.out.println();
    Player p12 = new Player();
    p12.setPlayerId(12);
    System.out.println("Player Id:" +p12.getPlayerId());
    p12.setName("Smith");
    System.out.println("Name:" +p12.getName());
    p12.setSport("Cricket");
    System.out.println("Sport:" +p12.getSport());
    p12.setAge(34);
    System.out.println("Age:" +p12.getAge());
    p12.setTeam("Australia");
    System.out.println("Team:" +p12.getTeam());
    p12.setMatchesPlayed(260);
    System.out.println("Matches:" +p12.getMatchesPlayed());
    p12.setScore(9500);
    System.out.println("Score:" +p12.getScore());

    System.out.println();
    Player p13 = new Player();
    p13.setPlayerId(13);
    System.out.println("Player Id:" +p13.getPlayerId());
    p13.setName("Alcaraz");
    System.out.println("Name:" +p13.getName());
    p13.setSport("Tennis");
    System.out.println("Sport:" +p13.getSport());
    p13.setAge(21);
    System.out.println("Age:" +p13.getAge());
    p13.setTeam("Spain");
    System.out.println("Team:" +p13.getTeam());
    p13.setMatchesPlayed(200);
    System.out.println("Matches:" +p13.getMatchesPlayed());
    p13.setScore(150);
    System.out.println("Score:" +p13.getScore());

    System.out.println();
    Player p14 = new Player();
    p14.setPlayerId(14);
    System.out.println("Player Id:" +p14.getPlayerId());
    p14.setName("Nadal");
    System.out.println("Name:" +p14.getName());
    p14.setSport("Tennis");
    System.out.println("Sport:" +p14.getSport());
    p14.setAge(37);
    System.out.println("Age:" +p14.getAge());
    p14.setTeam("Spain");
    System.out.println("Team:" +p14.getTeam());
    p14.setMatchesPlayed(1300);
    System.out.println("Matches:" +p14.getMatchesPlayed());
    p14.setScore(1100);
    System.out.println("Score:" +p14.getScore());

    System.out.println();
    Player p15 = new Player();
    p15.setPlayerId(15);
    System.out.println("Player Id:" +p15.getPlayerId());
    p15.setName("LeBron");
    System.out.println("Name:" +p15.getName());
    p15.setSport("Basketball");
    System.out.println("Sport:" +p15.getSport());
    p15.setAge(39);
    System.out.println("Age:" +p15.getAge());
    p15.setTeam("USA");
    System.out.println("Team:" +p15.getTeam());
    p15.setMatchesPlayed(1400);
    System.out.println("Matches:" +p15.getMatchesPlayed());
    p15.setScore(38000);
    System.out.println("Score:" +p15.getScore());

    System.out.println();
    Player p16 = new Player();
    p16.setPlayerId(16);
    System.out.println("Player Id:" +p16.getPlayerId());
    p16.setName("Curry");
    System.out.println("Name:" +p16.getName());
    p16.setSport("Basketball");
    System.out.println("Sport:" +p16.getSport());
    p16.setAge(36);
    System.out.println("Age:" +p16.getAge());
    p16.setTeam("USA");
    System.out.println("Team:" +p16.getTeam());
    p16.setMatchesPlayed(900);
    System.out.println("Matches:" +p16.getMatchesPlayed());
    p16.setScore(20000);
    System.out.println("Score:" +p16.getScore());

    System.out.println();
    Player p17 = new Player();
    p17.setPlayerId(17);
    System.out.println("Player Id:" +p17.getPlayerId());
    p17.setName("Jordan");
    System.out.println("Name:" +p17.getName());
    p17.setSport("Basketball");
    System.out.println("Sport:" +p17.getSport());
    p17.setAge(60);
    System.out.println("Age:" +p17.getAge());
    p17.setTeam("USA");
    System.out.println("Team:" +p17.getTeam());
    p17.setMatchesPlayed(1000);
    System.out.println("Matches:" +p17.getMatchesPlayed());
    p17.setScore(32000);
    System.out.println("Score:" +p17.getScore());

    System.out.println();
    Player p18 = new Player();
    p18.setPlayerId(18);
    System.out.println("Player Id:" +p18.getPlayerId());
    p18.setName("Bolt");
    System.out.println("Name:" +p18.getName());
    p18.setSport("Athletics");
    System.out.println("Sport:" +p18.getSport());
    p18.setAge(37);
    System.out.println("Age:" +p18.getAge());
    p18.setTeam("Jamaica");
    System.out.println("Team:" +p18.getTeam());
    p18.setMatchesPlayed(200);
    System.out.println("Matches:" +p18.getMatchesPlayed());
    p18.setScore(100);
    System.out.println("Score:" +p18.getScore());

    System.out.println();
    Player p19 = new Player();
    p19.setPlayerId(19);
    System.out.println("Player Id:" +p19.getPlayerId());
    p19.setName("Sindhu");
    System.out.println("Name:" +p19.getName());
    p19.setSport("Badminton");
    System.out.println("Sport:" +p19.getSport());
    p19.setAge(29);
    System.out.println("Age:" +p19.getAge());
    p19.setTeam("India");
    System.out.println("Team:" +p19.getTeam());
    p19.setMatchesPlayed(400);
    System.out.println("Matches:" +p19.getMatchesPlayed());
    p19.setScore(300);
    System.out.println("Score:" +p19.getScore());

    System.out.println();
    Player p20 = new Player();
    p20.setPlayerId(20);
    System.out.println("Player Id:" +p20.getPlayerId());
    p20.setName("Magnus");
    System.out.println("Name:" +p20.getName());
    p20.setSport("Chess");
    System.out.println("Sport:" +p20.getSport());
    p20.setAge(33);
    System.out.println("Age:" +p20.getAge());
    p20.setTeam("Norway");
    System.out.println("Team:" +p20.getTeam());
    p20.setMatchesPlayed(500);
    System.out.println("Matches:" +p20.getMatchesPlayed());
    p20.setScore(450);
    System.out.println("Score:" +p20.getScore());
	
	    System.out.println();
    Player p21 = new Player();
    p21.setPlayerId(21);
    System.out.println("Player Id:" +p21.getPlayerId());
    p21.setName("Gill");
    System.out.println("Name:" +p21.getName());
    p21.setSport("Cricket");
    System.out.println("Sport:" +p21.getSport());
    p21.setAge(24);
    System.out.println("Age:" +p21.getAge());
    p21.setTeam("India");
    System.out.println("Team:" +p21.getTeam());
    p21.setMatchesPlayed(80);
    System.out.println("Matches:" +p21.getMatchesPlayed());
    p21.setScore(2500);
    System.out.println("Score:" +p21.getScore());

    System.out.println();
    Player p22 = new Player();
    p22.setPlayerId(22);
    System.out.println("Player Id:" +p22.getPlayerId());
    p22.setName("Buttler");
    System.out.println("Name:" +p22.getName());
    p22.setSport("Cricket");
    System.out.println("Sport:" +p22.getSport());
    p22.setAge(33);
    System.out.println("Age:" +p22.getAge());
    p22.setTeam("England");
    System.out.println("Team:" +p22.getTeam());
    p22.setMatchesPlayed(200);
    System.out.println("Matches:" +p22.getMatchesPlayed());
    p22.setScore(6000);
    System.out.println("Score:" +p22.getScore());

    System.out.println();
    Player p23 = new Player();
    p23.setPlayerId(23);
    System.out.println("Player Id:" +p23.getPlayerId());
    p23.setName("Shaq");
    System.out.println("Name:" +p23.getName());
    p23.setSport("Basketball");
    System.out.println("Sport:" +p23.getSport());
    p23.setAge(52);
    System.out.println("Age:" +p23.getAge());
    p23.setTeam("USA");
    System.out.println("Team:" +p23.getTeam());
    p23.setMatchesPlayed(1200);
    System.out.println("Matches:" +p23.getMatchesPlayed());
    p23.setScore(28000);
    System.out.println("Score:" +p23.getScore());

    System.out.println();
    Player p24 = new Player();
    p24.setPlayerId(24);
    System.out.println("Player Id:" +p24.getPlayerId());
    p24.setName("Djokovic");
    System.out.println("Name:" +p24.getName());
    p24.setSport("Tennis");
    System.out.println("Sport:" +p24.getSport());
    p24.setAge(36);
    System.out.println("Age:" +p24.getAge());
    p24.setTeam("Serbia");
    System.out.println("Team:" +p24.getTeam());
    p24.setMatchesPlayed(1400);
    System.out.println("Matches:" +p24.getMatchesPlayed());
    p24.setScore(1150);
    System.out.println("Score:" +p24.getScore());

    System.out.println();
    Player p25 = new Player();
    p25.setPlayerId(25);
    System.out.println("Player Id:" +p25.getPlayerId());
    p25.setName("Kohli Jr");
    System.out.println("Name:" +p25.getName());
    p25.setSport("Cricket");
    System.out.println("Sport:" +p25.getSport());
    p25.setAge(20);
    System.out.println("Age:" +p25.getAge());
    p25.setTeam("India");
    System.out.println("Team:" +p25.getTeam());
    p25.setMatchesPlayed(20);
    System.out.println("Matches:" +p25.getMatchesPlayed());
    p25.setScore(800);
    System.out.println("Score:" +p25.getScore());

    System.out.println();
    Player p26 = new Player();
    p26.setPlayerId(26);
    System.out.println("Player Id:" +p26.getPlayerId());
    p26.setName("Haaland");
    System.out.println("Name:" +p26.getName());
    p26.setSport("Football");
    System.out.println("Sport:" +p26.getSport());
    p26.setAge(24);
    System.out.println("Age:" +p26.getAge());
    p26.setTeam("Norway");
    System.out.println("Team:" +p26.getTeam());
    p26.setMatchesPlayed(250);
    System.out.println("Matches:" +p26.getMatchesPlayed());
    p26.setScore(200);
    System.out.println("Score:" +p26.getScore());

    System.out.println();
    Player p27 = new Player();
    p27.setPlayerId(27);
    System.out.println("Player Id:" +p27.getPlayerId());
    p27.setName("Rashid");
    System.out.println("Name:" +p27.getName());
    p27.setSport("Cricket");
    System.out.println("Sport:" +p27.getSport());
    p27.setAge(26);
    System.out.println("Age:" +p27.getAge());
    p27.setTeam("Afghanistan");
    System.out.println("Team:" +p27.getTeam());
    p27.setMatchesPlayed(180);
    System.out.println("Matches:" +p27.getMatchesPlayed());
    p27.setScore(1200);
    System.out.println("Score:" +p27.getScore());

    System.out.println();
    Player p28 = new Player();
    p28.setPlayerId(28);
    System.out.println("Player Id:" +p28.getPlayerId());
    p28.setName("Sunil");
    System.out.println("Name:" +p28.getName());
    p28.setSport("Football");
    System.out.println("Sport:" +p28.getSport());
    p28.setAge(39);
    System.out.println("Age:" +p28.getAge());
    p28.setTeam("India");
    System.out.println("Team:" +p28.getTeam());
    p28.setMatchesPlayed(300);
    System.out.println("Matches:" +p28.getMatchesPlayed());
    p28.setScore(150);
    System.out.println("Score:" +p28.getScore());

    System.out.println();
    Player p29 = new Player();
    p29.setPlayerId(29);
    System.out.println("Player Id:" +p29.getPlayerId());
    p29.setName("Anand");
    System.out.println("Name:" +p29.getName());
    p29.setSport("Chess");
    System.out.println("Sport:" +p29.getSport());
    p29.setAge(54);
    System.out.println("Age:" +p29.getAge());
    p29.setTeam("India");
    System.out.println("Team:" +p29.getTeam());
    p29.setMatchesPlayed(600);
    System.out.println("Matches:" +p29.getMatchesPlayed());
    p29.setScore(500);
    System.out.println("Score:" +p29.getScore());

 }
}