class PostMortemReportExecutor {
 public static void main(String[] args){
    System.out.println();
    PostMortemReport p1 = new PostMortemReport();
    p1.setReportId(1);
    System.out.println("Report Id:" +p1.getReportId());
    p1.setPatientName("Ravi");
    System.out.println("Patient:" +p1.getPatientName());
    p1.setCauseOfDeath("Accident");
    System.out.println("Cause:" +p1.getCauseOfDeath());
    p1.setDoctorName("Dr. Kumar");
    System.out.println("Doctor:" +p1.getDoctorName());
    p1.setHospital("City Hospital");
    System.out.println("Hospital:" +p1.getHospital());
    p1.setDate("01-04-2026");
    System.out.println("Date:" +p1.getDate());
    p1.setIsCompleted(true);
    System.out.println("Completed:" +p1.getIsCompleted());

    System.out.println();
    PostMortemReport p2 = new PostMortemReport();
    p2.setReportId(2);
    System.out.println("Report Id:" +p2.getReportId());
    p2.setPatientName("Sneha");
    System.out.println("Patient:" +p2.getPatientName());
    p2.setCauseOfDeath("Heart Attack");
    System.out.println("Cause:" +p2.getCauseOfDeath());
    p2.setDoctorName("Dr. Meena");
    System.out.println("Doctor:" +p2.getDoctorName());
    p2.setHospital("Apollo Hospital");
    System.out.println("Hospital:" +p2.getHospital());
    p2.setDate("02-04-2026");
    System.out.println("Date:" +p2.getDate());
    p2.setIsCompleted(true);
    System.out.println("Completed:" +p2.getIsCompleted());
	
	System.out.println();
    PostMortemReport p3 = new PostMortemReport();
    p3.setReportId(3);
    System.out.println("Report Id:" +p3.getReportId());
    p3.setPatientName("Arjun");
    System.out.println("Patient:" +p3.getPatientName());
    p3.setCauseOfDeath("Poison");
    System.out.println("Cause:" +p3.getCauseOfDeath());
    p3.setDoctorName("Dr. Suresh");
    System.out.println("Doctor:" +p3.getDoctorName());
    p3.setHospital("Global Hospital");
    System.out.println("Hospital:" +p3.getHospital());
    p3.setDate("03-04-2026");
    System.out.println("Date:" +p3.getDate());
    p3.setIsCompleted(true);
    System.out.println("Completed:" +p3.getIsCompleted());

    System.out.println();
    PostMortemReport p4 = new PostMortemReport();
    p4.setReportId(4);
    System.out.println("Report Id:" +p4.getReportId());
    p4.setPatientName("Meena");
    System.out.println("Patient:" +p4.getPatientName());
    p4.setCauseOfDeath("Drowning");
    System.out.println("Cause:" +p4.getCauseOfDeath());
    p4.setDoctorName("Dr. Anil");
    System.out.println("Doctor:" +p4.getDoctorName());
    p4.setHospital("Sunrise Hospital");
    System.out.println("Hospital:" +p4.getHospital());
    p4.setDate("04-04-2026");
    System.out.println("Date:" +p4.getDate());
    p4.setIsCompleted(false);
    System.out.println("Completed:" +p4.getIsCompleted());

    System.out.println();
    PostMortemReport p5 = new PostMortemReport();
    p5.setReportId(5);
    System.out.println("Report Id:" +p5.getReportId());
    p5.setPatientName("Rahul");
    System.out.println("Patient:" +p5.getPatientName());
    p5.setCauseOfDeath("Burn Injury");
    System.out.println("Cause:" +p5.getCauseOfDeath());
    p5.setDoctorName("Dr. Kiran");
    System.out.println("Doctor:" +p5.getDoctorName());
    p5.setHospital("Care Hospital");
    System.out.println("Hospital:" +p5.getHospital());
    p5.setDate("05-04-2026");
    System.out.println("Date:" +p5.getDate());
    p5.setIsCompleted(true);
    System.out.println("Completed:" +p5.getIsCompleted());

    System.out.println();
    PostMortemReport p6 = new PostMortemReport();
    p6.setReportId(6);
    System.out.println("Report Id:" +p6.getReportId());
    p6.setPatientName("Anjali");
    System.out.println("Patient:" +p6.getPatientName());
    p6.setCauseOfDeath("Suicide");
    System.out.println("Cause:" +p6.getCauseOfDeath());
    p6.setDoctorName("Dr. Deepa");
    System.out.println("Doctor:" +p6.getDoctorName());
    p6.setHospital("Metro Hospital");
    System.out.println("Hospital:" +p6.getHospital());
    p6.setDate("06-04-2026");
    System.out.println("Date:" +p6.getDate());
    p6.setIsCompleted(false);
    System.out.println("Completed:" +p6.getIsCompleted());

    System.out.println();
    PostMortemReport p7 = new PostMortemReport();
    p7.setReportId(7);
    System.out.println("Report Id:" +p7.getReportId());
    p7.setPatientName("Vijay");
    System.out.println("Patient:" +p7.getPatientName());
    p7.setCauseOfDeath("Stroke");
    System.out.println("Cause:" +p7.getCauseOfDeath());
    p7.setDoctorName("Dr. Kumar");
    System.out.println("Doctor:" +p7.getDoctorName());
    p7.setHospital("City Hospital");
    System.out.println("Hospital:" +p7.getHospital());
    p7.setDate("07-04-2026");
    System.out.println("Date:" +p7.getDate());
    p7.setIsCompleted(true);
    System.out.println("Completed:" +p7.getIsCompleted());

    System.out.println();
    PostMortemReport p8 = new PostMortemReport();
    p8.setReportId(8);
    System.out.println("Report Id:" +p8.getReportId());
    p8.setPatientName("Lakshmi");
    System.out.println("Patient:" +p8.getPatientName());
    p8.setCauseOfDeath("Cancer");
    System.out.println("Cause:" +p8.getCauseOfDeath());
    p8.setDoctorName("Dr. Ramesh");
    System.out.println("Doctor:" +p8.getDoctorName());
    p8.setHospital("Apollo Hospital");
    System.out.println("Hospital:" +p8.getHospital());
    p8.setDate("08-04-2026");
    System.out.println("Date:" +p8.getDate());
    p8.setIsCompleted(true);
    System.out.println("Completed:" +p8.getIsCompleted());

    System.out.println();
    PostMortemReport p9 = new PostMortemReport();
    p9.setReportId(9);
    System.out.println("Report Id:" +p9.getReportId());
    p9.setPatientName("Karthik");
    System.out.println("Patient:" +p9.getPatientName());
    p9.setCauseOfDeath("Accident");
    System.out.println("Cause:" +p9.getCauseOfDeath());
    p9.setDoctorName("Dr. Sandeep");
    System.out.println("Doctor:" +p9.getDoctorName());
    p9.setHospital("Global Hospital");
    System.out.println("Hospital:" +p9.getHospital());
    p9.setDate("09-04-2026");
    System.out.println("Date:" +p9.getDate());
    p9.setIsCompleted(false);
    System.out.println("Completed:" +p9.getIsCompleted());

    System.out.println();
    PostMortemReport p10 = new PostMortemReport();
    p10.setReportId(10);
    System.out.println("Report Id:" +p10.getReportId());
    p10.setPatientName("Sandeep");
    System.out.println("Patient:" +p10.getPatientName());
    p10.setCauseOfDeath("Heart Failure");
    System.out.println("Cause:" +p10.getCauseOfDeath());
    p10.setDoctorName("Dr. Arun");
    System.out.println("Doctor:" +p10.getDoctorName());
    p10.setHospital("Care Hospital");
    System.out.println("Hospital:" +p10.getHospital());
    p10.setDate("10-04-2026");
    System.out.println("Date:" +p10.getDate());
    p10.setIsCompleted(true);
    System.out.println("Completed:" +p10.getIsCompleted());

 }
}