class SubscriptionDetailsExecutor {
 public static void main(String[] args){
    SubscriptionDetails s1 = new SubscriptionDetails();
    s1.setSubscriptionId(1);
    System.out.println("Subscription Id:" +s1.getSubscriptionId());
    s1.setPlanName("Basic Plan");
    System.out.println("Plan:" +s1.getPlanName());
    s1.setPrice(199);
    System.out.println("Price:" +s1.getPrice());
    s1.setDuration(30);
    System.out.println("Duration:" +s1.getDuration());
    s1.setStartDate("01-01-2026");
    System.out.println("Start Date:" +s1.getStartDate());
    s1.setEndDate("30-01-2026");
    System.out.println("End Date:" +s1.getEndDate());
    s1.setStatus("Active");
    System.out.println("Status:" +s1.getStatus());


    System.out.println();
    SubscriptionDetails s2 = new SubscriptionDetails();
    s2.setSubscriptionId(2);
    System.out.println("Subscription Id:" +s2.getSubscriptionId());
    s2.setPlanName("Premium Plan");
    System.out.println("Plan:" +s2.getPlanName());
    s2.setPrice(499);
    System.out.println("Price:" +s2.getPrice());
    s2.setDuration(90);
    System.out.println("Duration:" +s2.getDuration());
    s2.setStartDate("05-01-2026");
    System.out.println("Start Date:" +s2.getStartDate());
    s2.setEndDate("05-04-2026");
    System.out.println("End Date:" +s2.getEndDate());
    s2.setStatus("Active");
    System.out.println("Status:" +s2.getStatus());
	
	System.out.println();
    SubscriptionDetails s3 = new SubscriptionDetails();
    s3.setSubscriptionId(3);
    System.out.println("Subscription Id:" +s3.getSubscriptionId());
    s3.setPlanName("Gold Plan");
    System.out.println("Plan:" +s3.getPlanName());
    s3.setPrice(799);
    System.out.println("Price:" +s3.getPrice());
    s3.setDuration(180);
    System.out.println("Duration:" +s3.getDuration());
    s3.setStartDate("10-01-2026");
    System.out.println("Start Date:" +s3.getStartDate());
    s3.setEndDate("10-07-2026");
    System.out.println("End Date:" +s3.getEndDate());
    s3.setStatus("Active");
    System.out.println("Status:" +s3.getStatus());

    System.out.println();
    SubscriptionDetails s4 = new SubscriptionDetails();
    s4.setSubscriptionId(4);
    System.out.println("Subscription Id:" +s4.getSubscriptionId());
    s4.setPlanName("Silver Plan");
    System.out.println("Plan:" +s4.getPlanName());
    s4.setPrice(299);
    System.out.println("Price:" +s4.getPrice());
    s4.setDuration(60);
    System.out.println("Duration:" +s4.getDuration());
    s4.setStartDate("12-01-2026");
    System.out.println("Start Date:" +s4.getStartDate());
    s4.setEndDate("12-03-2026");
    System.out.println("End Date:" +s4.getEndDate());
    s4.setStatus("Expired");
    System.out.println("Status:" +s4.getStatus());

    System.out.println();
    SubscriptionDetails s5 = new SubscriptionDetails();
    s5.setSubscriptionId(5);
    System.out.println("Subscription Id:" +s5.getSubscriptionId());
    s5.setPlanName("Student Plan");
    System.out.println("Plan:" +s5.getPlanName());
    s5.setPrice(99);
    System.out.println("Price:" +s5.getPrice());
    s5.setDuration(30);
    System.out.println("Duration:" +s5.getDuration());
    s5.setStartDate("15-01-2026");
    System.out.println("Start Date:" +s5.getStartDate());
    s5.setEndDate("14-02-2026");
    System.out.println("End Date:" +s5.getEndDate());
    s5.setStatus("Active");
    System.out.println("Status:" +s5.getStatus());

    System.out.println();
    SubscriptionDetails s6 = new SubscriptionDetails();
    s6.setSubscriptionId(6);
    System.out.println("Subscription Id:" +s6.getSubscriptionId());
    s6.setPlanName("Family Plan");
    System.out.println("Plan:" +s6.getPlanName());
    s6.setPrice(999);
    System.out.println("Price:" +s6.getPrice());
    s6.setDuration(365);
    System.out.println("Duration:" +s6.getDuration());
    s6.setStartDate("18-01-2026");
    System.out.println("Start Date:" +s6.getStartDate());
    s6.setEndDate("18-01-2027");
    System.out.println("End Date:" +s6.getEndDate());
    s6.setStatus("Active");
    System.out.println("Status:" +s6.getStatus());

    System.out.println();
    SubscriptionDetails s7 = new SubscriptionDetails();
    s7.setSubscriptionId(7);
    System.out.println("Subscription Id:" +s7.getSubscriptionId());
    s7.setPlanName("Trial Plan");
    System.out.println("Plan:" +s7.getPlanName());
    s7.setPrice(0);
    System.out.println("Price:" +s7.getPrice());
    s7.setDuration(7);
    System.out.println("Duration:" +s7.getDuration());
    s7.setStartDate("20-01-2026");
    System.out.println("Start Date:" +s7.getStartDate());
    s7.setEndDate("27-01-2026");
    System.out.println("End Date:" +s7.getEndDate());
    s7.setStatus("Expired");
    System.out.println("Status:" +s7.getStatus());

    System.out.println();
    SubscriptionDetails s8 = new SubscriptionDetails();
    s8.setSubscriptionId(8);
    System.out.println("Subscription Id:" +s8.getSubscriptionId());
    s8.setPlanName("Pro Plan");
    System.out.println("Plan:" +s8.getPlanName());
    s8.setPrice(1299);
    System.out.println("Price:" +s8.getPrice());
    s8.setDuration(365);
    System.out.println("Duration:" +s8.getDuration());
    s8.setStartDate("22-01-2026");
    System.out.println("Start Date:" +s8.getStartDate());
    s8.setEndDate("22-01-2027");
    System.out.println("End Date:" +s8.getEndDate());
    s8.setStatus("Active");
    System.out.println("Status:" +s8.getStatus());

    System.out.println();
    SubscriptionDetails s9 = new SubscriptionDetails();
    s9.setSubscriptionId(9);
    System.out.println("Subscription Id:" +s9.getSubscriptionId());
    s9.setPlanName("Enterprise Plan");
    System.out.println("Plan:" +s9.getPlanName());
    s9.setPrice(5000);
    System.out.println("Price:" +s9.getPrice());
    s9.setDuration(365);
    System.out.println("Duration:" +s9.getDuration());
    s9.setStartDate("25-01-2026");
    System.out.println("Start Date:" +s9.getStartDate());
    s9.setEndDate("25-01-2027");
    System.out.println("End Date:" +s9.getEndDate());
    s9.setStatus("Active");
    System.out.println("Status:" +s9.getStatus());

    System.out.println();
    SubscriptionDetails s10 = new SubscriptionDetails();
    s10.setSubscriptionId(10);
    System.out.println("Subscription Id:" +s10.getSubscriptionId());
    s10.setPlanName("Monthly Plan");
    System.out.println("Plan:" +s10.getPlanName());
    s10.setPrice(199);
    System.out.println("Price:" +s10.getPrice());
    s10.setDuration(30);
    System.out.println("Duration:" +s10.getDuration());
    s10.setStartDate("28-01-2026");
    System.out.println("Start Date:" +s10.getStartDate());
    s10.setEndDate("28-02-2026");
    System.out.println("End Date:" +s10.getEndDate());
    s10.setStatus("Active");
    System.out.println("Status:" +s10.getStatus());
	
	System.out.println();
    SubscriptionDetails s11 = new SubscriptionDetails();
    s11.setSubscriptionId(11);
    System.out.println("Subscription Id:" +s11.getSubscriptionId());
    s11.setPlanName("Annual Plan");
    System.out.println("Plan:" +s11.getPlanName());
    s11.setPrice(1999);
    System.out.println("Price:" +s11.getPrice());
    s11.setDuration(365);
    System.out.println("Duration:" +s11.getDuration());
    s11.setStartDate("01-02-2026");
    System.out.println("Start Date:" +s11.getStartDate());
    s11.setEndDate("01-02-2027");
    System.out.println("End Date:" +s11.getEndDate());
    s11.setStatus("Active");
    System.out.println("Status:" +s11.getStatus());

    System.out.println();
    SubscriptionDetails s12 = new SubscriptionDetails();
    s12.setSubscriptionId(12);
    System.out.println("Subscription Id:" +s12.getSubscriptionId());
    s12.setPlanName("Basic Plus");
    System.out.println("Plan:" +s12.getPlanName());
    s12.setPrice(249);
    System.out.println("Price:" +s12.getPrice());
    s12.setDuration(30);
    System.out.println("Duration:" +s12.getDuration());
    s12.setStartDate("03-02-2026");
    System.out.println("Start Date:" +s12.getStartDate());
    s12.setEndDate("03-03-2026");
    System.out.println("End Date:" +s12.getEndDate());
    s12.setStatus("Active");
    System.out.println("Status:" +s12.getStatus());

    System.out.println();
    SubscriptionDetails s13 = new SubscriptionDetails();
    s13.setSubscriptionId(13);
    System.out.println("Subscription Id:" +s13.getSubscriptionId());
    s13.setPlanName("Premium Plus");
    System.out.println("Plan:" +s13.getPlanName());
    s13.setPrice(599);
    System.out.println("Price:" +s13.getPrice());
    s13.setDuration(90);
    System.out.println("Duration:" +s13.getDuration());
    s13.setStartDate("05-02-2026");
    System.out.println("Start Date:" +s13.getStartDate());
    s13.setEndDate("05-05-2026");
    System.out.println("End Date:" +s13.getEndDate());
    s13.setStatus("Active");
    System.out.println("Status:" +s13.getStatus());

    System.out.println();
    SubscriptionDetails s14 = new SubscriptionDetails();
    s14.setSubscriptionId(14);
    System.out.println("Subscription Id:" +s14.getSubscriptionId());
    s14.setPlanName("Lite Plan");
    System.out.println("Plan:" +s14.getPlanName());
    s14.setPrice(149);
    System.out.println("Price:" +s14.getPrice());
    s14.setDuration(30);
    System.out.println("Duration:" +s14.getDuration());
    s14.setStartDate("07-02-2026");
    System.out.println("Start Date:" +s14.getStartDate());
    s14.setEndDate("07-03-2026");
    s14.setStatus("Expired");
    System.out.println("Status:" +s14.getStatus());

    System.out.println();
    SubscriptionDetails s15 = new SubscriptionDetails();
    s15.setSubscriptionId(15);
    System.out.println("Subscription Id:" +s15.getSubscriptionId());
    s15.setPlanName("Business Plan");
    System.out.println("Plan:" +s15.getPlanName());
    s15.setPrice(2500);
    System.out.println("Price:" +s15.getPrice());
    s15.setDuration(365);
    System.out.println("Duration:" +s15.getDuration());
    s15.setStartDate("10-02-2026");
    System.out.println("Start Date:" +s15.getStartDate());
    s15.setEndDate("10-02-2027");
    System.out.println("End Date:" +s15.getEndDate());
    s15.setStatus("Active");
    System.out.println("Status:" +s15.getStatus());

    System.out.println();
    SubscriptionDetails s16 = new SubscriptionDetails();
    s16.setSubscriptionId(16);
    System.out.println("Subscription Id:" +s16.getSubscriptionId());
    s16.setPlanName("Startup Plan");
    System.out.println("Plan:" +s16.getPlanName());
    s16.setPrice(799);
    System.out.println("Price:" +s16.getPrice());
    s16.setDuration(180);
    System.out.println("Duration:" +s16.getDuration());
    s16.setStartDate("12-02-2026");
    System.out.println("Start Date:" +s16.getStartDate());
    s16.setEndDate("12-08-2026");
    System.out.println("End Date:" +s16.getEndDate());
    s16.setStatus("Active");
    System.out.println("Status:" +s16.getStatus());

    System.out.println();
    SubscriptionDetails s17 = new SubscriptionDetails();
    s17.setSubscriptionId(17);
    System.out.println("Subscription Id:" +s17.getSubscriptionId());
    s17.setPlanName("Weekend Plan");
    System.out.println("Plan:" +s17.getPlanName());
    s17.setPrice(49);
    System.out.println("Price:" +s17.getPrice());
    s17.setDuration(7);
    System.out.println("Duration:" +s17.getDuration());
    s17.setStartDate("14-02-2026");
    System.out.println("Start Date:" +s17.getStartDate());
    s17.setEndDate("21-02-2026");
    System.out.println("End Date:" +s17.getEndDate());
    s17.setStatus("Expired");
    System.out.println("Status:" +s17.getStatus());

    System.out.println();
    SubscriptionDetails s18 = new SubscriptionDetails();
    s18.setSubscriptionId(18);
    System.out.println("Subscription Id:" +s18.getSubscriptionId());
    s18.setPlanName("Half Year Plan");
    System.out.println("Plan:" +s18.getPlanName());
    s18.setPrice(999);
    System.out.println("Price:" +s18.getPrice());
    s18.setDuration(180);
    System.out.println("Duration:" +s18.getDuration());
    s18.setStartDate("16-02-2026");
    System.out.println("Start Date:" +s18.getStartDate());
    s18.setEndDate("16-08-2026");
    System.out.println("End Date:" +s18.getEndDate());
    s18.setStatus("Active");
    System.out.println("Status:" +s18.getStatus());

    System.out.println();
    SubscriptionDetails s19 = new SubscriptionDetails();
    s19.setSubscriptionId(19);
    System.out.println("Subscription Id:" +s19.getSubscriptionId());
    s19.setPlanName("Mini Plan");
    System.out.println("Plan:" +s19.getPlanName());
    s19.setPrice(79);
    System.out.println("Price:" +s19.getPrice());
    s19.setDuration(15);
    System.out.println("Duration:" +s19.getDuration());
    s19.setStartDate("18-02-2026");
    System.out.println("Start Date:" +s19.getStartDate());
    s19.setEndDate("05-03-2026");
    System.out.println("End Date:" +s19.getEndDate());
    s19.setStatus("Expired");
    System.out.println("Status:" +s19.getStatus());

    System.out.println();
    SubscriptionDetails s20 = new SubscriptionDetails();
    s20.setSubscriptionId(20);
    System.out.println("Subscription Id:" +s20.getSubscriptionId());
    s20.setPlanName("Ultimate Plan");
    System.out.println("Plan:" +s20.getPlanName());
    s20.setPrice(9999);
    System.out.println("Price:" +s20.getPrice());
    s20.setDuration(365);
    System.out.println("Duration:" +s20.getDuration());
    s20.setStartDate("20-02-2026");
    System.out.println("Start Date:" +s20.getStartDate());
    s20.setEndDate("20-02-2027");
    System.out.println("End Date:" +s20.getEndDate());
    s20.setStatus("Active");
    System.out.println("Status:" +s20.getStatus());

	System.out.println();
    SubscriptionDetails s21 = new SubscriptionDetails();
    s21.setSubscriptionId(21);
    System.out.println("Subscription Id:" +s21.getSubscriptionId());
    s21.setPlanName("Starter Plan");
    System.out.println("Plan:" +s21.getPlanName());
    s21.setPrice(149);
    System.out.println("Price:" +s21.getPrice());
    s21.setDuration(30);
    System.out.println("Duration:" +s21.getDuration());
    s21.setStartDate("22-02-2026");
    System.out.println("Start Date:" +s21.getStartDate());
    s21.setEndDate("24-03-2026");
    System.out.println("End Date:" +s21.getEndDate());
    s21.setStatus("Active");
    System.out.println("Status:" +s21.getStatus());

    System.out.println();
    SubscriptionDetails s22 = new SubscriptionDetails();
    s22.setSubscriptionId(22);
    System.out.println("Subscription Id:" +s22.getSubscriptionId());
    s22.setPlanName("Advanced Plan");
    System.out.println("Plan:" +s22.getPlanName());
    s22.setPrice(699);
    System.out.println("Price:" +s22.getPrice());
    s22.setDuration(90);
    System.out.println("Duration:" +s22.getDuration());
    s22.setStartDate("24-02-2026");
    System.out.println("Start Date:" +s22.getStartDate());
    s22.setEndDate("24-05-2026");
    System.out.println("End Date:" +s22.getEndDate());
    s22.setStatus("Active");
    System.out.println("Status:" +s22.getStatus());

    System.out.println();
    SubscriptionDetails s23 = new SubscriptionDetails();
    s23.setSubscriptionId(23);
    System.out.println("Subscription Id:" +s23.getSubscriptionId());
    s23.setPlanName("Student Plus");
    System.out.println("Plan:" +s23.getPlanName());
    s23.setPrice(129);
    System.out.println("Price:" +s23.getPrice());
    s23.setDuration(30);
    System.out.println("Duration:" +s23.getDuration());
    s23.setStartDate("26-02-2026");
    System.out.println("Start Date:" +s23.getStartDate());
    s23.setEndDate("28-03-2026");
    System.out.println("End Date:" +s23.getEndDate());
    s23.setStatus("Active");
    System.out.println("Status:" +s23.getStatus());

    System.out.println();
    SubscriptionDetails s24 = new SubscriptionDetails();
    s24.setSubscriptionId(24);
    System.out.println("Subscription Id:" +s24.getSubscriptionId());
    s24.setPlanName("Family Plus");
    System.out.println("Plan:" +s24.getPlanName());
    s24.setPrice(1199);
    System.out.println("Price:" +s24.getPrice());
    s24.setDuration(365);
    System.out.println("Duration:" +s24.getDuration());
    s24.setStartDate("01-03-2026");
    System.out.println("Start Date:" +s24.getStartDate());
    s24.setEndDate("01-03-2027");
    System.out.println("End Date:" +s24.getEndDate());
    s24.setStatus("Active");
    System.out.println("Status:" +s24.getStatus());

    System.out.println();
    SubscriptionDetails s25 = new SubscriptionDetails();
    s25.setSubscriptionId(25);
    System.out.println("Subscription Id:" +s25.getSubscriptionId());
    s25.setPlanName("Weekend Plus");
    System.out.println("Plan:" +s25.getPlanName());
    s25.setPrice(59);
    System.out.println("Price:" +s25.getPrice());
    s25.setDuration(7);
    System.out.println("Duration:" +s25.getDuration());
    s25.setStartDate("03-03-2026");
    System.out.println("Start Date:" +s25.getStartDate());
    s25.setEndDate("10-03-2026");
    System.out.println("End Date:" +s25.getEndDate());
    s25.setStatus("Expired");
    System.out.println("Status:" +s25.getStatus());

    System.out.println();
    SubscriptionDetails s26 = new SubscriptionDetails();
    s26.setSubscriptionId(26);
    System.out.println("Subscription Id:" +s26.getSubscriptionId());
    s26.setPlanName("Pro Plus");
    System.out.println("Plan:" +s26.getPlanName());
    s26.setPrice(1499);
    System.out.println("Price:" +s26.getPrice());
    s26.setDuration(365);
    System.out.println("Duration:" +s26.getDuration());
    s26.setStartDate("05-03-2026");
    System.out.println("Start Date:" +s26.getStartDate());
    s26.setEndDate("05-03-2027");
    System.out.println("End Date:" +s26.getEndDate());
    s26.setStatus("Active");
    System.out.println("Status:" +s26.getStatus());

    System.out.println();
    SubscriptionDetails s27 = new SubscriptionDetails();
    s27.setSubscriptionId(27);
    System.out.println("Subscription Id:" +s27.getSubscriptionId());
    s27.setPlanName("Enterprise Plus");
    System.out.println("Plan:" +s27.getPlanName());
    s27.setPrice(6000);
    System.out.println("Price:" +s27.getPrice());
    s27.setDuration(365);
    System.out.println("Duration:" +s27.getDuration());
    s27.setStartDate("07-03-2026");
    System.out.println("Start Date:" +s27.getStartDate());
    s27.setEndDate("07-03-2027");
    System.out.println("End Date:" +s27.getEndDate());
    s27.setStatus("Active");
    System.out.println("Status:" +s27.getStatus());

    System.out.println();
    SubscriptionDetails s28 = new SubscriptionDetails();
    s28.setSubscriptionId(28);
    System.out.println("Subscription Id:" +s28.getSubscriptionId());
    s28.setPlanName("Mini Plus");
    System.out.println("Plan:" +s28.getPlanName());
    s28.setPrice(99);
    System.out.println("Price:" +s28.getPrice());
    s28.setDuration(15);
    System.out.println("Duration:" +s28.getDuration());
    s28.setStartDate("09-03-2026");
    System.out.println("Start Date:" +s28.getStartDate());
    s28.setEndDate("24-03-2026");
    System.out.println("End Date:" +s28.getEndDate());
    s28.setStatus("Expired");
    System.out.println("Status:" +s28.getStatus());

    System.out.println();
    SubscriptionDetails s29 = new SubscriptionDetails();
    s29.setSubscriptionId(29);
    System.out.println("Subscription Id:" +s29.getSubscriptionId());
    s29.setPlanName("Ultimate Plus");
    System.out.println("Plan:" +s29.getPlanName());
    s29.setPrice(12000);
    System.out.println("Price:" +s29.getPrice());
    s29.setDuration(365);
    System.out.println("Duration:" +s29.getDuration());
    s29.setStartDate("10-03-2026");
    System.out.println("Start Date:" +s29.getStartDate());
    s29.setEndDate("10-03-2027");
    System.out.println("End Date:" +s29.getEndDate());
    s29.setStatus("Active");
    System.out.println("Status:" +s29.getStatus());
 }
}