class TicketDetailsExecutor {
 public static void main(String[] args){
    TicketDetails t1 = new TicketDetails();
    t1.setTicketId(1);
    System.out.println("Ticket Id:" +t1.getTicketId());
    t1.setPassengerName("Ravi");
    System.out.println("Passenger:" +t1.getPassengerName());
    t1.setSource("Bangalore");
    System.out.println("Source:" +t1.getSource());
    t1.setDestination("Chennai");
    System.out.println("Destination:" +t1.getDestination());
    t1.setPrice(850);
    System.out.println("Price:" +t1.getPrice());
    t1.setDate("01-04-2026");
    System.out.println("Date:" +t1.getDate());
    t1.setStatus("Booked");
    System.out.println("Status:" +t1.getStatus());

    System.out.println();
    TicketDetails t2 = new TicketDetails();
    t2.setTicketId(2);
    System.out.println("Ticket Id:" +t2.getTicketId());
    t2.setPassengerName("Sneha");
    System.out.println("Passenger:" +t2.getPassengerName());
    t2.setSource("Mumbai");
    System.out.println("Source:" +t2.getSource());
    t2.setDestination("Delhi");
    System.out.println("Destination:" +t2.getDestination());
    t2.setPrice(1500);
    System.out.println("Price:" +t2.getPrice());
    t2.setDate("02-04-2026");
    System.out.println("Date:" +t2.getDate());
    t2.setStatus("Confirmed");
    System.out.println("Status:" +t2.getStatus());
	
	System.out.println();
    TicketDetails t3 = new TicketDetails();
    t3.setTicketId(3);
    System.out.println("Ticket Id:" +t3.getTicketId());
    t3.setPassengerName("Arjun");
    System.out.println("Passenger:" +t3.getPassengerName());
    t3.setSource("Hyderabad");
    System.out.println("Source:" +t3.getSource());
    t3.setDestination("Bangalore");
    System.out.println("Destination:" +t3.getDestination());
    t3.setPrice(900);
    System.out.println("Price:" +t3.getPrice());
    t3.setDate("03-04-2026");
    System.out.println("Date:" +t3.getDate());
    t3.setStatus("Booked");
    System.out.println("Status:" +t3.getStatus());

    System.out.println();
    TicketDetails t4 = new TicketDetails();
    t4.setTicketId(4);
    System.out.println("Ticket Id:" +t4.getTicketId());
    t4.setPassengerName("Pooja");
    System.out.println("Passenger:" +t4.getPassengerName());
    t4.setSource("Delhi");
    System.out.println("Source:" +t4.getSource());
    t4.setDestination("Jaipur");
    System.out.println("Destination:" +t4.getDestination());
    t4.setPrice(700);
    System.out.println("Price:" +t4.getPrice());
    t4.setDate("04-04-2026");
    System.out.println("Date:" +t4.getDate());
    t4.setStatus("Confirmed");
    System.out.println("Status:" +t4.getStatus());

    System.out.println();
    TicketDetails t5 = new TicketDetails();
    t5.setTicketId(5);
    System.out.println("Ticket Id:" +t5.getTicketId());
    t5.setPassengerName("Kiran");
    System.out.println("Passenger:" +t5.getPassengerName());
    t5.setSource("Chennai");
    System.out.println("Source:" +t5.getSource());
    t5.setDestination("Coimbatore");
    System.out.println("Destination:" +t5.getDestination());
    t5.setPrice(600);
    System.out.println("Price:" +t5.getPrice());
    t5.setDate("05-04-2026");
    System.out.println("Date:" +t5.getDate());
    t5.setStatus("Cancelled");
    System.out.println("Status:" +t5.getStatus());

    System.out.println();
    TicketDetails t6 = new TicketDetails();
    t6.setTicketId(6);
    System.out.println("Ticket Id:" +t6.getTicketId());
    t6.setPassengerName("Meena");
    System.out.println("Passenger:" +t6.getPassengerName());
    t6.setSource("Pune");
    System.out.println("Source:" +t6.getSource());
    t6.setDestination("Mumbai");
    System.out.println("Destination:" +t6.getDestination());
    t6.setPrice(500);
    System.out.println("Price:" +t6.getPrice());
    t6.setDate("06-04-2026");
    System.out.println("Date:" +t6.getDate());
    t6.setStatus("Booked");
    System.out.println("Status:" +t6.getStatus());

    System.out.println();
    TicketDetails t7 = new TicketDetails();
    t7.setTicketId(7);
    System.out.println("Ticket Id:" +t7.getTicketId());
    t7.setPassengerName("Rahul");
    System.out.println("Passenger:" +t7.getPassengerName());
    t7.setSource("Kolkata");
    System.out.println("Source:" +t7.getSource());
    t7.setDestination("Delhi");
    System.out.println("Destination:" +t7.getDestination());
    t7.setPrice(1400);
    System.out.println("Price:" +t7.getPrice());
    t7.setDate("07-04-2026");
    System.out.println("Date:" +t7.getDate());
    t7.setStatus("Confirmed");
    System.out.println("Status:" +t7.getStatus());

    System.out.println();
    TicketDetails t8 = new TicketDetails();
    t8.setTicketId(8);
    System.out.println("Ticket Id:" +t8.getTicketId());
    t8.setPassengerName("Anjali");
    System.out.println("Passenger:" +t8.getPassengerName());
    t8.setSource("Ahmedabad");
    System.out.println("Source:" +t8.getSource());
    t8.setDestination("Surat");
    System.out.println("Destination:" +t8.getDestination());
    t8.setPrice(400);
    System.out.println("Price:" +t8.getPrice());
    t8.setDate("08-04-2026");
    System.out.println("Date:" +t8.getDate());
    t8.setStatus("Booked");
    System.out.println("Status:" +t8.getStatus());

    System.out.println();
    TicketDetails t9 = new TicketDetails();
    t9.setTicketId(9);
    System.out.println("Ticket Id:" +t9.getTicketId());
    t9.setPassengerName("Vijay");
    System.out.println("Passenger:" +t9.getPassengerName());
    t9.setSource("Goa");
    System.out.println("Source:" +t9.getSource());
    t9.setDestination("Bangalore");
    System.out.println("Destination:" +t9.getDestination());
    t9.setPrice(1200);
    System.out.println("Price:" +t9.getPrice());
    t9.setDate("09-04-2026");
    System.out.println("Date:" +t9.getDate());
    t9.setStatus("Cancelled");
    System.out.println("Status:" +t9.getStatus());

    System.out.println();
    TicketDetails t10 = new TicketDetails();
    t10.setTicketId(10);
    System.out.println("Ticket Id:" +t10.getTicketId());
    t10.setPassengerName("Lakshmi");
    System.out.println("Passenger:" +t10.getPassengerName());
    t10.setSource("Mysore");
    System.out.println("Source:" +t10.getSource());
    t10.setDestination("Chennai");
    System.out.println("Destination:" +t10.getDestination());
    t10.setPrice(950);
    System.out.println("Price:" +t10.getPrice());
    t10.setDate("10-04-2026");
    System.out.println("Date:" +t10.getDate());
    t10.setStatus("Confirmed");
    System.out.println("Status:" +t10.getStatus());

 }
}