class UserAccountExecutor{
 public static void main(String[] args){
    UserAccount useraccount = new UserAccount();
	useraccount.setId(1);
	System.out.println("Account Id:" +useraccount.getId());
	useraccount.setUserName("Harsha");
	System.out.println("Username:" +useraccount.getUserName());
	useraccount.setEmail("harsha190@gmail.com");
	System.out.println("Email:" +useraccount.getEmail());
	useraccount.setPassword("harsha87@1.");
	System.out.println("Password:" +useraccount.getPassword());
	useraccount.setPhone(9784561284L);
	System.out.println("Phone.no:" +useraccount.getPhone());
	useraccount.setAddress("Rajajinagar");
	System.out.println("Address:" +useraccount.getAddress());
	useraccount.setActive(true);
	System.out.println("Active:" +useraccount.getActive());
	
	
	System.out.println();
	UserAccount useraccount1= new UserAccount();
	useraccount1.setId(2);
	System.out.println("Account Id:" +useraccount1.getId());
	useraccount1.setUserName("Lohith");
	System.out.println("Username:" +useraccount1.getUserName());
	useraccount1.setEmail("Lohith190@gmail.com");
	System.out.println("Email:" +useraccount1.getEmail());
	useraccount1.setPassword("Lohith87@1.");
	System.out.println("Password:" +useraccount1.getPassword());
	useraccount1.setPhone(978478584L);
	System.out.println("Phone.no:" +useraccount1.getPhone());
	useraccount1.setAddress("BTM Layout");
	System.out.println("Address:" +useraccount1.getAddress());
	useraccount1.setActive(false);
	System.out.println("Active:" +useraccount1.getActive());
	
	System.out.println();
UserAccount useraccount2 = new UserAccount();
useraccount2.setId(3);
System.out.println("Account Id:" +useraccount2.getId());
useraccount2.setUserName("Kiran");
System.out.println("Username:" +useraccount2.getUserName());
useraccount2.setEmail("kiran3@gmail.com");
System.out.println("Email:" +useraccount2.getEmail());
useraccount2.setPassword("Kiran@123");
System.out.println("Password:" +useraccount2.getPassword());
useraccount2.setPhone(900000003L);
System.out.println("Phone.no:" +useraccount2.getPhone());
useraccount2.setAddress("Chennai");
System.out.println("Address:" +useraccount2.getAddress());
useraccount2.setActive(true);
System.out.println("Active:" +useraccount2.getActive());

System.out.println();
UserAccount useraccount3 = new UserAccount();
useraccount3.setId(4);
System.out.println("Account Id:" +useraccount3.getId());
useraccount3.setUserName("Suresh");
System.out.println("Username:" +useraccount3.getUserName());
useraccount3.setEmail("suresh4@gmail.com");
System.out.println("Email:" +useraccount3.getEmail());
useraccount3.setPassword("Suresh@123");
System.out.println("Password:" +useraccount3.getPassword());
useraccount3.setPhone(900000004L);
System.out.println("Phone.no:" +useraccount3.getPhone());
useraccount3.setAddress("Hyderabad");
System.out.println("Address:" +useraccount3.getAddress());
useraccount3.setActive(false);
System.out.println("Active:" +useraccount3.getActive());

System.out.println();
UserAccount useraccount4 = new UserAccount();
useraccount4.setId(5);
System.out.println("Account Id:" +useraccount4.getId());
useraccount4.setUserName("Ravi");
System.out.println("Username:" +useraccount4.getUserName());
useraccount4.setEmail("ravi5@gmail.com");
System.out.println("Email:" +useraccount4.getEmail());
useraccount4.setPassword("Ravi@123");
System.out.println("Password:" +useraccount4.getPassword());
useraccount4.setPhone(900000005L);
System.out.println("Phone.no:" +useraccount4.getPhone());
useraccount4.setAddress("Delhi");
System.out.println("Address:" +useraccount4.getAddress());
useraccount4.setActive(true);
System.out.println("Active:" +useraccount4.getActive());

System.out.println();
UserAccount useraccount5 = new UserAccount();
useraccount5.setId(6);
System.out.println("Account Id:" +useraccount5.getId());
useraccount5.setUserName("Vijay");
System.out.println("Username:" +useraccount5.getUserName());
useraccount5.setEmail("vijay6@gmail.com");
System.out.println("Email:" +useraccount5.getEmail());
useraccount5.setPassword("Vijay@123");
System.out.println("Password:" +useraccount5.getPassword());
useraccount5.setPhone(900000006L);
System.out.println("Phone.no:" +useraccount5.getPhone());
useraccount5.setAddress("Mumbai");
System.out.println("Address:" +useraccount5.getAddress());
useraccount5.setActive(false);
System.out.println("Active:" +useraccount5.getActive());

System.out.println();
UserAccount useraccount6 = new UserAccount();
useraccount6.setId(7);
System.out.println("Account Id:" +useraccount6.getId());
useraccount6.setUserName("Arjun");
System.out.println("Username:" +useraccount6.getUserName());
useraccount6.setEmail("arjun7@gmail.com");
System.out.println("Email:" +useraccount6.getEmail());
useraccount6.setPassword("Arjun@123");
System.out.println("Password:" +useraccount6.getPassword());
useraccount6.setPhone(900000007L);
System.out.println("Phone.no:" +useraccount6.getPhone());
useraccount6.setAddress("Pune");
System.out.println("Address:" +useraccount6.getAddress());
useraccount6.setActive(true);
System.out.println("Active:" +useraccount6.getActive());

System.out.println();
UserAccount useraccount7 = new UserAccount();
useraccount7.setId(8);
System.out.println("Account Id:" +useraccount7.getId());
useraccount7.setUserName("Manoj");
System.out.println("Username:" +useraccount7.getUserName());
useraccount7.setEmail("manoj8@gmail.com");
System.out.println("Email:" +useraccount7.getEmail());
useraccount7.setPassword("Manoj@123");
System.out.println("Password:" +useraccount7.getPassword());
useraccount7.setPhone(900000008L);
System.out.println("Phone.no:" +useraccount7.getPhone());
useraccount7.setAddress("Goa");
System.out.println("Address:" +useraccount7.getAddress());
useraccount7.setActive(false);
System.out.println("Active:" +useraccount7.getActive());

System.out.println();
UserAccount useraccount8 = new UserAccount();
useraccount8.setId(9);
System.out.println("Account Id:" +useraccount8.getId());
useraccount8.setUserName("Deepak");
System.out.println("Username:" +useraccount8.getUserName());
useraccount8.setEmail("deepak9@gmail.com");
System.out.println("Email:" +useraccount8.getEmail());
useraccount8.setPassword("Deepak@123");
System.out.println("Password:" +useraccount8.getPassword());
useraccount8.setPhone(900000009L);
System.out.println("Phone.no:" +useraccount8.getPhone());
useraccount8.setAddress("Kerala");
System.out.println("Address:" +useraccount8.getAddress());
useraccount8.setActive(true);
System.out.println("Active:" +useraccount8.getActive());

System.out.println();
UserAccount useraccount9 = new UserAccount();
useraccount9.setId(10);
System.out.println("Account Id:" +useraccount9.getId());
useraccount9.setUserName("Tarun");
System.out.println("Username:" +useraccount9.getUserName());
useraccount9.setEmail("tarun10@gmail.com");
System.out.println("Email:" +useraccount9.getEmail());
useraccount9.setPassword("Tarun@123");
System.out.println("Password:" +useraccount9.getPassword());
useraccount9.setPhone(900000010L);
System.out.println("Phone.no:" +useraccount9.getPhone());
useraccount9.setAddress("BTM Layout");
System.out.println("Address:" +useraccount9.getAddress());
useraccount9.setActive(false);
System.out.println("Active:" +useraccount9.getActive());


System.out.println();
UserAccount useraccount10 = new UserAccount();
useraccount10.setId(11);
System.out.println("Account Id:" +useraccount10.getId());
useraccount10.setUserName("Nikhil");
System.out.println("Username:" +useraccount10.getUserName());
useraccount10.setEmail("nikhil11@gmail.com");
System.out.println("Email:" +useraccount10.getEmail());
useraccount10.setPassword("Nikhil@123");
System.out.println("Password:" +useraccount10.getPassword());
useraccount10.setPhone(900000011L);
System.out.println("Phone.no:" +useraccount10.getPhone());
useraccount10.setAddress("Indore");
System.out.println("Address:" +useraccount10.getAddress());
useraccount10.setActive(true);
System.out.println("Active:" +useraccount10.getActive());

System.out.println();
UserAccount useraccount11 = new UserAccount();
useraccount11.setId(12);
System.out.println("Account Id:" +useraccount11.getId());
useraccount11.setUserName("Rohit");
System.out.println("Username:" +useraccount11.getUserName());
useraccount11.setEmail("rohit12@gmail.com");
System.out.println("Email:" +useraccount11.getEmail());
useraccount11.setPassword("Rohit@123");
System.out.println("Password:" +useraccount11.getPassword());
useraccount11.setPhone(900000012L);
System.out.println("Phone.no:" +useraccount11.getPhone());
useraccount11.setAddress("Nagpur");
System.out.println("Address:" +useraccount11.getAddress());
useraccount11.setActive(false);
System.out.println("Active:" +useraccount11.getActive());

System.out.println();
UserAccount useraccount12 = new UserAccount();
useraccount12.setId(13);
System.out.println("Account Id:" +useraccount12.getId());
useraccount12.setUserName("Ajay");
System.out.println("Username:" +useraccount12.getUserName());
useraccount12.setEmail("ajay13@gmail.com");
System.out.println("Email:" +useraccount12.getEmail());
useraccount12.setPassword("Ajay@123");
System.out.println("Password:" +useraccount12.getPassword());
useraccount12.setPhone(900000013L);
System.out.println("Phone.no:" +useraccount12.getPhone());
useraccount12.setAddress("Jaipur");
System.out.println("Address:" +useraccount12.getAddress());
useraccount12.setActive(true);
System.out.println("Active:" +useraccount12.getActive());

System.out.println();
UserAccount useraccount13 = new UserAccount();
useraccount13.setId(14);
System.out.println("Account Id:" +useraccount13.getId());
useraccount13.setUserName("Vinay");
System.out.println("Username:" +useraccount13.getUserName());
useraccount13.setEmail("vinay14@gmail.com");
System.out.println("Email:" +useraccount13.getEmail());
useraccount13.setPassword("Vinay@123");
System.out.println("Password:" +useraccount13.getPassword());
useraccount13.setPhone(900000014L);
System.out.println("Phone.no:" +useraccount13.getPhone());
useraccount13.setAddress("Lucknow");
System.out.println("Address:" +useraccount13.getAddress());
useraccount13.setActive(false);
System.out.println("Active:" +useraccount13.getActive());

System.out.println();
UserAccount useraccount14 = new UserAccount();
useraccount14.setId(15);
System.out.println("Account Id:" +useraccount14.getId());
useraccount14.setUserName("Prakash");
System.out.println("Username:" +useraccount14.getUserName());
useraccount14.setEmail("prakash15@gmail.com");
System.out.println("Email:" +useraccount14.getEmail());
useraccount14.setPassword("Prakash@123");
System.out.println("Password:" +useraccount14.getPassword());
useraccount14.setPhone(900000015L);
System.out.println("Phone.no:" +useraccount14.getPhone());
useraccount14.setAddress("Patna");
System.out.println("Address:" +useraccount14.getAddress());
useraccount14.setActive(true);
System.out.println("Active:" +useraccount14.getActive());

System.out.println();
UserAccount useraccount15 = new UserAccount();
useraccount15.setId(16);
System.out.println("Account Id:" +useraccount15.getId());
useraccount15.setUserName("Sunil");
System.out.println("Username:" +useraccount15.getUserName());
useraccount15.setEmail("sunil16@gmail.com");
System.out.println("Email:" +useraccount15.getEmail());
useraccount15.setPassword("Sunil@123");
System.out.println("Password:" +useraccount15.getPassword());
useraccount15.setPhone(900000016L);
System.out.println("Phone.no:" +useraccount15.getPhone());
useraccount15.setAddress("Bhopal");
System.out.println("Address:" +useraccount15.getAddress());
useraccount15.setActive(false);
System.out.println("Active:" +useraccount15.getActive());

System.out.println();
UserAccount useraccount16 = new UserAccount();
useraccount16.setId(17);
System.out.println("Account Id:" +useraccount16.getId());
useraccount16.setUserName("Girish");
System.out.println("Username:" +useraccount16.getUserName());
useraccount16.setEmail("girish17@gmail.com");
System.out.println("Email:" +useraccount16.getEmail());
useraccount16.setPassword("Girish@123");
System.out.println("Password:" +useraccount16.getPassword());
useraccount16.setPhone(900000017L);
System.out.println("Phone.no:" +useraccount16.getPhone());
useraccount16.setAddress("Surat");
System.out.println("Address:" +useraccount16.getAddress());
useraccount16.setActive(true);
System.out.println("Active:" +useraccount16.getActive());

System.out.println();
UserAccount useraccount17 = new UserAccount();
useraccount17.setId(18);
System.out.println("Account Id:" +useraccount17.getId());
useraccount17.setUserName("Mahesh");
System.out.println("Username:" +useraccount17.getUserName());
useraccount17.setEmail("mahesh18@gmail.com");
System.out.println("Email:" +useraccount17.getEmail());
useraccount17.setPassword("Mahesh@123");
System.out.println("Password:" +useraccount17.getPassword());
useraccount17.setPhone(900000018L);
System.out.println("Phone.no:" +useraccount17.getPhone());
useraccount17.setAddress("Ahmedabad");
System.out.println("Address:" +useraccount17.getAddress());
useraccount17.setActive(false);
System.out.println("Active:" +useraccount17.getActive());

System.out.println();
UserAccount useraccount18 = new UserAccount();
useraccount18.setId(19);
System.out.println("Account Id:" +useraccount18.getId());
useraccount18.setUserName("Tejas");
System.out.println("Username:" +useraccount18.getUserName());
useraccount18.setEmail("tejas19@gmail.com");
System.out.println("Email:" +useraccount18.getEmail());
useraccount18.setPassword("Tejas@123");
System.out.println("Password:" +useraccount18.getPassword());
useraccount18.setPhone(900000019L);
System.out.println("Phone.no:" +useraccount18.getPhone());
useraccount18.setAddress("Hubli");
System.out.println("Address:" +useraccount18.getAddress());
useraccount18.setActive(true);
System.out.println("Active:" +useraccount18.getActive());

System.out.println();
UserAccount useraccount19 = new UserAccount();
useraccount19.setId(20);
System.out.println("Account Id:" +useraccount19.getId());
useraccount19.setUserName("Shiva");
System.out.println("Username:" +useraccount19.getUserName());
useraccount19.setEmail("shiva20@gmail.com");
System.out.println("Email:" +useraccount19.getEmail());
useraccount19.setPassword("Shiva@123");
System.out.println("Password:" +useraccount19.getPassword());
useraccount19.setPhone(900000020L);
System.out.println("Phone.no:" +useraccount19.getPhone());
useraccount19.setAddress("Udupi");
System.out.println("Address:" +useraccount19.getAddress());
useraccount19.setActive(false);
System.out.println("Active:" +useraccount19.getActive());

System.out.println();
UserAccount useraccount20 = new UserAccount();
useraccount20.setId(21);
System.out.println("Account Id:" +useraccount20.getId());
useraccount20.setUserName("Ganesh");
System.out.println("Username:" +useraccount20.getUserName());
useraccount20.setEmail("ganesh21@gmail.com");
System.out.println("Email:" +useraccount20.getEmail());
useraccount20.setPassword("Ganesh@123");
System.out.println("Password:" +useraccount20.getPassword());
useraccount20.setPhone(900000021L);
System.out.println("Phone.no:" +useraccount20.getPhone());
useraccount20.setAddress("Belgaum");
System.out.println("Address:" +useraccount20.getAddress());
useraccount20.setActive(true);
System.out.println("Active:" +useraccount20.getActive());

System.out.println();
UserAccount useraccount21 = new UserAccount();
useraccount21.setId(22);
System.out.println("Account Id:" +useraccount21.getId());
useraccount21.setUserName("Harish");
System.out.println("Username:" +useraccount21.getUserName());
useraccount21.setEmail("harish22@gmail.com");
System.out.println("Email:" +useraccount21.getEmail());
useraccount21.setPassword("Harish@123");
System.out.println("Password:" +useraccount21.getPassword());
useraccount21.setPhone(900000022L);
System.out.println("Phone.no:" +useraccount21.getPhone());
useraccount21.setAddress("Davangere");
System.out.println("Address:" +useraccount21.getAddress());
useraccount21.setActive(false);
System.out.println("Active:" +useraccount21.getActive());

System.out.println();
UserAccount useraccount22 = new UserAccount();
useraccount22.setId(23);
System.out.println("Account Id:" +useraccount22.getId());
useraccount22.setUserName("Lokesh");
System.out.println("Username:" +useraccount22.getUserName());
useraccount22.setEmail("lokesh23@gmail.com");
System.out.println("Email:" +useraccount22.getEmail());
useraccount22.setPassword("Lokesh@123");
System.out.println("Password:" +useraccount22.getPassword());
useraccount22.setPhone(900000023L);
System.out.println("Phone.no:" +useraccount22.getPhone());
useraccount22.setAddress("Tumkur");
System.out.println("Address:" +useraccount22.getAddress());
useraccount22.setActive(true);
System.out.println("Active:" +useraccount22.getActive());

System.out.println();
UserAccount useraccount23 = new UserAccount();
useraccount23.setId(24);
System.out.println("Account Id:" +useraccount23.getId());
useraccount23.setUserName("Ramesh");
System.out.println("Username:" +useraccount23.getUserName());
useraccount23.setEmail("ramesh24@gmail.com");
System.out.println("Email:" +useraccount23.getEmail());
useraccount23.setPassword("Ramesh@123");
System.out.println("Password:" +useraccount23.getPassword());
useraccount23.setPhone(900000024L);
System.out.println("Phone.no:" +useraccount23.getPhone());
useraccount23.setAddress("Kolar");
System.out.println("Address:" +useraccount23.getAddress());
useraccount23.setActive(false);
System.out.println("Active:" +useraccount23.getActive());

System.out.println();
UserAccount useraccount24 = new UserAccount();
useraccount24.setId(25);
System.out.println("Account Id:" +useraccount24.getId());
useraccount24.setUserName("Sanjay");
System.out.println("Username:" +useraccount24.getUserName());
useraccount24.setEmail("sanjay25@gmail.com");
System.out.println("Email:" +useraccount24.getEmail());
useraccount24.setPassword("Sanjay@123");
System.out.println("Password:" +useraccount24.getPassword());
useraccount24.setPhone(900000025L);
System.out.println("Phone.no:" +useraccount24.getPhone());
useraccount24.setAddress("Chikkaballapur");
System.out.println("Address:" +useraccount24.getAddress());
useraccount24.setActive(true);
System.out.println("Active:" +useraccount24.getActive());

System.out.println();
UserAccount useraccount25 = new UserAccount();
useraccount25.setId(26);
System.out.println("Account Id:" +useraccount25.getId());
useraccount25.setUserName("Varun");
System.out.println("Username:" +useraccount25.getUserName());
useraccount25.setEmail("varun26@gmail.com");
System.out.println("Email:" +useraccount25.getEmail());
useraccount25.setPassword("Varun@123");
System.out.println("Password:" +useraccount25.getPassword());
useraccount25.setPhone(900000026L);
System.out.println("Phone.no:" +useraccount25.getPhone());
useraccount25.setAddress("Ramanagara");
System.out.println("Address:" +useraccount25.getAddress());
useraccount25.setActive(false);
System.out.println("Active:" +useraccount25.getActive());

System.out.println();
UserAccount useraccount26 = new UserAccount();
useraccount26.setId(27);
System.out.println("Account Id:" +useraccount26.getId());
useraccount26.setUserName("Karthik");
System.out.println("Username:" +useraccount26.getUserName());
useraccount26.setEmail("karthik27@gmail.com");
System.out.println("Email:" +useraccount26.getEmail());
useraccount26.setPassword("Karthik@123");
System.out.println("Password:" +useraccount26.getPassword());
useraccount26.setPhone(900000027L);
System.out.println("Phone.no:" +useraccount26.getPhone());
useraccount26.setAddress("Mandya");
System.out.println("Address:" +useraccount26.getAddress());
useraccount26.setActive(true);
System.out.println("Active:" +useraccount26.getActive());

System.out.println();
UserAccount useraccount27 = new UserAccount();
useraccount27.setId(28);
System.out.println("Account Id:" +useraccount27.getId());
useraccount27.setUserName("Shiva");
System.out.println("Username:" +useraccount27.getUserName());
useraccount27.setEmail("shiva20@gmail.com");
System.out.println("Email:" +useraccount27.getEmail());
useraccount27.setPassword("Shiva@123");
System.out.println("Password:" +useraccount27.getPassword());
useraccount27.setPhone(900000020L);
System.out.println("Phone.no:" +useraccount27.getPhone());
useraccount27.setAddress("Udupi");
System.out.println("Address:" +useraccount27.getAddress());
useraccount27.setActive(false);
System.out.println("Active:" +useraccount27.getActive());

System.out.println();
UserAccount useraccount28 = new UserAccount();
useraccount28.setId(29);
System.out.println("Account Id:" +useraccount28.getId());
useraccount28.setUserName("Anand");
System.out.println("Username:" +useraccount28.getUserName());
useraccount28.setEmail("anand28@gmail.com");
System.out.println("Email:" +useraccount28.getEmail());
useraccount28.setPassword("Anand@123");
System.out.println("Password:" +useraccount28.getPassword());
useraccount28.setPhone(900000028L);
System.out.println("Phone.no:" +useraccount28.getPhone());
useraccount28.setAddress("Mangalore");
System.out.println("Address:" +useraccount28.getAddress());
useraccount28.setActive(true);
System.out.println("Active:" +useraccount28.getActive());

System.out.println();
UserAccount useraccount29 = new UserAccount();
useraccount29.setId(30);
System.out.println("Account Id:" +useraccount29.getId());
useraccount29.setUserName("Tarun");
System.out.println("Username:" +useraccount29.getUserName());
useraccount29.setEmail("tarun10@gmail.com");
System.out.println("Email:" +useraccount29.getEmail());
useraccount29.setPassword("Tarun@123");
System.out.println("Password:" +useraccount29.getPassword());
useraccount29.setPhone(900000010L);
System.out.println("Phone.no:" +useraccount29.getPhone());
useraccount29.setAddress("BTM Layout");
System.out.println("Address:" +useraccount29.getAddress());
useraccount29.setActive(false);
System.out.println("Active:" +useraccount29.getActive());
	}
	}