class UserManualExecutor{
  public static void main(String[] args){    
	System.out.println();
    UserManual u1 = new UserManual();
    u1.setManualId(1);
    System.out.println("Manual Id:" +u1.getManualId());
    u1.setTitle("Getting Started");
    System.out.println("Title:" +u1.getTitle());
    u1.setDescription("Introduction to system");
    System.out.println("Description:" +u1.getDescription());
    u1.setVersion("1.0");
    System.out.println("Version:" +u1.getVersion());
    u1.setAuthor("Admin");
    System.out.println("Author:" +u1.getAuthor());

    System.out.println();
    UserManual u2 = new UserManual();
    u2.setManualId(2);
    System.out.println("Manual Id:" +u2.getManualId());
    u2.setTitle("Installation Guide");
    System.out.println("Title:" +u2.getTitle());
    u2.setDescription("Steps to install software");
    System.out.println("Description:" +u2.getDescription());
    u2.setVersion("1.1");
    System.out.println("Version:" +u2.getVersion());
    u2.setAuthor("Kiran");
    System.out.println("Author:" +u2.getAuthor());

    System.out.println();
    UserManual u3 = new UserManual();
    u3.setManualId(3);
    System.out.println("Manual Id:" +u3.getManualId());
    u3.setTitle("User Guide");
    System.out.println("Title:" +u3.getTitle());
    u3.setDescription("How to use application");
    System.out.println("Description:" +u3.getDescription());
    u3.setVersion("2.0");
    System.out.println("Version:" +u3.getVersion());
    u3.setAuthor("Sneha");
    System.out.println("Author:" +u3.getAuthor());

    System.out.println();
    UserManual u4 = new UserManual();
    u4.setManualId(4);
    System.out.println("Manual Id:" +u4.getManualId());
    u4.setTitle("Admin Guide");
    System.out.println("Title:" +u4.getTitle());
    u4.setDescription("Admin level operations");
    System.out.println("Description:" +u4.getDescription());
    u4.setVersion("2.1");
    System.out.println("Version:" +u4.getVersion());
    u4.setAuthor("Rahul");
    System.out.println("Author:" +u4.getAuthor());

    System.out.println();
    UserManual u5 = new UserManual();
    u5.setManualId(5);
    System.out.println("Manual Id:" +u5.getManualId());
    u5.setTitle("Troubleshooting");
    System.out.println("Title:" +u5.getTitle());
    u5.setDescription("Common issues and fixes");
    System.out.println("Description:" +u5.getDescription());
    u5.setVersion("2.2");
    System.out.println("Version:" +u5.getVersion());
    u5.setAuthor("Amit");
    System.out.println("Author:" +u5.getAuthor());
	
	System.out.println();
    UserManual u6 = new UserManual();
    u6.setManualId(6);
    System.out.println("Manual Id:" +u6.getManualId());
    u6.setTitle("Security Guide");
    System.out.println("Title:" +u6.getTitle());
    u6.setDescription("System security features");
    System.out.println("Description:" +u6.getDescription());
    u6.setVersion("3.0");
    System.out.println("Version:" +u6.getVersion());
    u6.setAuthor("Divya");
    System.out.println("Author:" +u6.getAuthor());

    System.out.println();
    UserManual u7 = new UserManual();
    u7.setManualId(7);
    System.out.println("Manual Id:" +u7.getManualId());
    u7.setTitle("Backup Guide");
    System.out.println("Title:" +u7.getTitle());
    u7.setDescription("How to backup data");
    System.out.println("Description:" +u7.getDescription());
    u7.setVersion("3.1");
    System.out.println("Version:" +u7.getVersion());
    u7.setAuthor("Arjun");
    System.out.println("Author:" +u7.getAuthor());

    System.out.println();
    UserManual u8 = new UserManual();
    u8.setManualId(8);
    System.out.println("Manual Id:" +u8.getManualId());
    u8.setTitle("Restore Guide");
    System.out.println("Title:" +u8.getTitle());
    u8.setDescription("Restore system data");
    System.out.println("Description:" +u8.getDescription());
    u8.setVersion("3.2");
    System.out.println("Version:" +u8.getVersion());
    u8.setAuthor("Kiran");
    System.out.println("Author:" +u8.getAuthor());

    System.out.println();
    UserManual u9 = new UserManual();
    u9.setManualId(9);
    System.out.println("Manual Id:" +u9.getManualId());
    u9.setTitle("Upgrade Guide");
    System.out.println("Title:" +u9.getTitle());
    u9.setDescription("Steps to upgrade system");
    System.out.println("Description:" +u9.getDescription());
    u9.setVersion("3.3");
    System.out.println("Version:" +u9.getVersion());
    u9.setAuthor("Sneha");
    System.out.println("Author:" +u9.getAuthor());

    System.out.println();
    UserManual u10 = new UserManual();
    u10.setManualId(10);
    System.out.println("Manual Id:" +u10.getManualId());
    u10.setTitle("FAQ");
    System.out.println("Title:" +u10.getTitle());
    u10.setDescription("Frequently asked questions");
    System.out.println("Description:" +u10.getDescription());
    u10.setVersion("3.4");
    System.out.println("Version:" +u10.getVersion());
    u10.setAuthor("Tarun");
    System.out.println("Author:" +u10.getAuthor());
	
	System.out.println();
    UserManual u11 = new UserManual();
    u11.setManualId(11);
    System.out.println("Manual Id:" +u11.getManualId());
    u11.setTitle("Login Guide");
    System.out.println("Title:" +u11.getTitle());
    u11.setDescription("User login process");
    System.out.println("Description:" +u11.getDescription());
    u11.setVersion("4.0");
    System.out.println("Version:" +u11.getVersion());
    u11.setAuthor("Rahul");
    System.out.println("Author:" +u11.getAuthor());

    System.out.println();
    UserManual u12 = new UserManual();
    u12.setManualId(12);
    System.out.println("Manual Id:" +u12.getManualId());
    u12.setTitle("Registration Guide");
    System.out.println("Title:" +u12.getTitle());
    u12.setDescription("User registration steps");
    System.out.println("Description:" +u12.getDescription());
    u12.setVersion("4.1");
    System.out.println("Version:" +u12.getVersion());
    u12.setAuthor("Pooja");
    System.out.println("Author:" +u12.getAuthor());

    System.out.println();
    UserManual u13 = new UserManual();
    u13.setManualId(13);
    System.out.println("Manual Id:" +u13.getManualId());
    u13.setTitle("Profile Guide");
    System.out.println("Title:" +u13.getTitle());
    u13.setDescription("Managing user profile");
    System.out.println("Description:" +u13.getDescription());
    u13.setVersion("4.2");
    System.out.println("Version:" +u13.getVersion());
    u13.setAuthor("Suresh");
    System.out.println("Author:" +u13.getAuthor());

    System.out.println();
    UserManual u14 = new UserManual();
    u14.setManualId(14);
    System.out.println("Manual Id:" +u14.getManualId());
    u14.setTitle("Settings Guide");
    System.out.println("Title:" +u14.getTitle());
    u14.setDescription("Application settings");
    System.out.println("Description:" +u14.getDescription());
    u14.setVersion("4.3");
    System.out.println("Version:" +u14.getVersion());
    u14.setAuthor("Anjali");
    System.out.println("Author:" +u14.getAuthor());

    System.out.println();
    UserManual u15 = new UserManual();
    u15.setManualId(15);
    System.out.println("Manual Id:" +u15.getManualId());
    u15.setTitle("Notification Guide");
    System.out.println("Title:" +u15.getTitle());
    u15.setDescription("Managing notifications");
    System.out.println("Description:" +u15.getDescription());
    u15.setVersion("4.4");
    System.out.println("Version:" +u15.getVersion());
    u15.setAuthor("Vijay");
    System.out.println("Author:" +u15.getAuthor());

    System.out.println();
    UserManual u16 = new UserManual();
    u16.setManualId(16);
    System.out.println("Manual Id:" +u16.getManualId());
    u16.setTitle("Privacy Guide");
    System.out.println("Title:" +u16.getTitle());
    u16.setDescription("User privacy settings");
    System.out.println("Description:" +u16.getDescription());
    u16.setVersion("4.5");
    System.out.println("Version:" +u16.getVersion());
    u16.setAuthor("Deepa");
    System.out.println("Author:" +u16.getAuthor());

    System.out.println();
    UserManual u17 = new UserManual();
    u17.setManualId(17);
    System.out.println("Manual Id:" +u17.getManualId());
    u17.setTitle("Data Usage Guide");
    System.out.println("Title:" +u17.getTitle());
    u17.setDescription("Monitoring data usage");
    System.out.println("Description:" +u17.getDescription());
    u17.setVersion("4.6");
    System.out.println("Version:" +u17.getVersion());
    u17.setAuthor("Karthik");
    System.out.println("Author:" +u17.getAuthor());

    System.out.println();
    UserManual u18 = new UserManual();
    u18.setManualId(18);
    System.out.println("Manual Id:" +u18.getManualId());
    u18.setTitle("Help Guide");
    System.out.println("Title:" +u18.getTitle());
    u18.setDescription("Getting help and support");
    System.out.println("Description:" +u18.getDescription());
    u18.setVersion("4.7");
    System.out.println("Version:" +u18.getVersion());
    u18.setAuthor("Meena");
    System.out.println("Author:" +u18.getAuthor());

    System.out.println();
    UserManual u19 = new UserManual();
    u19.setManualId(19);
    System.out.println("Manual Id:" +u19.getManualId());
    u19.setTitle("Feedback Guide");
    System.out.println("Title:" +u19.getTitle());
    u19.setDescription("Submitting feedback");
    System.out.println("Description:" +u19.getDescription());
    u19.setVersion("4.8");
    System.out.println("Version:" +u19.getVersion());
    u19.setAuthor("Arjun");
    System.out.println("Author:" +u19.getAuthor());

    System.out.println();
    UserManual u20 = new UserManual();
    u20.setManualId(20);
    System.out.println("Manual Id:" +u20.getManualId());
    u20.setTitle("Logout Guide");
    System.out.println("Title:" +u20.getTitle());
    u20.setDescription("User logout process");
    System.out.println("Description:" +u20.getDescription());
    u20.setVersion("4.9");
    System.out.println("Version:" +u20.getVersion());
    u20.setAuthor("Tarun");
    System.out.println("Author:" +u20.getAuthor());
	
	System.out.println();
    UserManual u21 = new UserManual();
    u21.setManualId(21);
    System.out.println("Manual Id:" +u21.getManualId());
    u21.setTitle("Dashboard Guide");
    System.out.println("Title:" +u21.getTitle());
    u21.setDescription("Overview of dashboard");
    System.out.println("Description:" +u21.getDescription());
    u21.setVersion("5.0");
    System.out.println("Version:" +u21.getVersion());
    u21.setAuthor("Nikhil");
    System.out.println("Author:" +u21.getAuthor());

    System.out.println();
    UserManual u22 = new UserManual();
    u22.setManualId(22);
    System.out.println("Manual Id:" +u22.getManualId());
    u22.setTitle("Search Guide");
    System.out.println("Title:" +u22.getTitle());
    u22.setDescription("How to search data");
    System.out.println("Description:" +u22.getDescription());
    u22.setVersion("5.1");
    System.out.println("Version:" +u22.getVersion());
    u22.setAuthor("Pooja");
    System.out.println("Author:" +u22.getAuthor());

    System.out.println();
    UserManual u23 = new UserManual();
    u23.setManualId(23);
    System.out.println("Manual Id:" +u23.getManualId());
    u23.setTitle("Reports Guide");
    System.out.println("Title:" +u23.getTitle());
    u23.setDescription("Generating reports");
    System.out.println("Description:" +u23.getDescription());
    u23.setVersion("5.2");
    System.out.println("Version:" +u23.getVersion());
    u23.setAuthor("Ramesh");
    System.out.println("Author:" +u23.getAuthor());

    System.out.println();
    UserManual u24 = new UserManual();
    u24.setManualId(24);
    System.out.println("Manual Id:" +u24.getManualId());
    u24.setTitle("Export Guide");
    System.out.println("Title:" +u24.getTitle());
    u24.setDescription("Exporting data");
    System.out.println("Description:" +u24.getDescription());
    u24.setVersion("5.3");
    System.out.println("Version:" +u24.getVersion());
    u24.setAuthor("Sneha");
    System.out.println("Author:" +u24.getAuthor());

    System.out.println();
    UserManual u25 = new UserManual();
    u25.setManualId(25);
    System.out.println("Manual Id:" +u25.getManualId());
    u25.setTitle("Import Guide");
    System.out.println("Title:" +u25.getTitle());
    u25.setDescription("Importing data");
    System.out.println("Description:" +u25.getDescription());
    u25.setVersion("5.4");
    System.out.println("Version:" +u25.getVersion());
    u25.setAuthor("Vikram");
    System.out.println("Author:" +u25.getAuthor());

    System.out.println();
    UserManual u26 = new UserManual();
    u26.setManualId(26);
    System.out.println("Manual Id:" +u26.getManualId());
    u26.setTitle("Analytics Guide");
    System.out.println("Title:" +u26.getTitle());
    u26.setDescription("Understanding analytics");
    System.out.println("Description:" +u26.getDescription());
    u26.setVersion("5.5");
    System.out.println("Version:" +u26.getVersion());
    u26.setAuthor("Anjali");
    System.out.println("Author:" +u26.getAuthor());

    System.out.println();
    UserManual u27 = new UserManual();
    u27.setManualId(27);
    System.out.println("Manual Id:" +u27.getManualId());
    u27.setTitle("User Roles Guide");
    System.out.println("Title:" +u27.getTitle());
    u27.setDescription("Managing user roles");
    System.out.println("Description:" +u27.getDescription());
    u27.setVersion("5.6");
    System.out.println("Version:" +u27.getVersion());
    u27.setAuthor("Kiran");
    System.out.println("Author:" +u27.getAuthor());

    System.out.println();
    UserManual u28 = new UserManual();
    u28.setManualId(28);
    System.out.println("Manual Id:" +u28.getManualId());
    u28.setTitle("Permissions Guide");
    System.out.println("Title:" +u28.getTitle());
    u28.setDescription("Setting permissions");
    System.out.println("Description:" +u28.getDescription());
    u28.setVersion("5.7");
    System.out.println("Version:" +u28.getVersion());
    u28.setAuthor("Deepa");
    System.out.println("Author:" +u28.getAuthor());

    System.out.println();
    UserManual u29 = new UserManual();
    u29.setManualId(29);
    System.out.println("Manual Id:" +u29.getManualId());
    u29.setTitle("System Overview");
    System.out.println("Title:" +u29.getTitle());
    u29.setDescription("Complete system overview");
    System.out.println("Description:" +u29.getDescription());
    u29.setVersion("5.8");
    System.out.println("Version:" +u29.getVersion());
    u29.setAuthor("Arun");
    System.out.println("Author:" +u29.getAuthor());
	}
 }