class UserAccountExecutor{
 public static void main(String[] args){
    UserAccount useraccount = new UserAccount();
	useraccount.setId(1);
	System.out.println("Account Id:" +useraccount.getId());
	useraccount.setUserName("Harsha");
	System.out.println("Username:" +useraccount.getUserName());
	useraccount.setEmail("harsha190@gmail.com");
	System.out.println("Email:" +useraccount.getEmail());
	useraccount.setPassword("harsha87@1.");
	System.out.println("Password:" +useraccount.getPassword());
	useraccount.setPhone(9784561284L);
	System.out.println("Phone.no:" +useraccount.getPhone());
	useraccount.setAddress("Rajajinagar");
	System.out.println("Address:" +useraccount.getAddress());
	useraccount.setActive(true);
	System.out.println("Active:" +useraccount.getActive());
	
	
	System.out.println();
	UserAccount useraccount1= new UserAccount();
	useraccount1.setId(2);
	System.out.println("Account Id:" +useraccount1.getId());
	useraccount1.setUserName("Lohith");
	System.out.println("Username:" +useraccount1.getUserName());
	useraccount1.setEmail("Lohith190@gmail.com");
	System.out.println("Email:" +useraccount1.getEmail());
	useraccount1.setPassword("Lohith87@1.");
	System.out.println("Password:" +useraccount1.getPassword());
	useraccount1.setPhone(978478584L);
	System.out.println("Phone.no:" +useraccount1.getPhone());
	useraccount1.setAddress("BTM Layout");
	System.out.println("Address:" +useraccount1.getAddress());
	useraccount1.setActive(false);
	System.out.println("Active:" +useraccount1.getActive());
	
	System.out.println();
	UserAccount useraccount2 = new UserAccount();
	useraccount2.setId(3);
	System.out.println("Account Id:" +useraccount2.getId());
	useraccount2.setUserName("Kiran");
	System.out.println("Username:" +useraccount2.getUserName());
	useraccount2.setEmail("kiran3@gmail.com");
	System.out.println("Email:" +useraccount2.getEmail());
	useraccount2.setPassword("Kiran@123");
	System.out.println("Password:" +useraccount2.getPassword());
	useraccount2.setPhone(900000003L);
	System.out.println("Phone.no:" +useraccount2.getPhone());
	useraccount2.setAddress("Chennai");
	System.out.println("Address:" +useraccount2.getAddress());
	useraccount2.setActive(true);
	System.out.println("Active:" +useraccount2.getActive());

	System.out.println();
	UserAccount useraccount3 = new UserAccount();
	useraccount3.setId(4);
	System.out.println("Account Id:" +useraccount3.getId());
	useraccount3.setUserName("Suresh");
	System.out.println("Username:" +useraccount3.getUserName());
	useraccount3.setEmail("suresh4@gmail.com");
	System.out.println("Email:" +useraccount3.getEmail());
	useraccount3.setPassword("Suresh@123");
	System.out.println("Password:" +useraccount3.getPassword());
	useraccount3.setPhone(900000004L);
	System.out.println("Phone.no:" +useraccount3.getPhone());
	useraccount3.setAddress("Hyderabad");
	System.out.println("Address:" +useraccount3.getAddress());
	useraccount3.setActive(false);
	System.out.println("Active:" +useraccount3.getActive());

	System.out.println();
	UserAccount useraccount4 = new UserAccount();
	useraccount4.setId(5);
	System.out.println("Account Id:" +useraccount4.getId());
	useraccount4.setUserName("Ravi");
	System.out.println("Username:" +useraccount4.getUserName());
	useraccount4.setEmail("ravi5@gmail.com");
	System.out.println("Email:" +useraccount4.getEmail());
	useraccount4.setPassword("Ravi@123");
	System.out.println("Password:" +useraccount4.getPassword());
	useraccount4.setPhone(900000005L);
	System.out.println("Phone.no:" +useraccount4.getPhone());
	useraccount4.setAddress("Delhi");
	System.out.println("Address:" +useraccount4.getAddress());
	useraccount4.setActive(true);
	System.out.println("Active:" +useraccount4.getActive());

	System.out.println();
	UserAccount useraccount5 = new UserAccount();
	useraccount5.setId(6);
	System.out.println("Account Id:" +useraccount5.getId());
	useraccount5.setUserName("Vijay");
	System.out.println("Username:" +useraccount5.getUserName());
	useraccount5.setEmail("vijay6@gmail.com");
	System.out.println("Email:" +useraccount5.getEmail());
	useraccount5.setPassword("Vijay@123");
	System.out.println("Password:" +useraccount5.getPassword());
	useraccount5.setPhone(900000006L);
	System.out.println("Phone.no:" +useraccount5.getPhone());
	useraccount5.setAddress("Mumbai");
	System.out.println("Address:" +useraccount5.getAddress());
	useraccount5.setActive(false);
	System.out.println("Active:" +useraccount5.getActive());

	System.out.println();
	UserAccount useraccount6 = new UserAccount();
	useraccount6.setId(7);
	System.out.println("Account Id:" +useraccount6.getId());
	useraccount6.setUserName("Arjun");
	System.out.println("Username:" +useraccount6.getUserName());
	useraccount6.setEmail("arjun7@gmail.com");
	System.out.println("Email:" +useraccount6.getEmail());
	useraccount6.setPassword("Arjun@123");
	System.out.println("Password:" +useraccount6.getPassword());
	useraccount6.setPhone(900000007L);
	System.out.println("Phone.no:" +useraccount6.getPhone());
	useraccount6.setAddress("Pune");
	System.out.println("Address:" +useraccount6.getAddress());
	useraccount6.setActive(true);
	System.out.println("Active:" +useraccount6.getActive());

	System.out.println();
	UserAccount useraccount7 = new UserAccount();
	useraccount7.setId(8);
	System.out.println("Account Id:" +useraccount7.getId());
	useraccount7.setUserName("Manoj");
	System.out.println("Username:" +useraccount7.getUserName());
	useraccount7.setEmail("manoj8@gmail.com");
	System.out.println("Email:" +useraccount7.getEmail());
	useraccount7.setPassword("Manoj@123");
	System.out.println("Password:" +useraccount7.getPassword());
	useraccount7.setPhone(900000008L);
	System.out.println("Phone.no:" +useraccount7.getPhone());
	useraccount7.setAddress("Goa");
	System.out.println("Address:" +useraccount7.getAddress());
	useraccount7.setActive(false);
	System.out.println("Active:" +useraccount7.getActive());

	System.out.println();
	UserAccount useraccount8 = new UserAccount();
	useraccount8.setId(9);
	System.out.println("Account Id:" +useraccount8.getId());
	useraccount8.setUserName("Deepak");
	System.out.println("Username:" +useraccount8.getUserName());
	useraccount8.setEmail("deepak9@gmail.com");
	System.out.println("Email:" +useraccount8.getEmail());
	useraccount8.setPassword("Deepak@123");
	System.out.println("Password:" +useraccount8.getPassword());
	useraccount8.setPhone(900000009L);
	System.out.println("Phone.no:" +useraccount8.getPhone());
	useraccount8.setAddress("Kerala");
	System.out.println("Address:" +useraccount8.getAddress());
	useraccount8.setActive(true);
	System.out.println("Active:" +useraccount8.getActive());

	System.out.println();
	UserAccount useraccount9 = new UserAccount();
	useraccount9.setId(10);
	System.out.println("Account Id:" +useraccount9.getId());
	useraccount9.setUserName("Tarun");
	System.out.println("Username:" +useraccount9.getUserName());
	useraccount9.setEmail("tarun10@gmail.com");
	System.out.println("Email:" +useraccount9.getEmail());
	useraccount9.setPassword("Tarun@123");
	System.out.println("Password:" +useraccount9.getPassword());
	useraccount9.setPhone(900000010L);
	System.out.println("Phone.no:" +useraccount9.getPhone());
	useraccount9.setAddress("BTM Layout");
	System.out.println("Address:" +useraccount9.getAddress());
	useraccount9.setActive(false);
	System.out.println("Active:" +useraccount9.getActive());
	
	System.out.println();
	UserAccount useraccount10 = new UserAccount();
	useraccount10.setId(11);
	System.out.println("Account Id:" +useraccount10.getId());
	useraccount10.setUserName("Varun");
	System.out.println("Username:" +useraccount10.getUserName());
	useraccount10.setEmail("varun10@gmail.com");
	System.out.println("Email:" +useraccount10.getEmail());
	useraccount10.setPassword("varun10@gmail.com");
	System.out.println("Password:" +useraccount10.getPassword());
	useraccount10.setPhone(900000010L);
	System.out.println("Phone.no:" +useraccount10.getPhone());
	useraccount10.setAddress("BTM Layout");
	System.out.println("Address:" +useraccount10.getAddress());
	useraccount10.setActive(false);
	System.out.println("Active:" +useraccount10.getActive());
	
	System.out.println();
	UserAccount useraccount11 = new UserAccount();
	useraccount11.setId(12);
	System.out.println("Account Id:" +useraccount11.getId());
	useraccount11.setUserName("Earesh");
	System.out.println("Username:" +useraccount11.getUserName());
	useraccount11.setEmail("Earesh10@gmail.com");
	System.out.println("Email:" +useraccount11.getEmail());
	useraccount11.setPassword("varun10");
	System.out.println("Password:" +useraccount11.getPassword());
	useraccount11.setPhone(900000010L);
	System.out.println("Phone.no:" +useraccount11.getPhone());
	useraccount11.setAddress("BTM Layout");
	System.out.println("Address:" +useraccount11.getAddress());
	useraccount11.setActive(true);
	System.out.println("Active:" +useraccount11.getActive());

	}
	}